### ISSUE TITLE
Link in Admin info helper needs updated.

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1002]
**Summary:**

1. **What is actually happening:**
<img width="629" alt="image" src="https://user-images.githubusercontent.com/82838264/172024594-acbad7d1-b2be-447e-9fac-68ba56ddcdce.png">

Link sends users to dead docs page https://docs.coordinape.com/welcome/admin_info

2. **What should be happening:**

Update link to https://docs.coordinape.com/get-started/get-started/new-coordinape-admins

3. **Steps to recreate:**
Go to admin panel scroll to user table, hover on the i next to admin and click learn more icon.

**Comment by sshmm** [comment]
fixed by @amrro PR #1031
