### ISSUE TITLE
Broken Doc Links in Tool Tips

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1012]
**Summary:**
Broken Links in Tool Tips

We updated the docs and now these links are broken 

### My Epoch Modal 
<img width="562" alt="Screen Shot 2022-06-07 at 6 41 21 PM" src="https://user-images.githubusercontent.com/92177509/172507256-04ccbcdf-a8b1-4124-ab30-a9dc32db550b.png">
Update Learn More to [Create An Epoch Page](https://docs.coordinape.com/get-started/epochs/create-an-epoch)

### Add Contributor Button
<img width="296" alt="Screen Shot 2022-06-07 at 6 41 48 PM" src="https://user-images.githubusercontent.com/92177509/172507300-a38f4824-0aa9-4a15-b7b3-ebd71cffc2fb.png">
Update Learn More to [Member](https://docs.coordinape.com/get-started/members)

### Create Epoch Button
<img width="269" alt="Screen Shot 2022-06-07 at 6 42 23 PM" src="https://user-images.githubusercontent.com/92177509/172507356-ef180afa-b3de-47a1-9d7d-cd6c7e952036.png">
Update Learn More to [Create An Epoch](https://docs.coordinape.com/get-started/epochs)

**Comment by spydermonkee** [comment]
@ivyquinzel - For issues like this that you 100% know need to be completed, feel free to add it to the Coordinape Development project directly and put it into the "Ready for Coding" column. Additionally, the "Help Wanted" label is good to add to this one to show everyone that this is a good issue for community devs to pick up.

Good catch and thank you for making the clear GH issue!

**Comment by spydermonkee** [comment]
Also, @ivyquinzel - "Good First Issue" is a good label to show that community devs can and should pick this one up.

**Comment by reeserj** [comment]
@PrajwalBorkar You're good to go!

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar You're good to go!

Thanks. Also, can you mention in which folder are the files are as am unable to find

**Comment by levity** [comment]
Start here:
https://github.com/coordinape/coordinape/blob/main/src/pages/AdminPage/AdminPage.tsx

**Comment by ivyquinzel** [comment]
@crabsinger @spydermonkee The implementation is wrong all the links just go to the record contributions page instead of the links added to the ticket

**Comment by levity** [comment]
@ivyquinzel crap, you're right. it looks like @PrajwalBorkar implemented this correctly in #1015 and then @amrro changed them to the wrong links in #1031 (which I approved 😓)

**Comment by levity** [comment]
fixed
