### ISSUE TITLE
Add created_at and updated_at columns to circle_integrations table

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1014]
**Problem**
We don't have a way to track growth of integrations 

**Solution**
Add created_at and updated_at columns to circle_integrations table so we can track integration growth

**Specification**
Add created_at and updated_at columns to circle_integrations table

**Stakeholders**
Who needs to provide input? Who might be impacted? Who needs to approve?
@zashton is the backend guru

**Comment by crabsinger** [comment]
+1! I think all tables should have these fields, as ageneral rule.
