### ISSUE TITLE
New user creating circle gets a null error trying to read organization property, seems like circle didn't create but it did

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1044]
**Summary:**

1. **What is actually happening:**

After creating a circle, the circle is actually created but there is an error reported about unable to read organization because of a null value. 

3. **What should be happening:**

it should navigate to the circle instead of throw an error

5. **Steps to recreate:**

1. sign up with new address
2. create circle from ui 
3. this calls createCircle custom action
4. it does stuff, calls a mutation that inserts a circle, gets back a valid id
5. that returns the id properly in the createCircleAction  { id: 92 }
6. the custom action is properly setup w/ a relationship to circle 
7. circle is null in the mutation response data and we get an error in the snackbar

**Comment by sshmm** [comment]
I tried to reproduce this issue but I couldn't. I navigated to new circle page without problems.
@CryptoGraffe  would you mind retesting the scenario?

**Comment by levity** [comment]
This one's fixed, I think? @CryptoGraffe
