### ISSUE TITLE
Double the limit of the character count in the epoch's contribution field

### ISSUE THREAD

**Issue by georgepor** [coordinape/coordinape#1050]
**Problem**
We have 2-week epochs, during which many contributors are working on multiple projects. Even a very concise and cogent description of their contributions doesn't fit in the current 560-character limit.

**Solution**
Double the limit of the character count to 1120.

**Specification**
What precisely needs to get built? (include any requirements or design files)

**Stakeholders**
Who needs to provide input? Who might be impacted? Who needs to approve?

**Comment by levity** [comment]
Thanks for the suggestion, @georgepor! This is a quick thing to change, without any major downside I can foresee, so I just went ahead and did it.

**Comment by georgepor** [comment]
Thank you so much!
george
--
*George Pór*
Researcher in Self-Organizing Collective Intelligence
Mentor to visionary leaders and transformative communities



Founder, Dir. of Research, FUTURE HOW <http://futurehow.site/>,
Action Research for Regenerative Futures
President, Campus Co-Evolve <https://campus-coevolve.org/>, a virtual
university for evolutionary agents
Founder, Enlivening Edge <https://www.enliveningedge.org/> media hub for
amplifying the evolution of organizations and social systems

Medium:     ***@***.***
Facebook:  https://www.facebook.com/EvolutionaryAgent/
LinkedIn:    linkedin.com/in/georgepor <http://uk.linkedin.com/in/georgepor>
Twitter:      https://twitter.com/technoshaman
