### ISSUE TITLE
Bug: All Circle members should be displayed when Team Selection Enabled is set to "No"

### ISSUE THREAD

**Issue by aahna-ashina** [coordinape/coordinape#1058]
**Summary:**

1. **What is actually happening:**
When Teammate selection is set to NO, no circle members are displayed.

2. **What should be happening:**
When Teammate selection is set to NO, all circle members are displayed.

4. **Steps to recreate:**
Create a new Circle, switch "Team Selection Enabled" from "Yes" to "No", add members, start an epoch.

6. **Screenshots/GIF/Video recording**
[Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.
](https://discord.com/channels/845400066532704256/852628536530829352/988366602732965928)

**Comment by levity** [comment]
@reeserj @aahna-ashina what circle is this happening in?

**Comment by levity** [comment]
a fix is going out now. please comment if you're still seeing issues
