### ISSUE TITLE
1.5.4 - Circle Overview page: New epoch buttons

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#1060]
**Current Section** [figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=2970%3A5029)
- Contributions Section
  - Until the Contributions are built out in #862 this should just take users to edit their epoch statement when they click add contribution
  - The gray text below should tally the days since the epoch started
- Allocate 
    - This should calculate what % of their give they need to allocate
    - the grey text below should count the allocations received | given
- Remove the Nominations box

**Add Completed Section** [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5223%3A20957)
-  All users should be able to see the export distribution csv
@smombartz Should this section mirror the Past sections? but just have a special button to submit the distributions?

**Comment by reeserj** [comment]
@yahiamarzouk you want to try this one?

**Comment by yahiamarzouk** [comment]
> @yahiamarzouk you want to try this one? 

I will look into it before u assign 👌🏼👍🏻

**Comment by levity** [comment]
let's check in as a team about this one--not sure it still makes sense as written. @ivyquinzel @spydermonkee

**Comment by ivyquinzel** [comment]
I think we just need to close this ticket a lot of this work has been done by wing or no longer needed
