### ISSUE TITLE
Overview & profile menus should always close once you’ve made a choice

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#1068]
**Problem**
When clicking something in the upper left and right nav menus, if the result is that the site _does not_ navigate to somewhere else, the nav menu simply doesn't go anywhere.
Examples: 
- While on overview page, click overview on upper left nav menu. Nav remains. 
- While on overview page, click "Circles" on upper right nav menu. Nav remains. 
- While on a circle overview page, click the circle in the upper left nav menu. Nav remains.

**Solution**
Overview menu and profile menu should always close once you’ve made a choice

**Comment by levity** [comment]
reverted in #1084, fixed in 4fa167203
