### ISSUE TITLE
Create Epoch button is mislabeled Add Contributor

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1082]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/95149165/175654924-9bf90dbd-4a10-4c9d-8a2e-f12c653574ab.png">

**Comment by reeserj** [comment]
@CryptoGraffe is this a help wanted or are you fixing it?

**Comment by CryptoGraffe** [comment]
@reeserj i fixed it
