### ISSUE TITLE
If user cancels tx to create distribution, delete the pending record & claims from the database

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1095]
during the submission of a distribution, we create a db record first without a tx hash, then submit the tx, then save the tx's hash in the db. if the user cancels the process by rejecting the tx, we should delete the db records that we created.

**Comment by reeserj** [comment]
@teeolendo how's this coming?

**Comment by levity** [comment]
I don't think he's working on it. @zashton is tho. Anyway we can close this for now because we're tracking it in notion
