### ISSUE TITLE
1.5.4  Implement Overview Page Updates 

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1124]
### Summary

This ticket is to update the current overview page (https://app.coordinape.com/circles) to reflect the new 1.5 app design. There are new design changes to the page, and changes to the default empty state of the page for new users. The scope includes updating the header, styling, and adding buttons. 

- [x] Users belonging to Orgs/ Circles see the new designs
Our current instance needs to reflect the design **below** 
[Overview UI ](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=4702%3A11975 )

- [x] New users see the Get Started content if they belong to no Orgs / Circles.
New User (not a part of any Orgs / Circles) Welcome Page 
[Overview New User Exp ](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=6434%3A27983)

If you have any questions about the designs, or things are not clear from the Figma, please reach out in Discord!

### Specification

**Overview Spacing** 
Organizations should be 48px apart. Circles should be 32px apart. 

**Overview Header** 
Add a header to the page with the  "Overview"  the subtitle should be "All your organizations and circle in one place."  in the same div.

**Header Styling** 
font-weight: 600;
font-size: 48px;

**Organizations Logo** 
The organization logo should only be 32x32px. 

**Circle Card Styling** 
The circle name in the card should be **H3 styling.** Epoch Name should be **H3 Style**, and the Date should be H3 Bold. Both should be on the same line instead of stacked. 

**H3 CSS**
font-weight: 600;
font-size: 24px;
line-height: 120%;

**Circle Status** 
The circle status should be in the second row. The styling should be body small. 

**Body Small**
font-weight: 400;
font-size: 13px;
line-height: 130%;

### Assumption 
I assume that the styling referenced above is in our design library. Some of the classes may not reflex the intended design in Figma. Please use Figma styling as a source of truth. If the dev instance doesn't reflect that, please update. 

### After Deployment Checklist:
- [ ] Update "Get Started" on the homepage to link to this page - **this is not part of this ticket**

### Stakeholders
@smombartz

**Comment by spydermonkee** [comment]
@ivyquinzel & @smombartz - When this ticket is completed and the Overview page is updated to the 1.5 design with content, one of you will be able to change the URL in the "Get Started" button on the homepage to `/circles` rather than what it is today `/new-circle`.
