### ISSUE TITLE
1.5.4 Add circle logo field to create-circle form

### ISSUE THREAD

**Issue by wingfeatherwave** [coordinape/coordinape#1130]
**Problem**
Circle logo cannot currently be added until a circle is created

**Solution**
Modify new circle form mutation to include adding circle logo image

Part of https://github.com/coordinape/coordinape/milestone/16

([Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=4786%3A13470))

**Comment by reeserj** [comment]
@wingfeatherwave is this a good community ticket?

**Comment by wingfeatherwave** [comment]
@reeserj yes.  And I think @sshmm would be a good candidate as they've worked on some similar items

**Comment by sshmm** [comment]
@levity @spydermonkee  while at it should I remove the deprecated_ fields and change the form to react-hook form?
