### ISSUE TITLE
Mobile ui not fully displayed

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1137]
**Summary:**

1. **What is actually happening:**
Mobile ui chops the edges off in admin settings screen 
![Screenshot_20220812-084855_MetaMask.jpg](https://user-images.githubusercontent.com/82838264/184367265-4ec1bc4f-b5ab-43fb-b518-24865ee6ce0c.jpg)

2. **What should be happening:**
All items should be displayed when on mobile 

3. **Steps to recreate:**
Open app in narrow screen
Go to admin settings

**Comment by yahiamarzouk** [comment]
@reeserj can I have this one please?

**Comment by yahiamarzouk** [comment]
@reeserj 
The mobile UI bug is not about the box 
it's the continent of the radio button are next to each other on the mobile UI on `flexDirection: 'row'` .
<img width="1440" alt="Screen Shot 2022-08-16 at 5 51 10 PM" src="https://user-images.githubusercontent.com/94828675/184924630-a5889099-8cd5-4e05-89a6-b7d017e1dcf0.png">


if I changed the radio buttons to be over each other as in `flexDirection: 'column'` it will look much better and then bug would be fixed (on mobile phones)
<img width="1440" alt="Screen Shot 2022-08-16 at 5 51 47 PM" src="https://user-images.githubusercontent.com/94828675/184924706-46f66288-fcf9-48d8-bed9-6f4589c4f3a6.png">

nut it wouldn't look as great on normal browsers 
<img width="1440" alt="Screen Shot 2022-08-16 at 5 51 37 PM" src="https://user-images.githubusercontent.com/94828675/184924879-e0b106c3-7fed-41b8-9043-650c8f1ba8bd.png">

any thoughts?
do u want to proceed with the fix?

**Comment by sshmm** [comment]
@yahiamarzouk  I think it is better to add flexWrap:wrap to the flex div that contains these radio buttons and they will wrap when the width goes narrower
![image](https://user-images.githubusercontent.com/34943689/184931661-618b045d-54f9-467b-92b0-bda9b4f77700.png)

**Comment by yahiamarzouk** [comment]
@sshmm now it's fixed and conditionally rendering depends on the width, thanks

**Comment by reeserj** [comment]
Closing with the merged change
