### ISSUE TITLE
Allow editing current epoch

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1138]
Follow-up to #1114 

The current epoch should also be editable, the same way that upcoming epochs are, except that you can't change the start date.

The edit button should go at the top right of the CurrentEpochPanel, pushing the Nominations & Allocations cards down.
<img width="605" alt="Coordinape" src="https://user-images.githubusercontent.com/193667/179033924-d9406599-8c11-4726-86c5-0a4f84069dce.png">

**Comment by spydermonkee** [comment]
@levity , @sshmm - This seems like a high priority to correct since it's a significant product behavior regression. @sshmm , do you have bandwidth to prioritize this? @levity, do you have any thoughts about this?

**Comment by levity** [comment]
> @levity , @sshmm - This seems like a high priority to correct since it's a significant product behavior regression. @sshmm , do you have bandwidth to prioritize this? @levity, do you have any thoughts about this?

If @sshmm has bandwidth today/tomorrow it should be a pretty quick fix, since it's very similar to what he just did for upcoming epochs. Otherwise I'll work on it tomorrow.

**Comment by sshmm** [comment]
@spydermonkee I will start working on it in less than an hour

**Comment by spydermonkee** [comment]
Awesome, thanks a lot @sshmm and @levity!
