### ISSUE TITLE
1.5.4 - Create Circle in New Org button

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#1143]
On Overview page, to the right of the header, please add a "Create Circle in New Organization" button. This button should lead the user to the circle creation page, with the Organization field empty.

[Overview UI ](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=4702%3A11975 )

### Acceptance Criteria
Scenario: User wants to create a new organization 
When: They are on the overview page 
Given: That the "Create Circle in New Organization" button is on the right 
When: They  click "Create Circle in New Organization" 
Then: The circle creation page populates

**Comment by levity** [comment]
Apologies if I’m jumping in without knowing full context, but my gut
feeling has been that this would be good to put at the bottom of the page,
underneath existing orgs, because it’s infrequently used and thus shouldn’t
be prominent.

**Comment by spydermonkee** [comment]
I'm totally open to other UI changes to this. It seems fine to me to be in that location, since it's part of the header and otherwise empty space. We just need to get a clear, non-hacky way for people to create new orgs/circles back into the app quickly.

**Comment by wingfeatherwave** [comment]
@levity @spydermonkee I can see both working well.  My hesitation with putting it at the bottom is that it would be difficult to find when there are many circles / orgs.  But like you said, if it's rarely used, then it likely doesn't deserve prime real estate.  I'm going to place it in the header for now, but am certainly open to exploring moving it later.
