### ISSUE TITLE
Add text that indicates Yearn Vault

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#1156]
When Creating DAI/USDC Vaults from buttons, we need to add text above the buttons that says, “Create a CoVault that utilizes Yearn Vaults[LINK TO YEARN] to earn yield:”
    
Then also text above the simple token entry box that says, ”Create a CoVault with any ERC-20 token:”

**Comment by levity** [comment]
Done in [3972ee4](https://github.com/coordinape/coordinape/commit/3972ee4acdfaaa9ecce1c699679a5cc4e19b332e)
