### ISSUE TITLE
Member Self Opt Out Fix 

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1162]
### **Problem**
On the allocation page, members are accidentally opting themselves out since it is the first option on the page. 

### **Solution**
Opt-In should be the first option on the allocation page and preselected for the user. 

### **Specification**
On the Allocation page, the options need to be flipped. It should appear as follows. 

**Example**
Should you receive GIVV distributions in the Apes Circle during this epoch?
(Selected) Opt-In
I want to be eligible to receive GIVV

Opt-Out
I am paid sufficiently via other channels.

### **Acceptance Criteria** 
Scenario: User wants to allocate
Given: The user is on the allocate page
Then: Opt-In should be selected

### **Stakeholders**
@spydermonkee

**Comment by topocount** [comment]
@ivyquinzel to clarify, the current state is that the radio button reflects the user's non_receiver setting on page load. If they non_receiver == false, they are opted in. If non-receiver == true, they are opted out.

I can change the presentation such that opted-in is the first option on the left, but im hesitant to change the behavior described above. Curious to hear your thoughts

**Comment by ivyquinzel** [comment]
The desired effect is making Opt In the default and opting out should be slightly harder to do. I want the user to have to consiously opt out of every epoch. We want to encourage and lean users towards participation.

**Comment by levity** [comment]
If I'm understanding this change correctly, there's now no way for a user to answer the question, "Am I opted-in or not?"
