### ISSUE TITLE
Minor controller update to DistributionForm

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#1168]
Update DistributionForm to use `useController` instead of `FormControl`

**Comment by sshmm** [comment]
@reeserj  @zashton  is anyone working on this? can I work on it?

**Comment by reeserj** [comment]
You got it @sshmm

**Comment by levity** [comment]
Beware though, this is a very active area of the code right now. You may
want to coordinate with @topocount in Discord so you don't conflict
