### ISSUE TITLE
Improve transitions between pages

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1211]
Notes from a discussion with Sascha about how to improve the look & feel of transitions

Check out [this Figma prototype](https://www.figma.com/proto/L4oZwYVUdpgacZtwipGaYe/App-1.5?page-id=2603%3A3922&node-id=15826%3A56885&viewport=-15805%2C3508%2C0.46&scaling=min-zoom&starting-point-node-id=15826%3A56885&show-proto-sidebar=1), which shows a fade-in/out animation when switching between pages

- Note that the animation and circular spinner doesn't cover up the menu

**Comment by reeserj** [comment]
@wingfeatherwave this feels like something for the refinement pod.

Question is can this be a community issue?

**Comment by reeserj** [comment]
Closing to redefine if we need to address later
