### ISSUE TITLE
Create New Circle Button from Admin Page doesn't prepopulate the existing Org name anymore

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1226]
**Summary:**

1. **What is actually happening:**
Creating a new Circle button prompts the user to re-type the org name. If a typo is made it will create a new org rather than just a new circle

2. **What should be happening:**
Org name should pre-populate with the existing Org name and allow users to change it if they choose

3. **Steps to recreate:**
Create a new circle from the admin page

4. **Screenshots/GIF/Video recording**
<img width="816" alt="image" src="https://user-images.githubusercontent.com/82838264/182744479-3a8a6e2b-9f73-44ba-9cf6-5607c8e628a2.png">

**Comment by reeserj** [comment]
@spydermonkee if this is the expected behavior feel free to close

**Comment by spydermonkee** [comment]
@reeserj - I left a message in Discord, but this is working as expected. When "Create New Circle" button is used, it's meant to be an option that also allows a new org. When "Add Circle" button is used (the ones near orgs on the Overview page), the org should pre-populate. Can you try that and verify?

**Comment by reeserj** [comment]
@spydermonkee it's not prepopulating from the admin panel or the top level create a circle button, but it does work from the org overview page. 
![Create Circle bug](https://user-images.githubusercontent.com/82838264/183297277-06700f05-85e0-4d88-9a5b-25c04850bd97.gif)

**Comment by levity** [comment]
Ah. The admin panel behavior is a bug. But then again, do we even still
want that button there?

**Comment by reeserj** [comment]
Closing because this button is going away
