### ISSUE TITLE
Bug: Continue with this team is under the pfps on select team screen

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1229]
**Summary:**

1. **What is actually happening:**
The team member PFP's are displaying above the continue with this team button when scrolling

2. **What should be happening:**
The select team member PFP's should be on the same level as the team name "pills" 

3. **Steps to recreate:**
open a circle with team selection enabled and scroll. 

4. **Screenshots/GIF/Video recording**
![image](https://user-images.githubusercontent.com/82838264/183139648-0ad98da6-f394-49aa-8981-61a6f9cb645e.png)

**Comment by yahiamarzouk** [comment]
can I have it?

**Comment by yahiamarzouk** [comment]
> > can I have it?
> 
> Yep!

don't I need to be in a circle?
what exactly is required from me to do please?

**Comment by spydermonkee** [comment]
@reeserj - the description on this issue is empty for me. Is that intentional or is there more info?

**Comment by reeserj** [comment]
Fixing @spydermonkee not sure where it went

**Comment by reeserj** [comment]
> > > can I have it?
> > 
> > 
> > Yep!
> 
> don't I need to be in a circle? what exactly is required from me to do please? and who should I report to?

You'll need to create a circle in your local environment with several addresses so you can get enough members down to the continue with this team button on the select team screen. 

Once you've done that fix the bug, and submit a PR to fix this issue.
