### ISSUE TITLE
Bug: Support Argent (EIP 1271)

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1242]
**Summary:**

1. **What is actually happening:**
When logging in with smart contract wallet we get a 401 error we don't currently support [EIP 1271 ](https://eips.ethereum.org/EIPS/eip-1271)

2. **What should be happening:**
Login should not be any different than logging in with Metamask

3. **Steps to recreate:**
Log in with or Argent

4. **Screenshots/GIF/Video recording**
![Smart contract wallet error](https://user-images.githubusercontent.com/82838264/183248142-8ca16477-b28b-4a4d-8911-34daf3940af2.gif)

Placed in vaults due to the need for users to deposit with gnosis safe

**Comment by reeserj** [comment]
We had argent working in #232 But looks like we've broken that. Could have been when we did #375

**Comment by levity** [comment]
@FelipeAleixo any chance you'd be able to help us with this one? Maybe it's a known issue or something misconfigured on our side.

**Comment by FilipeAleixo** [comment]
@levity I'm currently on a break, but will try to point you out into the most likely source of this error. I was trying to create a gnosis safe on Rinkeby to be able to reproduce myself, but the coordinape app only works on mainnet, so I couldn't.

The signatures coming from EOA's and contracts need to be validated differently, and I am not sure whether SIWE is currently able to also validate signatures coming from contracts out of the box. See here the removal of this different validation for EOA's and contracts and replacing it with validation with SIWE https://github.com/coordinape/coordinape/pull/991/files#diff-01abf081aaf21c9dd7749fceb2eaf3c000f88207e51f4a1ab234455045e4d2deL27

I think the best course of action is to submit an issue on https://github.com/spruceid/siwe and asking whether it should be able to validate contract signatures out of the box. If it should, then perhaps the signature data isn't being sent correctly from the front-end for some reason.
