### ISSUE TITLE
Bug: Mobile Map is not responsive to touch

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1248]
**Summary:**

1. **What is actually happening:**
Map is static and doesn't respond to touch on Android mobile

2. **What should be happening:**
Map should interact to touch

3. **Steps to recreate:**
Open map on mobile app and try to select app

4. **Screenshots/GIF/Video recording**
![Screenshot_20220808-132753_MetaMask.jpg](https://user-images.githubusercontent.com/82838264/183488147-5ff8d201-73c6-4b2b-8090-c501f638b0a8.jpg)

**Comment by sshmm** [comment]
I found the problem but still experimenting for a solution
