### ISSUE TITLE
Cannot Access Vaults Page from fresh Account

### ISSUE THREAD

**Issue by topocount** [coordinape/coordinape#1252]
**Summary:**

1. **What is actually happening:**

Clicking On the CoVaults link hits an error boundary:

```
Error: can't access property "id", orgsQuery.data.organizations[0] is undefined
```

since the profile is not a part of any orgs.

2. **What should be happening:**

Either we hide the coVaults menu button if the user has no orgs or we create an
empty page

3. **Steps to recreate:**

In staging log in with a fresh user to create a new account and then click on
CoVaults in the menu.

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides devElopers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.
![image](https://user-images.githubusercontent.com/17910833/183711807-e5b8312a-42a3-4654-9f00-555ef65589fb.png)

**Comment by sshmm** [comment]
@yahiamarzouk

**Comment by yahiamarzouk** [comment]
@topocount
I've been trying to find the issue 
as I logged in with a fresh account and there were no CoVaults button so it would make the error by user...

<img width="1440" alt="Screen_Shot_2022-08-15_at_4 32 29_PM" src="https://user-images.githubusercontent.com/94828675/184656307-6c248cf1-af28-4644-b418-40b72ceaf570.png">

but when I entered the rout " /vault " it showed the error.

<img width="1440" alt="Screen_Shot_2022-08-15_at_4 26 19_PM" src="https://user-images.githubusercontent.com/94828675/184656668-b683c795-bc6b-4fbf-a88f-3a99b30e6f59.png">

**Comment by topocount** [comment]
@yahiamarzouk you'll want to enable the feature flags found here in your .env: https://github.com/coordinape/coordinape/blob/739194856db853ee878608e00d6d305a3c9a0770/src/config/features.ts#L9-L10

just set those environment variables to `true` and the page will show up

**Comment by topocount** [comment]
I think hiding covaults for a fresh user who isnt a part of any orgs is the route we want to take for now, btw

**Comment by topocount** [comment]
@yahiamarzouk if you want to seed your address to seed what a nonfresh account looks like, you can set your address here: https://github.com/coordinape/coordinape/blob/feat/add-members-basic/.env.example#L2

**Comment by yahiamarzouk** [comment]
> @yahiamarzouk if you want to seed your address to see what a nonfresh account looks like, you can set your address in .env like here: https://github.com/coordinape/coordinape/blob/feat/add-members-basic/.env.example#L2

I just entered with a Dif add than what's in then .env
