### ISSUE TITLE
SPIKE: Zodiac plugin for Gnosis Safe - Admin Vaults

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1255]
**Problem**
What problem is this feature addressing?
Currently a circle admin can drain a vault without triggering another signature from the multisig

**Solution**
What's your proposed solution to the problem?
We need to have distributions be behind a multi-sig approval

**Specification**
What precisely needs to get built? (include any requirements or design files)
TBD

**Stakeholders**
Who needs to provide input? Who might be impacted? Who needs to approve?
@spydermonkee @levity @topocount

**Comment by karelianpie** [comment]
@reeserj feel free to assign this to me, I'll start discovering it

**Comment by levity** [comment]
closing this as a duplicate; we'll use #1253 instead to coordinate around Gnosis Safe matters
