### ISSUE TITLE
Allocations Page allows non integer GIVE inputs

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1292]
**Summary:**

1. **What is actually happening:**

On the Allocation page, the FE allows decimals GIVE, but the backend rejects this as invalid input (correctly.

3. **What should be happening:**
The FE doesn't allow decimal GIVE, and shows an error if it happens.

5. **Steps to recreate:**

Go to Allocation page and enter `12.345` in someones GIVE allocation.

7. **Screenshots/GIF/Video recording**

<img width="1467" alt="Screen Shot 2022-08-19 at 9 40 29 AM" src="https://user-images.githubusercontent.com/83605543/185666801-72fda6d6-003b-4080-b2f1-f291209587a7.png">

<img width="1506" alt="Screen Shot 2022-08-19 at 9 40 44 AM" src="https://user-images.githubusercontent.com/83605543/185666791-5d053e4e-5beb-4480-9ac1-ba74b3722ef4.png">

**Comment by yahiamarzouk** [comment]
@crabsinger 
I have been able to turn any decimal the user write into real number 
but the dom don't update with it 
so the amount of Give available don't change from decimal to real and still causes the bug if the user accepted the converted number 

https://user-images.githubusercontent.com/94828675/185745296-91f3529a-c754-40f7-bca8-8197047658d0.mov

**Comment by yahiamarzouk** [comment]
@crabsinger  please assign 
I fixed the problem

**Comment by crabsinger** [comment]
resolved

**Comment by crabsinger** [comment]
nice work @yahiamarzouk!

**Comment by yahiamarzouk** [comment]
> nice work @yahiamarzouk!

@crabsinger thanks, that means a lot 👌🏼🎉
Can't wait for my next issue
