### ISSUE TITLE
Update nav for members and admin (settings)

### ISSUE THREAD

**Issue by wingfeatherwave** [coordinape/coordinape#1313]
- [ ] In the main nav the `Admin` button currently links to `/circles/999/members`... change that button text from `Admin` to `Members`
- [ ] In the main nav create a new button that links to `/circles/999/admin`.  Call that button `Admin`
- [ ] Remove settings button from /members because it's now in the header
- [ ] Remove Add circle button from /members

Figma: https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=11000%3A30373

PR to `members-page-updates` instead of main until all of 1.5.5 is complete

**Comment by sshmm** [comment]
@wingfeatherwave  is 1.5.5 complete?
