### ISSUE TITLE
Nominees section of Circle Members

### ISSUE THREAD

**Issue by wingfeatherwave** [coordinape/coordinape#1315]
Reference nominee info on /vouching 

- [ ] Create Nominees table (use `makeTable`)
- [ ] Click nominee to expand info about the nominee
- [ ] Vouch button on each nominee row

Figma todo... add multiple nominees. 

Figma: https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5969%3A31045

PR to `members-page-updates` instead of main until all of 1.5.5 is complete

**Comment by reeserj** [comment]
Hey @sshmm are you blocked by anything here?

**Comment by sshmm** [comment]
> Hey @sshmm are you blocked by anything here?

@reeserj hey. No everything is ok. I will open the pr today or tomorrow max

**Comment by reeserj** [comment]
Wahoo!
________________________________

**Comment by sshmm** [comment]
closed by #1344
