### ISSUE TITLE
Members table

### ISSUE THREAD

**Issue by wingfeatherwave** [coordinape/coordinape#1316]
- [ ] Admins can use `Manage Member` button to toggle open member settings (talk to @wingfeatherwave about this... building the new settings UI will be tricky.  I think use a kind of popover OR use a new tr with full colspan td)
- [ ] Edit member in new "drawer/popover" a la Figma (ask team for more clarification if needed)

Figma todo:
❌ Eth Wallet Column
❌ Discord Linked Column

PR to `members-page-updates` instead of main until all of 1.5.5 is complete

**Comment by sshmm** [comment]
reminder to remane AdminPage.tsx to MembersPage.tsx after/before merging members-page-updates

**Comment by sshmm** [comment]
@wingfeatherwave I used a new row 'tr' for nominee settings. should I do the same for members or use a popover?

**Comment by wingfeatherwave** [comment]
@sshmm I think new tr is the better way to go
