### ISSUE TITLE
When submitting Create Circle, email address validation error doesn't show unless the field has been focused and blurred

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1333]
**Summary:**

1. **What is actually happening:**

If you go to create circle and put in a valid circle name but no email address, then hit submit, the error message doesn't show up on the form field until you focus it and blur it. 

3. **What should be happening:**

On submit all validation errors should be visible

**Comment by yahiamarzouk** [comment]
can I have a screen shot of the error?
or the content of the error

**Comment by sshmm** [comment]
@CryptoGraffe I think we should change this form to use react hook form.
@yahiamarzouk  I'd like to walkthrough @yahiamarzouk  in this so he gets more familiar with the libraries we are using. @CryptoGraffe @reeserj  what do you think?

**Comment by yahiamarzouk** [comment]
@reeserj can I have this issue please?

**Comment by yahiamarzouk** [comment]
@reeserj this issue should be closed
