### ISSUE TITLE
Remove Custom Token Name

### ISSUE THREAD

**Issue by topocount** [coordinape/coordinape#1335]
# What's Happening:
Users have the ability to designate a custom GIVE Token name, this causes some confusion for users when all of our docs refer to GIVE. 

![Image](https://user-images.githubusercontent.com/82838264/190436962-e67f0382-006c-459d-8344-a1eb9ac9675f.png)

# What should be Happening:
We need to disable the custom Token name on FE in the admin menu, and disable the ability to change their token name. 

We do not want to change any circles that are currently using a custom token name at this time.

Please ensure that the remaining fields fill the general box to match the fixed payments layout.

#### More detail:

If a custom token name is not set for the circle, the config should be hidden from the admin menu. and it should be impossible to begin using it. We'll also want to add a backend validation that rejects custom token names if one is not already set.

This is a low-risk step to being deprecating this feature. In the future we can consider removing all circles' use of it and refactoring the frontend to remove references to it, based on audits of current use patterns

**Comment by karelianpie** [comment]
I'll pick this one as I've done some work in the past related to this, albeit it was adding a custom token name
