### ISSUE TITLE
Developer console link isn't setting authorization header

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1391]
1. **What is actually happening:** In dev, the link to API explorer from /developers doesn't set the Authorization header

2. **What should be happening:** It should set the Authorization header so that you can immediately use the console as that user

3. **Steps to recreate:** visit /developers in a dev server and click the Open API Explorer button

Maybe this broke due to the recent upgrade to hasura-cli?

**Comment by crabsinger** [comment]
@levity this works on prod, are you testing this on localhost?

**Comment by levity** [comment]
> @levity this works on prod, are you testing this on localhost?

yep, in local dev
