### ISSUE TITLE
manual entry into the GiveAllocator can't erase the 0 because gifts is non optional

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1401]
The new GiveAllocator allows for manual entry of a number, but you can't actually erase the 0 to start from scratch. I think we need to make the tokens field optional to fix this bug I haven't investigated.

The field should probably also use some kind of zod validation.

**Comment by karelianpie** [comment]
I'll look into this once https://github.com/coordinape/coordinape/pull/1384 is merged

**Comment by crabsinger** [comment]
@karelianpie #1384 is merged.

**Comment by karelianpie** [comment]
> @karelianpie #1384 is merged.

Will work start working on this then, thanks for the heads up 👍
