### ISSUE TITLE
Visual regression on the epoch dropdown on the map

### ISSUE THREAD

**Issue by karelianpie** [coordinape/coordinape#1409]
**Summary:**

1. **What is actually happening:**

![image](https://user-images.githubusercontent.com/78794805/192841656-2f8c5ede-7d71-4d86-b8dd-a6806e4deb62.png)

3. **What should be happening:**

It should have a border & be full-width.

5. **Steps to recreate:**

Go to the maps page

**Comment by karelianpie** [comment]
Root cause was this change https://github.com/coordinape/coordinape/pull/1268/files#diff-04f735dc4a31f83d2f95252292d564b622a5b6b5039dbd2cef7ca5b2c297b6efR25

**Comment by wingfeatherwave** [comment]
Resolved with https://github.com/coordinape/coordinape/pull/1438
