### ISSUE TITLE
Map should not be cut off at top of page

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1421]
![Coordinape](https://user-images.githubusercontent.com/193667/192940640-b4b7a9d1-2338-462d-841b-8e57dbc52938.png)

**Comment by levity** [comment]
@karelianpie maybe while you're working on the map page, you could look into this one as well?

**Comment by karelianpie** [comment]
> @karelianpie maybe while you're working on the map page, you could look into this one as well?

Yup, happy to, just assigned this to myself
