### ISSUE TITLE
Give Users the option to leave Circles

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1431]
### What's happening:
Once a user is a added to a circle they cannot leave the circle.
### What should be happening:
Users should have the option leave a circle at their choosing. See Figma designs @Ivyquinzel Please drop Figma design here
### Backend Considerations:
Users who leave the circle should be treated like they've been deleted from the circle. 

Assign to Sshmm once issue created

@Topo to update API Endpoint once the build is ready.

FIGMA: https://www.figma.com/proto/L4oZwYVUdpgacZtwipGaYe/Coordinape-App?node-id=14369%3A36225&scaling=min-zoom&page-id=14369%3A30224&starting-point-node-id=14369%3A37093&show-proto-sidebar=1

**Comment by reeserj** [comment]
@ivyquinzel can you drop a figma link to what this should look like?

**Comment by ivyquinzel** [comment]
https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=14369%3A37093
