### ISSUE TITLE
Modal should be scrollable?

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1440]
The vault creation modal is getting long enough that it should be scrollable, otherwise the button at the bottom of the form is likely to be offscreen and inaccessible.

I added a question mark to the issue title because maybe we should convert it into a drawer instead of a centered modal. @wingfeatherwave @ivyquinzel what do you think?

**Comment by ivyquinzel** [comment]
I think drawer is the right pattern for creating and modifying. Modals should be warnings and confirmations

**Comment by levity** [comment]
Fixed in c99f90fe0f5f0f255dda3212e5af86f8f6f0f364
