### ISSUE TITLE
Publish Storybook

### ISSUE THREAD

**Issue by karelianpie** [coordinape/coordinape#1453]
**Problem**

Spin-off https://github.com/coordinape/coordinape/pull/1442#issuecomment-1266137417 - At the moment there's no hosted version of Storybook, so the only way to check the stories is to run Storybook locally which adds an extra step and complexity.

**Solution**

[Publish Storybook](https://storybook.js.org/docs/react/sharing/publish-storybook) in their recommended app; [Chromatic](https://www.chromatic.com/), a free publishing service made for Storybook that documents, versions, and indexes your UI components securely in the cloud.

**Specification**

1. Sign up with your GitHub, GitLab, Bitbucket, or email and generate a unique `project-token` for the project;
2. Configure the environment variables provided by GitHub so that we don't need to hard code the `project-token`. Refer to the [official documentation](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) on how to configure them.

**Stakeholders**

@crabsinger

**Comment by levity** [comment]
Could this just be hosted on a vercel app or something even simpler like
surge.sh? Since the project is open-source, we don't have to worry about
access control, so being able to avoid having to create accounts and
configure environment variables and so forth would be great.

**Comment by levity** [comment]
Hmm, interesting. Could be worth it. I'm open to it; let's let some
more people on the team weigh in as well. @crabsinger @wingfeatherwave

**Comment by crabsinger** [comment]
Setup a vercel deploy that runs `yarn build-storybook` on every push to main hosted at https://coordinape-storybook.vercel.app/
