### ISSUE TITLE
Epoch Statement text field on new give workflow should probably maintain whitespace

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1481]
**Summary:**

1. **What is actually happening:**

Text is losing its formatting 

2. **What should be happening:**

It should keep its formatting

3. **Steps to recreate:**

4. **Screenshots/GIF/Video recording**
See this text that should be prettier/ white-space:pre :

<img width="620" alt="image" src="https://user-images.githubusercontent.com/95149165/194415999-190b5073-4a04-4f19-8cae-e19d367e9f1b.png">

**Comment by yahiamarzouk** [comment]
@reeserj can I have this issue?

**Comment by wingfeatherwave** [comment]
fixed with #1554
