### ISSUE TITLE
Visual inconsistencies between all-orgs and one-org pages

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1487]
All-orgs page:

<img width="310" alt="Screen Shot 2022-10-10 at 11 13 02 PM" src="https://user-images.githubusercontent.com/193667/194899035-e63b480d-32f3-4837-9fc9-25f20a430886.png">

One-org page:

<img width="309" alt="Screen Shot 2022-10-10 at 11 13 08 PM" src="https://user-images.githubusercontent.com/193667/194899067-d275ab3f-8c5e-40f8-845c-c93f73015941.png">

As is visible in the screenshots:
- Font weight differs
- Vertical alignment with image differs

**Comment by levity** [comment]
cc @crabsinger

**Comment by crabsinger** [comment]
resolved by https://github.com/coordinape/coordinape/pull/1492
