### ISSUE TITLE
Add Claim Distributions to Mobile Layout

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1488]
**Summary:**

1. **What is actually happening:**
Users can't claim distributions on mobile because there's no button for it
2. **What should be happening:**
Users should be able to claim distributions via a claim button in the hamburger menu.
3. **Steps to recreate:**
Log in on mobile with funds available to claim.

**Comment by yahiamarzouk** [comment]
You can't even know how many gives you have on mobile except when the epoch ends

**Comment by yahiamarzouk** [comment]
@reeserj can I try with this one please?

**Comment by reeserj** [comment]
How's this one going @yahiamarzouk ?

**Comment by yahiamarzouk** [comment]
> How's this one going @yahiamarzouk ?

Working on it
