### ISSUE TITLE
Create new column on `users` to track source of invitation

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1490]
Goal:

We want to be able to know, track, and funnelize how a user enters a circle.

Solution: Create a new column on `users` named `entrance` to track how the user was added, either via:
- admin self-add: admin created circle
- magic link
- manual address entry
- CSV
- vouched in

Then wherever we add users to circles, we add the information.

**Comment by sshmm** [comment]
@crabsinger  does that include changing adding user actions to modify this value?

**Comment by crabsinger** [comment]
- Keep this as a string.
- Ignore adding this field for old users
- Do add this to all places for going forwards
