### ISSUE TITLE
Improve User profile picture upload pattern

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1496]
### What's happening:
Uploading images is a difficult user flow
### What should be happening
Uploading images should follow the add Org image process flow

1.  Button to upload new Image
![Image](https://user-images.githubusercontent.com/82838264/195173297-965a9ba0-dcf9-4fe5-8303-eae7bc7e9a62.png)
2. Auto-save Image after selected 
![Image](https://user-images.githubusercontent.com/82838264/195173477-3531e2f1-ec6e-42ce-8022-5b7c47faf2dc.png)
3. Error state
- If image too large return error : The maximum image size is 3mb, please try again with a smaller file.
4. While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."

**Comment by sshmm** [comment]
org logo max size is about 10MB. should I make the profile avatar 3MB?

**Comment by reeserj** [comment]
If it's 10 mb make it say 10 MB
________________________________
