### ISSUE TITLE
Improve Org Logo Update

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1498]
### What's happening:
Uploading images error messages are not helpful, and users have no indication their image is loading after selecting a photo
### What should be happening
1. Error state
- If image too large return error : The maximum image size is 3mb, please try again with a smaller file.
- If the wrong file type is selected give message: "jpg and png are the only accepted file types please select an acceptable file and try again"
2. While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."

**Comment by crabsinger** [comment]
@reeserj can you separate these into two separate tickets. Part 2 is resolved by #1500
