### ISSUE TITLE
Fix validation on Circle Create form

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1515]
**Summary:**

1. **What is actually happening:**
On the Circle Create https://app.coordinape.com/new-circle page, the zod validaiton doesn't always properly display on the form.

2. **What should be happening:**

The zod validation should always properly show any errors in the form, and properly enable/disable the "Create Circle" form depending on if errors are present.

3. **Steps to recreate:**

Go to circle create form, add valid data into all fields except "Email Address", click the "Create Circle" button, and you should see no visible error message, but a console zod error showing email address is required.

4. **Screenshots/GIF/Video recording**
<img width="1251" alt="Screen Shot 2022-10-17 at 10 02 26 AM" src="https://user-images.githubusercontent.com/83605543/196241006-41e90499-8ac9-4871-b723-8dc87b7bc6d2.png">

**Comment by sshmm** [comment]
@yahiamarzouk  is working on it on #1333

**Comment by yahiamarzouk** [comment]
@reeserj this issue should be closed
