### ISSUE TITLE
Hidden GIVE Setting

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1523]
Admin will be able to hide member give amounts during an active epoch. The map is not available to the user until post-epoch. If GIVE is hidden. GIVE is revealed after Epoch ends. This does not affect data such as epoch description, member notes, and GIVE amounts. This data will be stored and released after the Epoch ends.

**Comment by reeserj** [comment]
It seems the Map is still working here @sshmm I used the vercel link in #1674
