### ISSUE TITLE
Remove use of ui-avatars.com and AVATAR_PLACEHOLDER

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#1531]
See [domain.ts](https://github.com/coordinape/coordinape/blob/main/src/utils/domain.ts#L52:L54)

1. We have a placeholder image in the code that we should no longer use.
2. We have code that makes requests to ui-avatars.com to generate fallback images for avatars when there is no image set. This was a quick & handy solution at the time, but now we have [a better way to do it (in src/ui/Avatar)](https://github.com/coordinape/coordinape/blob/main/src/ui/Avatar/Avatar.tsx#L145) that doesn't depend upon an external server.

- Remove the placeholder.jpg image
- Remove `AVATAR_PLACEHOLDER`
- Remove `getInitialsUrl` 
- Remove `getAvatarPath` and rename `getAvatarPathWithoutPlaceholder` to `getAvatarPath`
- Remove `getCircleAvatar`
- Change all the code downstream so it still works
  - i.e.: Show an object's avatar image if it exists, or its initials according to [`getInitialFromName`](https://github.com/coordinape/coordinape/blob/main/src/utils/domain.ts#L101), using src/ui/Avatar.

**Comment by crabsinger** [comment]
@yahiamarzouk is interested in tackling this issue...
