### ISSUE TITLE
Allow admin to populate contribution text fields

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1566]
**Summary:**

1. **What is actually happening:**
In the changes to the allocation and contribution designs, the display of the admin text fields 
![image](https://user-images.githubusercontent.com/82838264/197822981-6a1499c4-976d-40a8-ba03-3bc5dc6f7627.png)
has disappeared. 
2. **What should be happening:**
![2022-10-20_15 39 49](https://user-images.githubusercontent.com/82838264/197828524-ec5e4fb6-78bc-4f9c-9812-c462cc9ff05f.gif)

- When the user is an admin add an **edit help text** button to the right hand side next to the text and allow the admin to make changes to the text field in the db
- Remove the box from the admin page where prompted to edit these fields

Figma Link- https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/Coordinape-App?node-id=24690%3A73693/

Needs to be done for #1565

**Comment by MooSeMoos** [comment]
hay can i work on this issues

**Comment by sshmm** [comment]
@reeserj  but the cutomization section fields are still used in the old give/allocation page. I think we should leave it until the old one is removed from the project

**Comment by ivyquinzel** [comment]
@sshmm The helper text should be showing in the old and new designs. Right now if you update the allocation & contribution helper text it doesn't reflect on the new pages.

**Comment by ivyquinzel** [comment]
@reeserj This ticket needs to be rewritten. Whats happens is when the admin goes to customize the text. It doesn't show on the new allocation/contribution pages. The in page "edit helper text" function is a new feature not yet in the app

**Comment by sshmm** [comment]
> @reeserj This ticket needs to be rewritten. Whats happens is when the admin goes to customize the text. It doesn't show on the new allocation/contribution pages. The in page "edit helper text" function is a new feature not yet in the app

I think this is what is @MooSeMoos  is working on right now for this issue. what I am saying is that we shouldn't remove the old one so that we can change the helper text for the old pages. so we leave both methods the admin settings for old pages and the edit helper text for new page

**Comment by MooSeMoos** [comment]
@reeserj  hey there!! I finished working on the contribution page part 
![image](https://user-images.githubusercontent.com/73297706/199804083-948e1f30-7e12-4162-886b-493b23ec0bcf.png)
![image](https://user-images.githubusercontent.com/73297706/199804254-0e60ca78-bb67-4fae-ae5b-9daa7c9bab4b.png)
should i delete the customization part?
![Screenshot from 2022-11-03 20-20-53](https://user-images.githubusercontent.com/73297706/199804707-8ea38732-85a1-471e-8514-656bf8d26610.png)

**Comment by reeserj** [comment]
Great work @MooSeMoos let's hold off on the deletion for now as we're still using in in the old allocation phase
