### ISSUE TITLE
Epoch Meta Data or Notes

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1572]
- People want to be able to write info about what the epoch is about.
- This would help add flavor to the epoch

In this design, we remove epoch naming such as epoch 1, epoch 2, etc., just allowing the date range to be the name. The user can now add a description to upcoming or current epochs. 

[UI](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/Coordinape-App?node-id=26295%3A76370)
[Prototype](https://www.figma.com/proto/L4oZwYVUdpgacZtwipGaYe/Coordinape-App?page-id=14369%3A30224&node-id=26295%3A75992&viewport=1239%2C18819%2C0.27&scaling=min-zoom&starting-point-node-id=14370%3A52369&show-proto-sidebar=1&hide-ui=1)

**Comment by sshmm** [comment]
@wingfeatherwave  @ivyquinzel  any suggestions what should be the min and max characters for epoch description>

**Comment by sshmm** [comment]
@1656 still under review
