### ISSUE TITLE
Entering Contributions Creating Duplicates

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1579]
**Summary:**

1. **What is actually happening:**
Occasionally when I create a contribution there will be a contribution created by the auto save before I'm finished typing.
2. **What should be happening:**
There should only be one contribution created when typing.
3. **Steps to recreate:**
Create a new Contribution, type , pause, type some more 

Seems to be more likely when you come to the page for the first time.

Tried to get a screen cap of it but wasn't able to. 
4. **Screenshots/GIF/Video recording**

**Comment by topocount** [comment]
I think the createContribution call needs to be "trapdoored." I think a second `createContribution` mutation runs while the first one is inflight, so we need a state variable to suspend saving while contribution creation is inflight.

**Comment by levity** [comment]
Maybe talk to Graffe about this pattern of “not only debounce, but make
sure there’s only ever one request pending”; he had to do it for
auto-saving allocations as well. Would be good to see in the code that the
same pattern is in use, maybe make it more legible/reusable

**Comment by ashmbanks** [comment]
I'm seeing this a lot; like every 3rd contribution I start.

**Comment by reeserj** [comment]
@topocount did this get resolved?

**Comment by crabsinger** [comment]
@reeserj can you try and see if you can reproduce this, and close if you cant.

**Comment by reeserj** [comment]
Couldn't replicate
