### ISSUE TITLE
Clicking on Wonder/Dework contributions are no longer linking to wonder/dework

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1580]
**Summary:**

1. **What is actually happening:**
Historically integration contributions would link out to Dework or Wonder when clicked. These aren't working at the moment
2. **What should be happening:**
Clicking on an integration contribution should take you to that issue.
3. **Steps to recreate:**
Click on an integration contribution that is on someone's card. (Reese in Circle 2 has one of each)
4. **Screenshots/GIF/Video recording**

**Comment by karelianpie** [comment]
@reeserj is this the correct screen recording?

**Comment by reeserj** [comment]
> @reeserj is this the correct screen recording?

No, the error was clicking on a wonder integration task and then not being redirected to the wonder app

**Comment by yahiamarzouk** [comment]
i've been testing this and it works as expected

**Comment by sshmm** [comment]
@reeserj  is not it better to add the link to the drawer? so clicking the link will open the drawer with the contribution information and a link to go to this contribution.
I made it to open the drawer based on figma

**Comment by yahiamarzouk** [comment]
> @reeserj  is not it better to add the link to the drawer? so clicking the link will open the drawer with the contribution information and a link to go to this contribution.
> 
> I made it to open the drawer based on figma

I was thinking about making it a button in the drawer and separate from the manual personal allocations that can be edited

**Comment by sshmm** [comment]
there is a similar example here https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/Coordinape-App?node-id=27338%3A84444&t=sw3tnZGNTqxWujnC-0
![image](https://user-images.githubusercontent.com/34943689/202749574-26845daa-e604-454d-a727-1a05af168e9c.png)
