### ISSUE TITLE
Introduction to Contributions Blue Onboarding Notification Pattern

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#1604]
The contributions feature needs explaining for new and existing users. Using our "notification" components, we can add explainer text with links to our docs. Example attached Below 

Deliverables
- Blue Intro to contributions 
- Preloaded "Example" Contributions 

![Image](https://user-images.githubusercontent.com/92177509/199131349-101c8e8c-eaa6-411a-95c7-79c6374ee51e.png)

**Comment by reeserj** [comment]
@CryptoGraffe have you had a chance to look at this one?
