### ISSUE TITLE
Members page caching bug

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1706]
Every time you allocate, the Members page is out of date. 

Our current model uses an old model of recoil data to fetch the allocations, which are often out of date.

Resolving this bug would involve updating these queries to not be out of date:

A few possible solution options:

A) Invalidate this data after allocating (but what about other users allocating?)
B) Refetch the data whenever you refocus the Members table, or whenever you look at it again.

**Summary:**

1. **What is actually happening:**
Members page allocation data is out of date

3. **What should be happening:**
It should be accurate.

5. **Steps to recreate:**
Go to members page. Change your allocations. Go back to members page and check allocations listed on Members page and they are old and inaccurate.

**Comment by sshmm** [comment]
> The map is vulnerable to this too

I opened this PR #1764 for members page.
I suggest doing map page in another Pr because it depends on different queries and more complicated
