### ISSUE TITLE
When a user is invited or nominated and they have an existing different username, notify about it

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1737]
**Problem**
Once we have moved to one username per profile (#1395), there can be a conflict with an admin providing a new username when inviting or nominating. We need to detect this on the backend and return information such that the inviter/nominator can discover that despite them inviting an address with a particular name, that profile/address already had a valid name.

**Comment by sshmm** [comment]
I did that for inviting users in #1735. I will do it for nominees after merging it
