### ISSUE TITLE
Update Default Contribution Text

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1755]
**Summary:**

1. **What is actually happening:**
Current default Contribution text is slightly confusing

Please update from 
![image](https://user-images.githubusercontent.com/82838264/206770834-e422abb4-d0f5-4289-b10a-77beceb7812e.png) to 

> Contributions are a great way to highlight the work you're doing. 
> 
> You can summarize your Contributions in the Epoch Statement when there's an active Epoch by clicking on your row.

2. **What should be happening:**
Default Contribution text should read: 

> **Contributions** are a great way to highlight the work you're doing. 
> 
> You can summarize your Contributions in the **Epoch Statement** when there's an active Epoch by clicking on your row.

3. **Steps to recreate:**
Go to the contributions tab and see the description text

**Comment by maddy020** [comment]
I am unable to set up this in my local machine
It  shows me this
 warning ..\..\package.json: No license field
$ ./scripts/serve.sh
Done in 7.75s.

**Comment by yahiamarzouk** [comment]
> can u please ask for help on our Discord channel - devs-all 
https://discord.com/channels/845400066532704256/898299792575299654

**Comment by MooSeMoos** [comment]
can i work on it

**Comment by sshmm** [comment]
@MooSeMoos  I assigned it to you
