### ISSUE TITLE
MagicLink ToolTip

### ISSUE THREAD

**Issue by ashmbanks** [coordinape/coordinape#1804]
Tooltip or some explanation that explains that Magic Link is creating a wallet for you.

Context: Help new-to-web3-users understand that by using email to login, they are actually going to have a wallet (created by MagicLink) and that they "ARE WEB3-ING!!"

Consider also adding a link to MagicLink Docs (especially if there's a "Start Here" for end users on MagicLink).

**Comment by levity** [comment]
@ashmbanks can you jog my memory? is this for the Email button on the initial modal?

**Comment by ashmbanks** [comment]
Yep, that's right, @levity

**Comment by levity** [comment]
Feels redundant with the interstitial in #1805 to me now... WDYT @Zemm111?

**Comment by ashmbanks** [comment]
@levity - What about when the app asks to sign something. Is that completely Magiclink modal? (And we can't add anything there)

**Comment by levity** [comment]
Yep, that’s right

**Comment by Zemm111** [comment]
I think we could move forward without a tooltip.  If the interstitial modal is the first thing a user sees when they click Email Login, they will get the relevant information and can back out at that point if they want to.
