### ISSUE TITLE
Info Modal when MagicLink user tries to use Vaults

### ISSUE THREAD

**Issue by ashmbanks** [coordinape/coordinape#1806]
- “You need to get a real wallet to use/manage vaults OR export your Magic Link wallet into Meta Mask”
    - ~Change login flow to update `profiles.connector` so that we can see that user is now using Metamask for an address that was originally created with Magic~ not needed, reading the value from the frontend auth store instead

**Comment by levity** [comment]
<img width="1552" alt="Screen Shot 2023-01-13 at 1 47 53 PM" src="https://user-images.githubusercontent.com/193667/212246632-3009591b-1eea-42ab-beb5-c94fd5c8c524.png">

**Comment by levity** [comment]
> <img alt="Screen Shot 2023-01-13 at 1 47 53 PM" width="1552" src="https://user-images.githubusercontent.com/193667/212246632-3009591b-1eea-42ab-beb5-c94fd5c8c524.png">

you can see that i'm using the HintBanner, with an alert background color. personally i'm not a fan of this layout but at least it's consistent with the rest of the site... @wingfeatherwave any suggestions?
