### ISSUE TITLE
Remove Material UI buttons/styles from profile page

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1813]
Make the profile page (and edit modal) work with new themes: http://localhost:3000/profile/me
- don't redesign, or change anything beyond the following:
- remove Material UI button (switch to normal buttons)
- remove makeStyles, and use default stitches styling patterns
- verify it works with theme switching.

**Comment by sshmm** [comment]
@crabsinger  should I remove makstyles from subcomponents? like ProfileSkills and FormFileUpload
