### ISSUE TITLE
Bug: Can't access CSV when not on Main net

### ISSUE THREAD

**Issue by ashmbanks** [coordinape/coordinape#1846]
Problem:
I can't access a distribution page when not connected to main net. 

![Image](https://user-images.githubusercontent.com/113928419/213829385-587cc001-c1a8-474d-8dac-8b795f09777a.png)

Proposed Solution:
Allow access to the Distribution page, but disable the Give Circle and Fixed Payment forms/actions.
This way, folks could still use the "Export CSV" action without being forced to switch to Main Net.

![Image](https://user-images.githubusercontent.com/113928419/213829504-d668f3be-76ab-4da5-b3da-c4a3093ae68c.png)

A nice to have would be a message in the forms that says 
"Gift Circle payments disabled on Chain ID: [chain.id]" & "Fixed Payments are disabled on Chain ID: [chain.id]"

**Comment by crabsinger** [comment]
I thought this worked for a bit - but I saw the distro page failing to load, so I just fixed the failed to load case with the "Require mainnet error" as a short term fix.

@sshmm can probably fix this?
