### ISSUE TITLE
Make updateEpoch timing `params` optional

### ISSUE THREAD

**Issue by topocount** [coordinape/coordinape#1899]
The `updateEpoch` endpoint has never had nice gql-like ergonomics where parameters that don't need to be updated can be omitted.

Currently, the `params` object contains all timing-related inputs and is mandatory and the current flow involves including the existing inputs, even if they aren't changing. It'd be possible to drop this requirement, and bypass the required validations to update things like the `description`.

**Comment by crabsinger** [comment]
No longer needed.
