### ISSUE TITLE
Changing Org Logo doesn't update side nave until you refresh

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1915]
**Summary:**

1. **What is actually happening:**
When Changing Org Logo the side nave doesn't update until the page is refreshed
2. **What should be happening:**
The side nave should update the org logo automatically after the image is saved. 
3. **Steps to recreate:**
Try to change the Org logo
4. **Screenshots/GIF/Video recording**
![Bug Change Org Image ](https://user-images.githubusercontent.com/82838264/216771774-269e2608-f2e2-4223-b948-bd48991b1929.gif)

**Comment by yahiamarzouk** [comment]
hey Reese, i've been trying to recreate this bug but it always auto save

**Comment by reeserj** [comment]
It's OK for it to auto save, I think the logo on the side bar should update as soon as the logo is saved
________________________________
