### ISSUE TITLE
Profile Name Rollout Part 1

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#1927]
This task is to run a data migration to set `profile.name` for users who have not logged in recently and completed the modal.

- if user has only one name across our, copy it to profiles.
- otherwise: copy address to profile name using 0x${first2}…{last4} , example `0x75...FC34`

## if user has only one name across our, copy it to profiles.

This query fetches all users with exactly one name in users table across our system
```sql
SELECT u.*
FROM users u
JOIN profiles p ON u.address = p.address
WHERE p.name IS NULL
GROUP BY u.id
HAVING COUNT(DISTINCT u.name) = 1
```

So to update all these users:

```SQL
UPDATE profiles p
SET name = u.name
FROM users u
WHERE p.address = u.address
  AND p.name IS NULL
  AND (
    SELECT COUNT(DISTINCT name)
    FROM users u2
    WHERE u2.address = u.address
  ) = 1;
```

## otherwise: copy address to profile name using 0x${first2}…{last4} , example 0x75...FC34

After the previous update, if the user does not have a profile name, then just use their abbreviated address. This could be done with something like:

```
UPDATE profiles
SET name = '0x' || substring(address FROM 1 FOR 2) || '...' || substring(address FROM -4 FOR 4)
WHERE name IS NULL;
```
> This query uses the string concatenation operator || to concatenate the string '0x...' with the result of the substring function, which extracts the last 4 characters of the address column.

Run this migration to ensure all users have a profile name.

Notes:

| criteria | result |
| --- | --- |
| users with profile NULL and one name across system [^1]| 10989 |
| users with NULL profile name, in one circle, one unique name [^2]| 4499 |

[^1]: This query gets users with profile NULL and one name across system: ```
SELECT COUNT(*) FROM (
SELECT u.*
FROM users u
JOIN profiles p ON u.address = p.address
WHERE p.name IS NULL
GROUP BY u.id
HAVING COUNT(DISTINCT u.name) = 1
  ) subsquery;
);```

[^2]: This query gets users with NULL profile name, in one circle, one unique name : ```
SELECT COUNT(*)
FROM (
  SELECT u.address
  FROM users u
  JOIN profiles p ON u.address = p.address
  JOIN circles c ON u.circle_id = c.id
  WHERE p.name IS NULL
  GROUP BY u.address, u.name
  HAVING COUNT(DISTINCT u.name) = 1 AND COUNT(c.id) = 1
) subquery;
);```

**Comment by crabsinger** [comment]
I haven't tested all this SQL... so it needs to be verified.

**Comment by ashmbanks** [comment]
@levity is going to handle this part of the process, @sshmm.

**Comment by levity** [comment]
all profiles have names now
