### ISSUE TITLE
Add Information Icons and Tooltips on Circle Settings/Epoch Settings pages

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#220]
# Description:

Add Information Icons and Tooltips on Circle Settings/Epoch Settings pages with additional clarifying text to help users better understand the options.

## Page Details

Circle Settings model - this page is accessible from https://app.coordinape.com/admin and then click "Edit Circle Settings". This will open a modal. On this modal make the following changes:

See Figma for design details: https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=1937%3A3440

Tooltip design here: https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=1519%3A2253

### Enable Vouching: 

Yes - Circle members can invite new people to the circle; they become new members if enough other members vouch for them
No - Only circle admins may add new members

See the Docs

### Default Opt In:

Yes - All new members are eligible to receive GIVE
No - New members need to log into Coordinape and opt in to receiving GIVE

See the Docs

### Team Selection Enabled:

Yes - Members select a team during allocation and make allocations only to that team
No - Members make allocations to anyone in the circle

### Only Givers Can Vouch:

Yes - Only members who are eligible to send GIVE can vouch for new members
No - Anyone in the circle can vouch for new members

See the Docs

(was DEV-289 in Linear)

**Comment by jsur** [comment]
This can be closed @crabsinger, @exrhizo merged the changes in https://github.com/coordinape/coordinape/pull/331.
