### ISSUE TITLE
Update the email login info interstitial modal to help web2 users

### ISSUE THREAD

**Issue by ashmbanks** [coordinape/coordinape#2336]
Update this modal: 

![Image](https://github.com/coordinape/coordinape/assets/113928419/526fc106-1419-464d-ae2c-56e298d3de4c)

1. Add an image of the magic signature modal that opens in a new window. (so that web2 users will see what's coming and know what to expect and what to do)
2. Update the text of the modal to this: 

## How Email Login Works

Because this is a Web3 application, it relies on an Ethereum (or EVM) wallet. When you log in with email, we will create a wallet for you, using a service called [magic.link](https://magic.link/). With this wallet, you can receive tokens from Coordinape CoVaults, and interact with the blockchain.

## How to Login

After entering your email address or choosing to use a Google account, you will see a "Signature Request". Please click "Sign", and this should open a new browser window with the Magic.link signature request, which looks like this:

<img width="445" alt="Screenshot 2023-09-27 at 4 19 30 PM" src="https://github.com/coordinape/coordinape/assets/113928419/451022af-1b76-4715-9c68-5490d7bb669c">

Click "Sign" to authorize your login. The window will close and you will now be logged in!

For more information on wallets, web3, and best practices, please read [here](https://docs.coordinape.com/info/documentation/email-login-and-web3-best-practices).

**Comment by crabsinger** [comment]
Here's a link to the S3 upload of the magic link example: https://coordinape-prod.s3.amazonaws.com/assets/static/images/magic-link-example.png @sshmm
