### ISSUE TITLE
Improve usability on mobile

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#245]
More details to come

Notes from @AlexDistill:
> Low hanging fruit to fix in mobile design:
> 
> General task is to reflow content going from a 12 column grid, down to 4 or 3 columns on mobile (Alex to detail grid specs in design documentation)
> 
> - mobile menu for both regular users and admins (subnav could be inside mobile menu or moved to tabs)
> - Turn admin edit/add modals into overlays,
> - Profile - including profile editing
> - Tables - most likely table rows turn into cards and tables are stacks of cards

**Comment by almithani** [comment]
I started on the mobile header but didn't get a chance to complete it just yet: https://github.com/almithani/coordinape/tree/fix_responsive_header

**Comment by exrhizo** [comment]
Of all these things, the most egregious from my POV is,
![image](https://user-images.githubusercontent.com/4206097/140257078-0b1a7b26-6d9b-4e23-bb12-e204607b246c.png)

I agree on "RECO: create hamburger menu to replace top menu"

**Comment by almithani** [comment]
This PR takes care of two of the issues: https://github.com/coordinape/coordinape/pull/257

- Mobile menu styling is fixed, burger menu exists, but without the burger menu icon.
- epoch table styling is fixed so we don't get the overlaps that @exrhizo shows up  there

**Comment by exrhizo** [comment]
I merged @almithani 's code in a new PR and I am currently rewriting the suspense related stuff in the header, so I'd hold off starting people on this

**Comment by reeserj** [comment]
@spydermonkee This is complete
![image](https://user-images.githubusercontent.com/82838264/150000473-c585a338-7456-4af1-8976-2b9d30aff100.png)
![image](https://user-images.githubusercontent.com/82838264/150000490-aafce09d-b45a-474b-bb83-4c5e1cdb9775.png)


Still a lot of work to be done on Mobile but this issue is done

**Comment by reeserj** [comment]
Closed
