### ISSUE TITLE
Request: API Feature Specifications

### ISSUE THREAD

**Issue by kushagra27** [coordinape/coordinape#246]
# API Endpoints Request

## Description

Here are a few suggested endpoints and parameters for the coordinape API that I could think of which could serve a common use case. Most of them are to aimed to make features from the app dashboard usable through API. 
> Note: I will update this as per suggestions and requirements.

1. Circle creation endpoint (Endpoints taken from current coordinape form for circle creation) – **To be used by circle Admin (needs verification by eth address)**

    Function – To create a circle using API

    ``` 
    # Sample Input Parameters
    {
        publicAddress: "0x8aFDb350650E659c3d8cB892afBB989b785a172d",
        circleName: "Sample Circle",
        organizationName: "Sample Organization",
        usernameOfCreator: "kushagra",
        creatorSocialHandle: "twitter.com/kushagra\_agr",
        usecase: "Sample Use case"
        distribution: "100"
    }
    ```

    |**Parameters**|**Expected data**|
    | :- | :- |
    |ETH Address of creator|ETH Public address (String)|||
    |Circle Name|Name (String)|||
    |Organization Name|Organization Name (String)|||
    |Username of Creator|Name (String)|||
    |Creator social handle|Social Link (String)|||
    |Use case|Description (String)|||
    |How much will you distribute (approx)|Number(Float)|||

    **Response** – circle id and metadata.

    ``` 
    {
        circleId: "hjabvcjvwyfcabkja",
        createdBy: "0x8aFDb350650E659c3d8cB892afBB989b785a172d",
        circleName: "Sample Circle",
        organizationName: "Sample Organization",

    }
    ```

2. Add contributor to a circle – **To be used by circle Admin**

    Function - to add contributors to circle, single or in bulk.

    Parameters will be passed in an array of Objects

    ``` 
    #Sample Data to be passed
    [ 
        {
            name: 'John Doe',
            address: '0x8aFDb350650E659c3d8cB892afBB989b785a172d',
            admin: true,
            canGive: true,
            forcedOut: false,
            optedOut: true,
            startingTokens: 100.00
        },
        {
            name: 'John Doe',
            address: '0x8aFDb350650E659c3d8cB892afBB989b785a172d',
            admin: true,
            canGive: true,
            forcedOut: false,
            optedOut: true,
            startingTokens: 100.00
        },
        {...},
    ]
    ```

    |**Parameters**|**Expected Data**|**Additional**|
    | :- | :- | :- |
    |Contributor Name|Name(String)|||
    |Contributor ETH Address|Address (String)|||
    |Admin|Yes/No(Boolean)|Default No||
    |Can give to others|Yes /No(Boolean)|Default Yes||
    |Forced Opt Out|Yes/No(Boolean)|Default No||
    |Opted Out|Yes/No(Boolean)|Default Yes||
    |Starting Tokens|Number (Float)|||

    **Response** – Returns a batch summary and individual status of successful and failed additions

    ``` 
    # Sample Response Data

    {
        summary: {
            circleID: "ajnbfibhqvbckabjkcbds",
            circleName: "Sample Circle",
            contributors: "100",
            success: "98",
            failed: "2"
        },
        success: [
            {
                name: 'John Doe',
                address: '0x8aFDb350650E659c3d8cB892afBB989b785a172d',
                admin: true,
                canGive: true,
                forcedOut: false,
                optedOut: true,
                startingTokens: 100.00
            },
            {...}
        ],
        failure: [
            {
                name: 'John Doe',
                address: '0x52e87A0f75782eF0e77C87C4E2F290296Fa5d2Ff',
                admin: true,
                canGive: true,
                forcedOut: false,
                optedOut: true,
                startingTokens: 100.00
            },
            {...}
        ]
    }
    ```

3. Add Epoch to circle – **To be used by circle Admins**

    ``` 
    # Sample data

    {
        startDate: "24/10/2021"
        epochLength: "2"
        startTime : "00:00"
        repeats: true
        repeatFrequency: "weekly"
    }
    ```

    |**Parameters**|**Expected Data**|
    | :- | :- |
    |startDate|Date (string in DD/MM/YYYY)||
    |epochLength|Number (days int)||
    |startTime (UTC)|time (HH:MM UTC in 24 hour format)||
    |Repeats|Yes/ no (boolean)||
    |repeatFrequency|Weekly/monthly (String)||

    **Response** –

    Status added / not Added and epoch id.

4. Fetch epoch details

    |**Parameters**|**Expected Data**|
    | :- | :- |
    |epochID|Id(string)||

    **Response** –

    |**Parameters**|**Expected Data**|
    | :- | :- |
    |epochStartDate|Date (string in DD/MM/YYYY)||
    |epochStartTime|Time (HH:MM UTC in 24 hour format)||
    |duration|Number (days int)||

5. Fetch circle details

    |**Parameters**|**Expected Data**|
    | :- | :- |
    |circleID|Id(string)||

    Response – Circle admins list, members list, epochs list, GIVE allocated and received by every member, embeddable allocation map link

6. Fetch Team mates -

    |**Parameters**|**Expected Data**|
    | :- | :- |
    |circleId|Id(string)||

    Response – Circle member list, user’s team mates

7. Configure Epoch - for team members

    |**Parameters**|**Expected Data**||
    | :- | :- | :- |
    |epochID|Id(string)||
    |addTeammate|List of teammate ids(array)||
    |removeTeammate|List of teammate ids (array)||
    |allocate|<p>List of allocations(key value pairs)   \<id>:\<allocation>||
    |Opt in|True / false|Changes the user preference to opt in or out of epoch|

## Notes
Maybe club APIs related to user profile and create a profile handler to fetch all user specific data and make alterations, like opting in or out of allocations in an epoch.

**Comment by reeserj** [comment]
@kushagra27 please see our beta API at app.coordinape.com/developers
