### ISSUE TITLE
Active Epoch Count Inaccurate

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#253]
![image](https://user-images.githubusercontent.com/82838264/139495854-b81a8542-be2e-4458-bbec-436ec701e418.png)

When there is an active epoch the number to the right is the same as the last completed epoch which also throws off the next epoch number.

Issue reported by Egor
https://discord.com/channels/845400066532704256/854757515899699200/903736258730274877

**Comment by exrhizo** [comment]
The server doesn't give an epoch a number until it has begun, so the front end sorts them and then extrapolates the numbers - this is a bug in that process

**Comment by reeserj** [comment]
Expected outcome is that the epoch numbers would never display a duplicate number. So the current Epoch should be last complete epoch +1 and then +1 for each epoch after that.

**Comment by exrhizo** [comment]
Open question if is this still occurring - I didn't think it got fixed...

**Comment by jsur** [comment]
@reeserj is this still a thing? I tried one case, that seems to work:

<img width="1180" alt="Screenshot 2021-12-13 at 8 51 25" src="https://user-images.githubusercontent.com/1258424/145765689-6d0c8e3a-06ac-4a3f-af0c-def7d4b6316d.png">

**Comment by reeserj** [comment]
Looks to be working I'll close it
