### ISSUE TITLE
New Epochs reverting users to opt-out despite Circle Settings

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#256]
User's reporting their circle members are all opted out at the end of an epoch.

(Evidenced in our Circle 2 as well) 

https://discord.com/channels/845400066532704256/852628536530829352/904731551357628497

**Comment by levity** [comment]
@zashton can you take a look at this?

**Comment by zashton** [comment]
this is actually a feature requested by our team, automatically opt out users that didn't allocate the previous epoch.
remove it ?
@levity

**Comment by levity** [comment]
@msutherl @AlexDistill what do you think?

**Comment by osaat-eth** [comment]
@zashton , now I understand:
> automatically opt out users that didn't allocate the previous epoch
As we decided to allocate on a bi-weekly basis, our epoch duration is set to 1 week and we only allocate every other week.

This option does make sense, but should be explained transparently somewhere (with an opt-out possibility? :) ).

**Comment by msutherl** [comment]
@AlexDistill this might be a good issue for us to dig into together to help me get some more exposure to how we do things tactically

**Comment by AlexDistill** [comment]
yes this seems like a small thing we can tackle quickly

**Comment by exrhizo** [comment]
@crabsinger I believe this is closed
