### ISSUE TITLE
Add Circle Settings toggle for "Opt Out" due to inactivity feature

### ISSUE THREAD

**Issue by Zemm111** [coordinape/coordinape#260]
**Current Behavior Is:** When a contributor is inactive for an epoch (does not log in to send GIVE), they are automatically opted out on the next epoch.

**Desired Behavior Is:** A toggle in Circle Settings that allows Admins to turn this feature ON or OFF for their circle, using our current switch components.  Label can be: "Opt Out Contributors after One Epoch of Inactivity"

**Comment by zashton** [comment]
https://github.com/coordinape/coordinape-backend/pull/66
