### ISSUE TITLE
Percentage Based Vouching Thresholds

### ISSUE THREAD

**Issue by Zemm111** [coordinape/coordinape#268]
**Current Behavior Is:**  Admins can set a whole number integer for their vouching threshold.  For example, a threshold of 3 means that it takes 3 circle members to vouch in a new member, including the nominator.

**Desired Behavior Is:**  Admins can set a percentage of total circle population.  In this case, the number to Vouch will need to be calculated, rounded and displayed, as it will change as the circle grows or contracts.  For UI, admins will enter this in the Circle Settings, Vouching area.  They will be able to use either Percentage or Number, but not both.  A Tooltip explainer would also be nice to have.

**Comment by Caranell** [comment]
Hi, I'd like to help with this issue. @Zemm111 , do you expect interface to look like this?

<img width="302" alt="Screenshot" src="https://user-images.githubusercontent.com/9637757/141840216-e565ba68-8a5f-47e7-9a00-146bc703f2f6.png">

**Comment by Zemm111** [comment]
Awesome!  Let me send this to @crabsinger and @levity - looks good to me, but not sure the process for approving.  Thanks for your help on this!

**Comment by crabsinger** [comment]
Hi @Caranell - awesome that you're diving in and making some designs on this. I think something like what you mocked up would work - we should ask for input from @AlexDistill on the design.

This feature will require some backend work in the Laravel app and then frontend changes in this repo. Are you able/interested in trying to do both of those PRs?

A good first step is getting the backend and frontend repos running locally and then finding the vouching code flow.

**Comment by Caranell** [comment]
> Are you able/interested in trying to do both of those PRs?

Yea, I almost finished work both on frontend and backend, I'll create a PR soon

**Comment by crabsinger** [comment]
@Caranell awesome. I've assigned this issue to you so others won't jump in and do redundant work. In the future, just ask to claim it if you are going to work on it.

Let us know when you're ready for a code review or need any help!

**Comment by AlexDistill** [comment]
@Caranell I created a design for this, you can find it here:

https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/Coordinape-Design-v8?node-id=2136%3A21761

Tooltip content is in the frame directly below that.

@Zemm111 can we prepare a docs update for this? The tooltip content I spec'd is assuming it will be noted somewhere in the docs.

**Comment by Caranell** [comment]
Thanks for the design, it's pretty similar to the one I've done, still yours looks better 👍 
<img width="301" alt="Screenshot 2021-11-24 в 00 44 17" src="https://user-images.githubusercontent.com/9637757/143134221-6e1a2e1c-4f34-42c2-a503-e397b1c6b200.png">

**Comment by Zemm111** [comment]
@Caranell Wondering if this is ready for review to merge?  Thanks for your work on it!

**Comment by spydermonkee** [comment]
Hi @Caranell - Do you still have this code on a branch? Would you mind submitting it for PR?

**Comment by levity** [comment]
@reeserj if we have a community dev work on this now, they should just build it to fit with the 1.0 designs, and we would update the look & feel later on

**Comment by karelianpie** [comment]
Is anyone working on this? Otherwise I think I can pick it up @reeserj

**Comment by karelianpie** [comment]
> This one is lower priority than some other work—I’ll let @reeserj point you to them when he’s around

Sounds good, I was browsing through the issues and they mostly seem to depend on other work being done, let me know @reeserj what would be a good next issue for me. Thank you!

**Comment by crabsinger** [comment]
low priority for now -closing
