### ISSUE TITLE
Batch Upload Contributors by CSV

### ISSUE THREAD

**Issue by Zemm111** [coordinape/coordinape#269]
**Current Behavior:** Admins can only enter new contributors manually via the Admin Page.

**Desired Behavior:** Admins can download a Template CSV, which contains any contributors and settings available in the circle. They can make changes and upload it again with new contributors populated or other changes.  This should not effect any current GIVE totals, etc.

**Comment by reeserj** [comment]
This is part of the 1.5 design right @AlexDistill ?

**Comment by crabsinger** [comment]
Currently under work by @CryptoGraffe - can you tag this issue when your put up your PR so this gets resolved.
