### ISSUE TITLE
Profile Picture not saving

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#273]
After uploading a new profile picture and clicking save nothing happens. 

![image](https://user-images.githubusercontent.com/82838264/140861159-4b97e20e-0cf2-4a4c-ae36-3c765392f97d.png)

![image](https://user-images.githubusercontent.com/82838264/140861179-9f66494a-17c5-415c-b41f-eec836b39f3b.png)

There are no error messages to view

**Comment by zashton** [comment]
added fix here 
https://github.com/coordinape/coordinape-backend/pull/60

**Comment by crabsinger** [comment]
Seems to be fixed.
