### ISSUE TITLE
Long tags break UI

### ISSUE THREAD

**Issue by crisgarner** [coordinape/coordinape#277]
There is an UI issue, if you have long tags, even if you only have 3 lines the text is hidden. A fix could be to remove the last part of the text and add "... see more" and show a pop up with the rest of the text

![Screenshot_from_2021-10-27_08-54-46](https://user-images.githubusercontent.com/578688/140963674-904cb5b3-5786-4077-8b6f-68098a32d313.png)

**Comment by crabsinger** [comment]
@AlexDistill i like the proposed solution:
> A fix could be to remove the last part of the text and add "... see more"

any thoughts on this UX?

**Comment by exrhizo** [comment]
I updated the card last, there is a bug at least where I think more text could fit even before doing that with ...

**Comment by f1lander** [comment]
@exrhizo I can take a look, wen can just overflow y that section

**Comment by crabsinger** [comment]
Assigning to you @f1lander

**Comment by crabsinger** [comment]
@f1lander you still working on this?

**Comment by f1lander** [comment]
@crabsinger PR was already merge https://github.com/coordinape/coordinape/pull/297
