### ISSUE TITLE
ENS Name Resolution

### ISSUE THREAD

**Issue by exrhizo** [coordinape/coordinape#279]
## Improve `zEthAddress` in `formHelpers.ts`

The simplest way to do this is to have the Zod parser use asynParse and get the address for an ens if it is ens or if it is a regular address validate that. If the ens resolution fails, then that should fail the validation.

See: https://github.com/colinhacks/zod#parseasync

For this to work, I think that `createForm` will need to use `useRecoilValueLoadable` otherwise it will cause the form to suspend.

---

### Alternatively 
(This way has the drawback that validation would still need to be spread between this and the above zod parser)

Create an `FormEnsField` that wraps `ApeTextField` with the same interface as `FormTextField` and intercepts onChange and resolves ens names to an address.

The field needs to recognize the difference between an ENS name and address, and only resolve for the ens, it can display an indication if the ens name doesn't resolve.

**Comment by zencephalon** [comment]
@exrhizo I'm interested in working on this, have used Zod quite a bit in some previous work.

**Comment by crabsinger** [comment]
@zencephalon great - I'll assign to you to take this on!
