### ISSUE TITLE
Missing placeholder links on social media fields when editing profile

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#294]
when linked a medium profile to coordinape the autolink is medium.com/username when the link medium gives me for my profile is username.medium.com

From Oops https://discord.com/channels/845400066532704256/854757515899699200/909676881161359422

EG of when you copy and paste a the URL into the medium link 
![image](https://user-images.githubusercontent.com/82838264/141778439-5b9d789d-7680-4115-8b38-6c157409a59f.png)

We used to have the prompts (EG @username) in the fields when they were empty but now it's gone

Please add the prompts back to each field so users know how to link their profiles on the other sides

**Comment by levity** [comment]
@f1lander can you take a look at this one? it looks like the placeholders were accidentally removed in a refactoring a few weeks ago ([this is where they used to be](https://github.com/coordinape/coordinape/blob/ef5b3505eb19f1fc55eb4c331a0bd784ec1fd35b/src/pages/ProfilePage/EditModal.tsx#L396))

**Comment by f1lander** [comment]
> @f1lander can you take a look at this one? it looks like the placeholders were accidentally removed in a refactoring a few weeks ago ([this is where they used to be](https://github.com/coordinape/coordinape/blob/ef5b3505eb19f1fc55eb4c331a0bd784ec1fd35b/src/pages/ProfilePage/EditModal.tsx#L396))

Sure I can do it

**Comment by levity** [comment]
https://github.com/coordinape/coordinape/pull/295
