### ISSUE TITLE
UI loop or inadequate error signaling

### ISSUE THREAD

**Issue by parseb** [coordinape/coordinape#301]
I was trying to reproduce #287 on the live website and I hit a [loop](https://user-images.githubusercontent.com/5999852/141973367-98fe1a4d-4d76-4a56-bc01-2aef19c728a3.gif).  
Will try to reproduce it locally. 
Likely lack of proper error signaling.

![coordinape-2021-11-16_12 55 25](https://user-images.githubusercontent.com/5999852/141973367-98fe1a4d-4d76-4a56-bc01-2aef19c728a3.gif)

**Comment by levity** [comment]
@f1lander please take a look at this one; i think it may be a regression from my changes to https://github.com/coordinape/coordinape/blob/master/src/routes/routes.tsx

**Comment by exrhizo** [comment]
I think this is fixed with the big refactor
