### ISSUE TITLE
UI updates to Profile Cards

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#305]
Remove the scrollable-y from appearing in the Profile card, add a popover text when clicking on `see more` and update the placeholder text

https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/Coordinape-Design-v8?node-id=2136%3A16522

**Comment by AlexDistill** [comment]
Intended behavior for this is...

User hovers over "See More" text goes to 100% opacity and tooltip pops up with full text. When user moves off the text the tooltip goes away
