### ISSUE TITLE
Omit "No Epoch Statement Made" from User Profile

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#307]
![image](https://user-images.githubusercontent.com/82838264/142511766-5f39ea66-9f3d-4c76-a739-c134ce338f8d.png)
On the Profile for recent Epoch activity please omit the "No Epoch Statement Made" so that it just shows recent epochs. 

If there is an epoch statement please keep it displayed.

**Comment by zencephalon** [comment]
I can take this on! If someone else wants to though, by all means.

**Comment by reeserj** [comment]
Go for it!

Thanks,

Regan
________________________________

**Comment by crabsinger** [comment]
@zencephalon assigning to you. 🙏
