### ISSUE TITLE
Extend “initials fallback avatar image” functionality to circles as well as users

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#308]
![image](https://user-images.githubusercontent.com/82838264/142512625-d8274699-b8b6-499e-92af-f2bb136ec1d8.png)

Where Circles are displayed please use the same Logic being used for New Users Profile Pictures on the Circle Profile Pictures.

**Comment by zencephalon** [comment]
I'll take this unless anyone else wants to!

**Comment by reeserj** [comment]
Go for it!

Thanks,

Regan
________________________________

**Comment by crabsinger** [comment]
@zencephalon bumping this - you still on it?

**Comment by zencephalon** [comment]
Yes, will get this done, but probably not until next week. Happy to let someone else pick it up too, it’s a good first issue.

**Comment by zencephalon** [comment]
I've decided to release this to the wild so that more people can get exposure to this part of the codebase. It didn't feel like I'd learn much new information about the code by doing this, so ROI doesn't seem worth it for me.

**Comment by jsur** [comment]
I can take a look at this.

**Comment by jsur** [comment]
Just to confirm @reeserj, is this what we're after here?

<img width="604" alt="Screenshot 2021-12-04 at 11 17 48" src="https://user-images.githubusercontent.com/1258424/144704363-fc505c22-7f34-4e4b-a26d-92df3e21a370.png">

**Comment by levity** [comment]
That’s right!

**Comment by jsur** [comment]
Ok great. Are there other pages where `<Avatar />` or `<ApeAvatar />` are used for showing circles? I didn't find any with a quick ctrl+f but I might be missing something.

**Comment by levity** [comment]
> Ok great. Are there other pages where `<Avatar />` or `<ApeAvatar />` are used for showing circles? I didn't find any with a quick ctrl+shift+f but I might be missing something.

Off the top of my head I don't know of any.

**Comment by jsur** [comment]
This was merged in https://github.com/coordinape/coordinape/pull/340.

**Comment by jsur** [comment]
@reeserj this can be closed.

**Comment by reeserj** [comment]
Thanks!
