### ISSUE TITLE
App doesn't update correctly after certain actions

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#313]
**Action:**
Create new Circle
**Expected Outcome:**
New Circle is immediately available
**Actual Outcome:**
Page needs refreshed before the circle is visible

**Action:**
Change Circles when in vouching, map, or allocations screen
**Expected Outcome:**
New Circles data is immediately available
**Actual Outcome:**
Page needs refreshed before the correct data circle is visible

**Comment by jsur** [comment]
I can take a look at this, could you assign this to me?

**Comment by jsur** [comment]
A question about the first action: Where should the new circle be visible? When I create a new circle in path `/new-circle`, the app redirects to `/admin?new-circle` and the new circle is shown like this:

<img width="1227" alt="Screenshot 2021-12-11 at 14 08 33" src="https://user-images.githubusercontent.com/1258424/145676058-5ff514ce-083b-4ab0-972b-ce7957abc584.png">

**Comment by reeserj** [comment]
I think we had a bug that that was preventing the app from refreshing after the circle was created. 

It seems to have been fixed
