### ISSUE TITLE
Setup CI/CD for Hasura

### ISSUE THREAD

**Issue by META-DREAMER** [coordinape/coordinape#321]
[Relevant Docs](https://hasura.io/docs/latest/graphql/cloud/projects/github-integration.html#github-integration)

**Comment by META-DREAMER** [comment]
Done in #421

**Comment by levity** [comment]
Hey @META-DREAMER, "CI" to me suggests the ability to write automated tests using Hasura. Should we keep this task open until that's done or open another one?

**Comment by META-DREAMER** [comment]
I think that should be a separate issue,  will be more about configuring regression tests etc. This is moreso just doing the groundwork for getting GitHub deploys working etc for the dev lifecycle. 

Testing our code as a whole is a much larger thing we will need to tackle, we don't really have tests at all.
