### ISSUE TITLE
Warning on Opt-Out button

### ISSUE THREAD

**Issue by Zemm111** [coordinape/coordinape#325]
**Problem**
Coordinape users sometimes click "opt out" in an exploratory manner, not realizing they will lose any GIVE they have accrued if an epoch is active and they have GIVE.

**Solution**
If an epoch is active and the contributor has GIVE, pop up a warning message that the user can click through if they are sure they want to opt out.

**Specification**
Front End change to the Opt-Out toggle on the Epoch Settings page: 

IF the logged in user has GIVE during an active epoch, and the attempt to Opt-Out, display a pop up notification with following copy:

- "If you Opt-Out you will lose your _____ GIVE"
- "Opting out during an in-progress epoch will result in any GIVE you have received being returned to senders.  Are you sure you wish to proceed?  This cannot be undone."

Buttons displayed: 
- "Proceed to Opt-Out" : Opts out the user and closes the window 
- "Cancel" : Closes the window and leaves the user opted in.

Link to Figma: 
https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/Coordinape-Design-v8?node-id=2519%3A4149

**Stakeholders**
@AlexDistill

**Comment by levity** [comment]
For an example of what the modal looks like, check out the pop-up that appears when you try to delete a user from the admin UI.

**Comment by jsur** [comment]
@Zemm111 is this what you're looking for? 

<img width="612" alt="Screenshot 2021-12-13 at 9 04 45" src="https://user-images.githubusercontent.com/1258424/145767203-8c80d68d-1f86-4296-a1e5-d86d1b41fe3a.png">

We could also just use the default X for closing the dialog like this:

<img width="614" alt="Screenshot 2021-12-13 at 9 06 29" src="https://user-images.githubusercontent.com/1258424/145767373-8221ea6c-cc86-4843-abed-27acca16e506.png">

**Comment by jsur** [comment]
This one can be assigned to me @levity

**Comment by Zemm111** [comment]
Yes looks good,.  @jsur -- the X in the top corner is probably sufficient.  Thank you!

**Comment by jsur** [comment]
Here's the PR: https://github.com/coordinape/coordinape/pull/363

**Comment by levity** [comment]
🚢 'ed, nice work
