### ISSUE TITLE
Mobile navigation - Add Admin View & Circles below main nav?

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#334]
The mobile menu is missing the circle selector option.
![image](https://user-images.githubusercontent.com/82838264/144430031-0c4f3015-6bc5-409b-b5c2-d19d791e3449.png)

Full size menu for reference
![image](https://user-images.githubusercontent.com/82838264/144430124-6cbe12b6-9ccd-4b4f-9eae-84884d108c5b.png)

Also the Red line in the middle of the header when you're in the circle selector in the mobile UI needs to be cleared

Please move "Allocation, Map, and Vouching" buttons above the circle selection in the order of the mobile menu

**Comment by exrhizo** [comment]
Needs design feedback about if we want to move the main nav above circle selection. Original design was for a dropdown to appear. I'd saw we move the circle selection and then later change the selector as we look at a org level version of the site.

**Comment by spydermonkee** [comment]
Hi @f1lander :) 
Is this one in progress? Or is it needing some design review or something?

**Comment by f1lander** [comment]
It is done @spydermonkee
