### ISSUE TITLE
Use v2 CSV Export endpoint

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#335]
The v2 CSV endpoint needs to be in `api.ts` instead of a regular link. That way it can use the auth credentials.

![image](https://user-images.githubusercontent.com/4206097/144521642-c8d90db9-6193-400e-ab6d-134312006f8b.png)

**Comment by exrhizo** [comment]
In the backend repo, it's this endpoint:
```Route::get('/csv', [DataController::class, 'generateCsv']);```

So the route is:
`/v2/${circleId}/csv`

**Comment by CryptoGraffe** [comment]
I'll be investigating/fixing this tomorrow (12/3)

**Comment by crabsinger** [comment]
@CryptoGraffe awesome, I've assigned this issue to you.

**Comment by CryptoGraffe** [comment]
Got this implemented and working, will put in PR in the morning.

**Comment by CryptoGraffe** [comment]
@exrhizo I don't understand PHP very well, but I'm not sure this route goes through the user verification middleware? 

This route appears to: https://github.com/coordinape/coordinape-backend/blob/2a0294ebee5c357a10fdcd2a22fe743847a4b3a4/routes/api.php#L60

But not this one, which has a "tmp fix" comment above it: 

https://github.com/coordinape/coordinape-backend/blob/2a0294ebee5c357a10fdcd2a22fe743847a4b3a4/routes/api.php#L91

**Comment by CryptoGraffe** [comment]
PR is in #341
