### ISSUE TITLE
[UI] Spike for stitches.dev getting the knowhow

### ISSUE THREAD

**Issue by f1lander** [coordinape/coordinape#355]
https://stitches.dev/docs/introduction

Before proceeding with more mobile components I'm digging with ChakraUI and stitches.dev, in matter to test the new ways to handle all upcoming components, goal here will be create the new buttons using both then to evaluate which is better and for opur purpose.

**Comment by spydermonkee** [comment]
Hi @f1lander :) 
Is this ticket still in progress?

**Comment by f1lander** [comment]
@spydermonkee sorry, it is not, let me close it.
