### ISSUE TITLE
Some emojis don't display on the history page

### ISSUE THREAD

**Issue by AlexDistill** [coordinape/coordinape#358]
I used emojis in a bunch of my notes, the emojis were pasted from the Keyboard viewer in OS x and were visible in the input fields. However, on the history page most of them show up as question marks 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2601663/145641866-80b17f95-6be7-432f-9f02-12b0b295b8cb.png">
a few emojis do display on the history page... like this sun 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/2601663/145641927-60dd543c-fbf2-43e8-927f-29ce5b320f70.png">

**Comment by CryptoGraffe** [comment]
This might be due to extended UTF-8 characters and how the database is setup... are the db configs in the repo somewhere?

**Comment by CryptoGraffe** [comment]
It could also be the sender and the viewer don't have the same unicode support, e.g. newer emoji available to the sender than viewer. Do you have an example emoji that we know is causing this @AlexDistill ?

**Comment by crabsinger** [comment]
@AlexDistill is this still happening for you? I tested this a bit more and seem to be able to send and receive notes with emojis. So not sure how to repro this bug... 

some screenshots of it working for me:


<img width="738" alt="Screen Shot 2022-03-24 at 10 05 42 AM" src="https://user-images.githubusercontent.com/83605543/159971494-daddedf6-7128-41cd-88eb-8c748568de66.png">
<img width="769" alt="Screen Shot 2022-03-24 at 10 05 39 AM" src="https://user-images.githubusercontent.com/83605543/159971498-90b28c7e-f3fb-493b-8984-a8343c56ce1b.png">
<img width="708" alt="Screen Shot 2022-03-24 at 10 05 26 AM" src="https://user-images.githubusercontent.com/83605543/159971499-3fc98b2a-911a-4baf-a22a-bfca504d580d.png">
<img width="699" alt="Screen Shot 2022-03-24 at 10 05 22 AM" src="https://user-images.githubusercontent.com/83605543/159971502-1ac51662-e1c7-4ea1-a800-edf60b619366.png">

**Comment by AlexDistill** [comment]
This one seems to be working fine for me as well now.
