### ISSUE TITLE
Support Sign-In with Ethereum [EIP-4361] On Coordinape 

### ISSUE THREAD

**Issue by obstropolos** [coordinape/coordinape#375]
What:

Update Coordinape's signature method to implement EIP-4361. Currently, we sign messages with this format: https://github.com/coordinape/coordinape/blob/f4743c2bd6866275b177c41ae25741378a37ea51/src/services/api.ts#L40

Changing the data payload to match EIP-4361 should be an easy change that helps us meet the standard.

**Problem**
Coordinape currently uses a custom way to sign users connecting their wallet into the platform, containing a login message and what appears to be a nonce. 

**Solution**
We would love if Coordinape would adopt [EIP-4361](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4361.md), or the new Sign-In with Ethereum standard to establish a session with users. The standardization of SIWE was supported by the Ethereum Foundation and ENS, and put together over a number of weeks in the open with community calls, feedback and participation being critical to the process. All of this is included on [login.xyz](login.xyz) which was used to host core information. 

Sign-In with Ethereum's goal in Web3 is to improve interoperability across existing services, while also providing wallet vendors a reliable method to identify signing requests as Sign-In with Ethereum requests for improved UX.

**Specification**
There are libraries being built to ease any adoption or integration concerns, namely for dapps: 
- Our initial TypeScript library which can be found [here](https://github.com/spruceid/siwe)
- In-progress [Ruby](https://github.com/spruceid/siwe-ruby) and [Rust](https://github.com/spruceid/siwe-rs) implementations

**Additional Notes** 
If Coordinape is open to adopting, we'd also love to add the logo to the list of supporters on login.xyz.

**Comment by EsteFilipe** [comment]
Interested in this task - authentication using Ethereum is currently my main area of interest.

Can I get it assigned to me?

**Comment by zashton** [comment]
> Interested in this task - authentication using Ethereum is currently my main area of interest.
> 
> Can I get it assigned to me?

Sure go ahead !

**Comment by awoie** [comment]
We have worked on a PR but it is WIP. The WIP PR should be there today @EsteFilipe @zashton . It would be awesome if you could get it across the finish line.

**Comment by awoie** [comment]
Current state of ^^ is sign in works, but we didn't have time to verify that post sign functionality is intact.

**Comment by EsteFilipe** [comment]
Awesome, will start working on this tomorrow

**Comment by awoie** [comment]
> EsteFilipe

@EsteFilipe @zashton This is the WIP PR #930 . It would be amazing if you could finish it.

**Comment by crabsinger** [comment]
Awesome -  glad this is moving forwards!

**Comment by crabsinger** [comment]
hey @EsteFilipe - let me know if you have any questions on this. Excited you are going to move the PR https://github.com/coordinape/coordinape/pull/930 across the finish line.

**Comment by EsteFilipe** [comment]
hey there @crabsinger I've been having trouble the past couple days building the repo - I was using windows and needed to do an ubuntu boot to get everything to work. the next days will be working on it :)

**Comment by EsteFilipe** [comment]
I've checked and everything seems to be intact post login. PR here, just added a couple lines regarding the domain in the message to sign. https://github.com/theosirian/coordinape/pull/1

For the back-end login endpoint I think it would be a good idea to create a .env variable to set the expected domain, to use it for cross-checking with what's received in the message, what do you think? Once this detail is set, we should be good to go.

Regarding the TODO comments in [`api/time.ts`](https://github.com/coordinape/coordinape/commit/f5f3d8c430047ccea437bd5c5ef30a1ce3e094b8#diff-1d264a5920d3174bc688e091ccedc1412eae67fb1e5e76e00461dbe7c5a71698)

> // TODO: might want to save the generated nonce and verify against it

This doesn't seem to be necessary as we never need to verify the signature again past the initial login.
