### ISSUE TITLE
Warning when opting in or opting out.

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#381]
A warning is needed when a user or admin are adjusting the opt-in/opt-out status to alert them that all allocated GIVE will be removed from this user after the setting is changed. 

# Current process
## Case 1
Admin changes a user with give allocated to be opted out.
![image](https://user-images.githubusercontent.com/82838264/147257892-1f46b990-0a3f-46b7-8961-8e73307c047e.png)
No warning, give removed, and status changed

## Case 2
User opts themselves out of receiving GIVE
No warning, give removed and status changed

# Recommended process
## Case 1
Admin changes a user with give allocated to be opted out.
![image](https://user-images.githubusercontent.com/82838264/147257892-1f46b990-0a3f-46b7-8961-8e73307c047e.png)
Recommended warning box here: https://www.figma.com/file/eAq3jcr4epDSof4mn255SR/opt-out-warning?node-id=2%3A6
![image](https://user-images.githubusercontent.com/82838264/147257666-e56428d7-19f7-4e31-bdaf-cf623a7913dc.png)
Click "Okay, got it" button 
GIVE Removed and status changed.

## Case 2
User opts themselves out of receiving GIVE
Warning 
![image](https://user-images.githubusercontent.com/82838264/147259195-321143f2-320e-4c3c-9df0-5425436f47c6.png)
Click "Okay, got it" button 
give removed and status changed

@AlexDistill please provide guidance here (Close if you don't think we need it)

**Comment by AlexDistill** [comment]
These notifications layouts look good as does the text copy. This is ready
to be built IMO.

**Comment by reeserj** [comment]
@spydermonkee Tagging with good first issue and 1, I think this is easy but not a dev so could be wrong.

**Comment by cashd** [comment]
Chatted with @spydermonkee and this seems like a good first contribution task. Currently in progress.
