### ISSUE TITLE
Map empty state, after nav from circle with epochs

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#386]
**Problem**
1. Be in circle with existing epochs on MAP page
2. nav to circle with no epochs (via dropdown nav)
RESULT - empty epoch dropdown selector (on upper left of main body) and empty Active Users side panel 
EXPECTED - complete empty state 

Note - refresh goes to complete empty state

![image](https://user-images.githubusercontent.com/5608004/147969158-82cb7c3f-d28b-430c-828a-6a64468ea47d.png)

**Solution**
Suggest that map page be in completely empty state since with no epochs, the epoch selector and team panel are both irrelevant at this stage 

![image](https://user-images.githubusercontent.com/5608004/147969258-cc97e1e1-ae0a-4ff2-ab02-1f27ef624f17.png)

**Stakeholders**
Dev team, Design team

**Comment by sshmm** [comment]
@spydermonkee  this issue should be marked as resolved right?
I don't see the unexpected behavior in latest origin/main

**Comment by spydermonkee** [comment]
Actually, I see this behavior still when I try to follow the reproduction
steps. It's still valid, although a small consequence.

**Comment by sshmm** [comment]
@spydermonkee I think this one should be closed as it resolved after new map design #914
