### ISSUE TITLE
Save button disabled on profile image edit

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#387]
**Problem**
1. nav to edit profile
2. change profile image
RESULT - save button disabled and does not autosave
EXPECTED - save button enabled to save updated profile image

**Solution**
after uploading profile image, enable save button to enable save of new profile image

**Stakeholders**
Dev team

**Comment by levity** [comment]
See my response to #388 -- probably a UX issue, not a bug. That said, agree it's confusing.

**Comment by f1lander** [comment]
@levity do you want to review and see if I can improve the ux for this?

**Comment by levity** [comment]
@f1lander I'd defer to @AlexDistill and others on the design team about priorities for smaller fixes like this.

**Comment by spydermonkee** [comment]
@levity, thanks for your quick response on this. Yeah, it is confusing, but does work as you say. I'd like to refer this to the design team (ping @AlexDistill).
