### ISSUE TITLE
Save profile image doesn't work

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#388]
**Problem**
1. nav to edit profile
2. udpate image
2. add some text to get around "save button disable bug" https://github.com/coordinape/coordinape/issues/387
3. save
RESULT-  Image not updated (on main profile or edit profile screen)
EXPECTED - image updated

**Stakeholders**
Dev team

**Notes**
- produced in Chrome on Mac
- refresh after save also does not update
- other edits to Biography text and skills persist correctly, just not profile photo

**Comment by levity** [comment]
Haven't checked recently, but this  is probably a known UX issue. Saving the profile photo is done differently than the rest of those fields. You have to click once to pick an image, then after you do so, that button is changed, and you click it again to finish the upload.

**Comment by spydermonkee** [comment]
@levity - Yep - I see that you are correct. I was able to save a profile photo correctly. As I get my bearings, if you have a moment to direct me,  can you share the best place to report this as a UI issue? I think that this as well as the background image update are a bit counter-intuitive and easy to miss. 

Thanks for your quick triages and response, @levity!

**Comment by levity** [comment]
This is a fine place to report it as a UX issue :)
