### ISSUE TITLE
Edit background image doesn't work when choosing same image twice in a row

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#389]
**Problem**
Background doesn't show preview on second try if same image was selected twice. (without saving by using the "Upload Background" button).

1. choose edit background button
2. choose file
3. hit "x" instead of "upload background"
4. edit background button
5. choose same file again

RESULT - nothing happens (no background change and no info)
EXPECTED - image preview on background 

Note - refresh allows same image to work again

**Solution**
Allow multiple tries with same image

**Stakeholders**
Dev team

**Comment by CryptoGraffe** [comment]
i can check this out
