### ISSUE TITLE
Replace manifest and fullCircle GET requests w/ GraphQL

### ISSUE THREAD

**Issue by exrhizo** [coordinape/coordinape#395]
@exrhizo: I thought this would be a good step

These are the two endpoints that are how the app currently gets data from Laravel.

Part of step 3 on the Notion plan "Setup GraphQL frontend library to read (and write) data" (https://www.notion.so/coordinape/Hasura-Migration-Project-b9312ea20c8d449cbbc9b97316eec840)

This is a subset of #409. 👍🏼

**Comment by crabsinger** [comment]
I think this will end up being a task created out of #409

**Comment by topocount** [comment]
We might want to shape this to figure out what data we want to keep querying and what we can do without.

We also might want to decompose this into the different queries we'll call at different points.

**Comment by CryptoGraffe** [comment]
This is replaced by #758 #744
