### ISSUE TITLE
Validate Hasura permissions match our policies for data visibility/access

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#401]
This issue is to validate and test our Hasura permissions represent the access and visibility we want to have for our data policy.

Tasks to complete this include testing the Hasura GraphQL API using the Hasura console to make requests as different roles (admin, and different users in different circles) to ensure that we are properly exposing data only to the API roles which should have access to that data.

See this Notion (may need access) for more details: https://www.notion.so/coordinape/Public-Data-Access-c082f176eb3d4ccf8cb0f1dff92b63f9

**Comment by reeserj** [comment]
@crabsinger this is in progress right?

**Comment by crabsinger** [comment]
I think this task is complete... @zashton @topocount @CryptoGraffe anything additionally we should explicitly test?

**Comment by zashton** [comment]
@crabsinger perms was completed long ago, can close this if no complains of other data visibility issues
