### ISSUE TITLE
Migrate cron jobs and any background tasks from Laravel into Hasura’s cron triggers system.

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#404]
This issue is to migrate Laravel's cron and background tasks into Hasura.

Hasura has a Cron system: https://hasura.io/docs/latest/graphql/core/scheduled-triggers/create-cron-trigger.html

that can be used to replace Laravel's cron tasks. However, for each cron job we should look and see if there is an option to move to an event based system instead of a cron based system for the same functionality.

1. List all of Laravel's cron and background tasks
2. Decide how best to migrate these tasks (and create a list here or in separate Github Issues for each of these tasks.

**Comment by jsur** [comment]
There are at least these cron tasks, are there any other patterns used in this project to run scheduled tasks I should know about?

```
➜  coordinape-backend git:(main) php artisan schedule:list

+-----------------------------------------------+-------------+-------------+----------------------------+
| Command                                       | Interval    | Description | Next Due                   |
+-----------------------------------------------+-------------+-------------+----------------------------+
| '/usr/bin/php' 'artisan' close:epochs         | */5 * * * * |             | 2022-01-16 10:45:00 +00:00 |
| '/usr/bin/php' 'artisan' check:enotifications | */5 * * * * |             | 2022-01-16 10:45:00 +00:00 |
| '/usr/bin/php' 'artisan' daily:update         | 0 21 * * *  |             | 2022-01-16 21:00:00 +00:00 |
| '/usr/bin/php' 'artisan' check:nominees       | 1 0 * * *   |             | 2022-01-17 00:01:00 +00:00 |
+-----------------------------------------------+-------------+-------------+----------------------------+
```

**Comment by jsur** [comment]
`check:nominees` seems to be the simplest one in terms of business logic, it checks expired nominees and sends messages to Telegram and Discord. All tasks send notifications so that's a common functionality for all.

**Comment by crabsinger** [comment]
@zashton FYI.

**Comment by zashton** [comment]
Name | Frequency | Logic
-- | -- | --
Close Epochs|*/5 * * * *|Iterate through every circle and check for epochs that has yet to end but has past its `end_date`.  Duplicate over all the `pending_gift_tokens` to `token_gifts` and purge away the existing pending records. Check if `auto_opt_out` = 1 , if yes set those users that are allowed to give and that didn't allocate this epoch to opt out. Create a snapshot of the user's bio and save in the histories table. Update all users in the circle and reset their `give_tokens_received` to zero , and `give_token_remaining` to `starting_tokens`, `epoch_first_visit` to 1 and `bio` to null. Set epoch number to epoch if not yet by counting through past ended epochs and set it to ended. Send discord/telegram notification to with list of users that didn't allocate this epoch. Purge the redis cache of `token_gifts` records of this specific circle. Check if epoch is a repeating epoch, if its a weekly epoch add 7 days to the start date, if monthly add 1 month to it ( use the last day of the month or the specific end day of the existing epoch whichever is earlier.). Do validation checks if the new repeated epoch start_date doesn't intercept the end date of the current epoch, check if the repeated epoch intercepts with any other existing epochs in the circle. If no issues create the repeated epoch and send notification via discord/telegram to alert the start of a new epoch.
Check notifications|*/5 * * * *|Iterate through every circle with discord webhook or telegram chat id set. Notify via discord/telegram if epoch has just started. If epoch is less than 1 day away from end_date send epoch ending notification. Send individual DM reminders to specific users that has interacted with telegram bot and has outstanding GIVEs not allocated. 
Check Nominee Expiry|1 0 * * *|Iterate through all nominees that has yet to end, check if any of them has past their expiry date. If yes set the nominee record to end and send discord/telegram notification to notify nomination has past expiry date and failed.
Daily Update|0 21 * * *|Iterate through every circle with discord webhook or telegram chat id set. Get the details of the users that has allocated in the current day, how much they have allocated and overall statistics etc. Refer to an discord/telegram bot for example of a daily update

@jsur

**Comment by jsur** [comment]
Here's a draft PR for checking nominee expiry, I have a couple of questions about it: https://github.com/coordinape/coordinape/pull/499

**Comment by crabsinger** [comment]
@zashton @jsur so I'm curious about how best to migrate our cron jobs over from Laravel to Hasura. We have completed the #499 check nominiees (Nice work jsur!), so maybe we can start running that job on staging and disable it from running on Laravel on staging?

**Comment by topocount** [comment]
closing because:
#522
#523
#524
#525 

have all been merged.
