### ISSUE TITLE
Improve onboarding for permissionless circle creation

### ISSUE THREAD

**Issue by exrhizo** [coordinape/coordinape#406]
- Cut 3 questions
- Change wording

From @ivy 's report:
![image](https://user-images.githubusercontent.com/4206097/148827954-b0b60a8b-a44a-4469-be66-0d183da8b1d2.png)

“How may we contact you?” -> “Circle Point of Contact.”

**Comment by ivyquinzel** [comment]
### List of Coordinape Tool Tip Changes
Add Tools Tip to the following Call to Actions

**Allocate Page**
My Epoch 
Allocate GIVE 

**Admin Page**
My Circle 
Add Epoch 
Add Contribtior 
Non Giver?
Opted Out ?
GIVE Sent
Vouch For Nominees

**Create Epoch Modal**
Create Epoch - Add Small Description

**Comment by spydermonkee** [comment]
> ### List of Coordinape Tool Tip Changes
> Add Tools Tip to the following Call to Actions
> 
> **Allocate Page** My Epoch Allocate GIVE
> 
> **Admin Page** My Circle Add Epoch Add Contribtior Non Giver? Opted Out ? GIVE Sent Vouch For Nominees
> 
> **Create Epoch Modal** Create Epoch - Add Small Description

I think we should make a whole issue with this. We can either provide the copy on this ticket for each of the areas needing tooltips or drop those into a Notion page.
