### ISSUE TITLE
NaN value on Login method src/services/api.ts

### ISSUE THREAD

**Issue by f1lander** [coordinape/coordinape#420]
## Description:

When I tried to run the app locally with the prod api, got `NaN` on Login method located at `src/services/api.ts`

![image](https://user-images.githubusercontent.com/5679878/149851521-b1c28d39-f9a9-40b5-a05e-f090ff1593ce.png)
![image](https://user-images.githubusercontent.com/5679878/149851500-a5e3d781-de11-4f25-bab8-37086e2ffbf3.png)

`nowRew.text()` resolves this:
![image](https://user-images.githubusercontent.com/5679878/149851777-31fa1fc2-c5a1-43f3-88fc-691adcdbff9c.png)

That'ss why the try does not catch the error and assigned to now the current time

**Comment by levity** [comment]
@f1lander do you have this commit https://github.com/coordinape/coordinape/commit/963ce5c84dd238b9c9c94d97cb497297eb00e75b on your local environment? if you're on a branch, try merging from main back to your branch

**Comment by f1lander** [comment]
@levity sorry I did notice that is already solved on main, I was about to upload the PR with the fix :v ... closing this issue
