### ISSUE TITLE
Allocate Tooltips

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#427]
### Summary
New users do not understand Coordinape Native terms, and there is no additional information provided 
Tooltips with definitions for "Epoch" and "Allocate GIVE" that link to documents that provide additional context

### **Specification**
We need to add an "i" icon to step 3 in the stepper and the header "What did you do this epoch?" The "i" icon needs to trigger tooltips bubbles on hover with links in the learn more CTA. On mobile, the tooltip triggers by pressing. 

Epoch Tooltips Specification 
"An Epoch is a period of time where circle members contribute value & allocate GIVE tokens to one another."
Link - https://docs.coordinape.com/welcome/how_to_use_coordinape#my-epoch 

Allocate GIVE Tooltips Specification 
"Reward your teammates in the circle by sending them GIVE tokens."
Link - https://docs.coordinape.com/welcome/gift_circle#the-gift-circle 

[Desktop Prototype
](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=7%3A1034&viewport=241%2C48%2C0.29&scaling=scale-down-width&starting-point-node-id=7%3A1034&show-proto-sidebar=1&hide-ui=1)[Mobile Prototype](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=39%3A456&viewport=241%2C48%2C0.29&scaling=scale-down-width&starting-point-node-id=39%3A456&show-proto-sidebar=1&hide-ui=1)

### **User Story** 
When I am on the allocated page, I can learn more about how Coordinape works and what its terms mean quickly.

### **Acceptance Criteria** 
1. Scenario: User does not know the term GIVE
Given: The user navigates to the allocated page
And: On a desktop device
When: The user hovers over the "i" icon next to "Allocate GIVE."
Then: The system triggers a tooltip
When: The user clicks to the tooltip link 
Then: The system opens a new tab to the Gift Circle Doc 

2. Scenario: User does not know the term GIVE
Given: The user navigates to the allocated page
And: On a mobile device
When: The user presses and holds over the "i" icon next to "Allocate GIVE."
Then: The system triggers a tooltip
When: The user taps to the tooltip link 
Then: The system opens a new tab to the Gift Circle Doc 

3. Scenario: User does not know the term GIVE
Given: The user navigates to the allocated page
And: On a mobile device
When: The user clicks the term "Allocate GIVE."
Then: The system opens a new tab to the Gift Circle Doc 

4. Scenario: User does not know the term Epoch
Given: The user navigates to the allocated page
And: On a desktop device
When: The user hovers over the "i" icon next to "What have you been working on this epoch?"
Then: The system triggers a tooltip
When: The user clicks to the tooltip link 
Then: The system opens a new tab to the My Epoch section of the support doc 

5. Scenario: User does not know the term Epoch
Given: The user navigates to the allocated page
And: On a mobile device
When: The user presses and holds over the "i" icon next to "What have you been working on this epoch?"
Then: The system triggers a tooltip
When: The user clicks to the tooltip link 
Then: The system opens a new tab to the My Epoch section of the support doc 

6. Scenario: User does not know the term GIVE
Given: The user navigates to the allocated page
When: The user clicks the term "What have you been working on this epoch?"
Then: The system opens a new tab to the My Epoch section of the support doc 

### **Functional Requirement**
When the user triggers a tooltip, the tooltip must remain on the page long enough to click the "Learn More" link within the bubble. 

### **Assumption** 
The sections changed can leverage HTML to modify classes to add the "i" icon. In addition, tooltips interactions can delay so users can click on them before they disappear. 

### **Stakeholders**
Alex, the art director  &  Sascha, UI Designer

**Comment by MarcogodoyV** [comment]
Hi guys, I'd like to be assign to this issue, is that possible?

**Comment by spydermonkee** [comment]
Awesome! I assigned you. Feel free to ping me on our Discord for additional coordination. Good luck knocking this one out!
