### ISSUE TITLE
Vouching Card Not Updating with Vouches

### ISSUE THREAD

**Issue by Zemm111** [coordinape/coordinape#433]
**Current Behavior:** 
When a user vouches for a nominee, the card will not correctly count down the number of vouches to display that the vouch has been made.  It also does not record the name of the Voucher.  

**Expected Behavior:** 
Vouches remaining would count down toward zero and voucher's name would appear on the card.

**Confirmation:**
This has been reported by TempleDAO and also now observed by Zemm in the Coordinape Community Circle.

**Comment by reeserj** [comment]
May be intermittent as it worked for me shortly afterwards

**Comment by Zemm111** [comment]
@reeserj did you see the incorrect number of vouches?  To clarify, my vouch worked, it just didn't display that it worked.

**Comment by spydermonkee** [comment]
I saw the same thing that you saw, @Zemm111 :
After Zemm vouched, I saw no change. That is, that the vouching still said that 2 more were needed and I saw no evidence that Zemm had vouched.

**Comment by reeserj** [comment]
We're also seeing this in the WGMI circle.

**Comment by Zemm111** [comment]
@f1lander has there been any movement on this fix? Should it be assigned to someone else?

**Comment by f1lander** [comment]
> @f1lander has there been any movement on this fix? Should it be assigned to someone else?

No movement, we should assign to someone else.
