### ISSUE TITLE
Migrate POST v2/upload-avatar

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#435]
## Summary:
Migrate Upload Avatar Laravel API Endpoint functionality to Hasura.

### Details
This task is to migrate the functionality of `POST v2/upload-avatar` to Hasura.

We'll need to use a Hasura action to upload the data to S3, and then write the mutation to the database.

In Laravel, this endpoint has the following functionality.

**Middleware:** auth token

**Additional Validations besides basic inputs:**
validate max 10mb, file type jpg,bmp,gif,png

**Logic:**
80% image quality compression, append current timestamp to filename, delete previous image if exists and upload modified image to s3

**DB Tables:**
profiles

#### Notes:

 - Ngnix limits us to 1mb, let's use 2mb max, like twitter.

- We'll need to setup an S3 upload client in TS. Figure out what env vars are needed, and we can provision those env vars in our different environments (staging/prod). Let's find a well used library.

- We could convert the filename to wallet id pattern we'll be using in ceramic.

**Comment by exrhizo** [comment]
Ceramic ids are like this:
```
export const addressToCaip10String = (
  address: string,
  chainId: number = networkIds.MAINNET
) => `${address}@eip155:${chainId}`;
```

Also, moving forward, let's have a field for the full URL in the database, so create a new URL for that.

Finally, to work on this locally it seems easy to use fakeS3 in docker-compose, that would be nice to have if it is straight forward

**Comment by crabsinger** [comment]
This is a subtask of #403

**Comment by crabsinger** [comment]
Assignign this to @CryptoGraffe

**Comment by CryptoGraffe** [comment]
yep!

**Comment by CryptoGraffe** [comment]
So I have this ready in MR #547  but I did not do the ceramic ID or URL work. I'm using uuid filenames in order to keep the pattern of deleting previous file that was implemented in laravel. What do you want to be done here?
