### ISSUE TITLE
Admin Contributor Attributes Updates 

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#442]
### Summary 
We are changing the phrasing of contributor attributes to add more context and make managing users easier for admins. 

### Specification
The contributor's permissions are confusing to first-time users and the cognitive load to read the chart is high because of the excessive text. Therefore, I propose changing the Admin Table attributes, Add/Edit Contributor Modal, and Circle Settings. 

**Admin Page Contributor Table Changes** 
Non Giver ----> GIVER
Opted Out ---->  GIVE Recipient
Are they Admin ----> Admin

Instead of having "Yes" or "No." 
Yes ----> ✓
No  ----> ✖

The table's header will be sticky, so the chart header is always in view as you scroll. 

**Admin Page Tooltips**
Tooltips should appear on the following headers on the following headers: Giver, Give Recipient, and Admin. 

- GIVER - Circle Member allocating GIVE
- GIVE Recipient - Circle Member receiving GIVE
- Admin - As a Circle Admin, you will be able to edit Circle Settings, Edit Epoch settings, edit your users, and create new circles. Learn More - https://docs.coordinape.com/welcome/admin_info

**Add Contributor Modal** 
The following inputs will change from "Yes/No" into checkboxes. The following titles will also change. 

- Starting Tokens ---->  GIVE Allotment 
- Are They Admin?  ---->  Grant Administrative Permissions  / Connected to Admin on chart 
- Can Give? ----> Allow contributor to give tokens / Connected to GIVER
- Opted out ----> Allow contributor to receive tokens / Connected to GIVE Recipient 
- Force Opted out ---->  Removed

**Add Contributor Modal Tool Tips**
- Grant Administrative Permissions  - As a Circle Admin, you will be able to edit Circle Settings, Edit Epoch settings, edit your users, and create new circles. Learn More - https://docs.coordinape.com/welcome/admin_info
-  Allow contributor to give tokens - Allows the Contributor to get paid based on the amount of giving allocated by circle members  Learn More- https://docs.coordinape.com/welcome/gift_circle#the-gift-circle
- Allow contributor to receive tokens - Gives the member the ability to reward circle members with giving. Learn More - https://docs.coordinape.com/welcome/gift_circle#the-gift-circle
- GIVE Allotment - The maximum amount of giving a user can allocate in an epoch Learn More -https://docs.coordinape.com/welcome/gift_circle#the-gift-circle

**Circle Settings Changes** 
The following settings will change in vocabulary. 
Default Opt-In ----> Default Contributors GIVE

**Add Contributor Modal Tool Tips**
Default Contributors GIVE - Allows all new contributors to get paid based on the amount of giving allocated by circle members. Learn More https://docs.coordinape.com/welcome/admin_info#editing-circle-settings

[Desktop Prototype](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=28%3A2967&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=28%3A2967&show-proto-sidebar=1&hide-ui=1)

[Mobile Prototype](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=49%3A1046&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=49%3A1046&show-proto-sidebar=1&hide-ui=1)

[Add Contributor Modal](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=7%3A794&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=7%3A794&show-proto-sidebar=1&hide-ui=1)

[Circle Settings Modal](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=125%3A912&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=125%3A912&show-proto-sidebar=1&hide-ui=1)

### User Story
As an admin, I can easily see who can allocate, give and receive it. 

### Acceptance Criteria
1. Scenario: Admin wants to see if Leslie can GIVE 
Given: The user navigates to the circle admin page
And: On a desktop device 
When: The user scrolls to the Admin chart 
Then: The system shows a checkmark under GIVER
When: The user hovers over the "i" icon of GIVER
Then: The system shows the definition of GIVER 

2. Scenario: Admin wants to see if Leslie can receive GIVE
Given: The user navigates to the circle admin page
And: On a desktop device 
When: The user scrolls to the Admin chart 
Then: The system shows an X mark under GIVE Recipient 
When: The user hovers over the "i" icon of GIVE Recipient 
Then: The system shows the definition of GIVE Recipient 

3. Scenario: Admin wants to take away Leslie's GIVE ability 
Given: The user navigates to the circle admin page
When: The user scrolls to the Admin chart  
And: Clicks Edit 
Then: The opens the Edit/Add Contributor Modal 
When: The Admin Unchecked Allow contributor to give tokens 
And: Clicks Save
Then: The modal closes the chart shows an X next to GIVER

4. Scenario: Admin wants to see if Ivy has Admin permissions 
Given: The user navigates to the circle admin page
When: The user scrolls to the Admin chart  
Then: The header stays in the same place
When: The Admin gets to Ivy 
Then: The Admin can click a checkmark next to Ivy's name
When: The user hovers over the word Admin 
Then: The system shows the definition of Admin

4. Scenario: Admin wants to have all members not allocated on default 
Given: The user navigates to the circle admin page
When: The clicks Circle Settings 
Then: The Admin hovers over the word Default Contributors GIVE
When: The system shows the definition of Default Contributors GIVE
Then: The Admin clicks No 
And: Save

### Functional Requirement
Tooltips must appear long enough for users to navigate the tooltip link for approximately 2 seconds. In addition, the admin chart header must stay in the same place so users can see permission headers as they scroll. 

### Assumption
The developer can configure tooltip interactions in seconds. For example, developers can easily add the material design "i" icon to buttons that Front-End can change the vocabulary without significantly impacting the function of those permissions. 

### Stakeholders
@AlexDistill , the art director  &  Sasche, UI Designer

**Comment by amrro** [comment]
Hey @spydermonkee.

**Comment by levity** [comment]
@ivyquinzel please check out https://coordinape-git-fork-amrro-amrro-admin-attr-update-coordinape.vercel.app/ and leave any feedback here

**Comment by ivyquinzel** [comment]
Let's show this to the team working on organization terminology before we push

**Comment by levity** [comment]
@AlexDistill @smombartz @spydermonkee  see above -- lemme know if there are any design/UX-level blockers to resolve before this can be shipped

**Comment by smombartz** [comment]
> @AlexDistill @smombartz @spydermonkee see above -- lemme know if there are any design/UX-level blockers to resolve before this can be shipped

dont see anything that would block this!

**Comment by Zemm111** [comment]
The Add Contributor window might be well served by these ideas: 


1) By default, Allow to GIVE and Allow to RECEIVE GIVE should both be checked, IMO.  It would be less typical to add contributors as non GIVE recipients.

2) Do we want to use the term “tokens” here?  Or, do we want to just call it GIVE, since its not a token? i.e.:

- Allow contributor to send GIVE
- Allow contributor to receive GIVE

**Comment by levity** [comment]
Thanks for the feedback, @Zemm111; will take care of these items

**Comment by levity** [comment]
Yep!
