### ISSUE TITLE
My Epoch Modal Update

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#443]
### **Summary**
To add context for the user, we want to define the "My Epoch" modal.

### **Specification**
On the Create Epoch Modal, under the header, add the following definition: An Epoch is a time where circle members contribute value & allocate GIVE tokens to one another. 
Learn More - https://docs.coordinape.com/welcome/how_to_use_coordinape#my-epoch

[Epoch Modal UI Mockup](https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=7%3A795&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=7%3A1034&show-proto-sidebar=1&hide-ui=1)

### **User Story** 
As a new user, I can learn what Epochs are and create one. 

### **Acceptance Criteria** 
1. Scenario: Admin wants to get the circle to start allocating 
Given: The user navigates Create Epoch Modal 
When: The user can see the definition of Epoch
Then: Clicks the Learn More button 
Then: The system opens a new tab to the My Epoch section of docs

### **Stakeholders**
@AlexDistill , the art director  &  Sascha, UI Designer

**Comment by thea-exe** [comment]
Hi! Just wanted some clarification, is the Epoch Mockup that you linked a new section that should be added to the beginning of the "How To Use Coordinape" document ([https://docs.coordinape.com/welcome/how_to_use_coordinape])? Where would it go? 

Where would the definition go? or is the whole UI implemented?

Thanks! :)

**Comment by ivyquinzel** [comment]
The link I want to be used is in the Specification section of the issue. When the user clicks learn more, it should go to https://docs.coordinape.com/welcome/how_to_use_coordinape#my-epoch

**Comment by thea-exe** [comment]
Sorry I misinterpreted the whole post, gotcha! :)

**Comment by ivyquinzel** [comment]
For more context, here is the whole admin page. https://www.figma.com/proto/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?page-id=0%3A1&node-id=28%3A2967&viewport=241%2C48%2C1.23&scaling=min-zoom&starting-point-node-id=28%3A2967&show-proto-sidebar=1&hide-ui=1

If you click create Epoch, the desired design is implemented.

**Comment by spydermonkee** [comment]
@thea-exe - would you like to pick this one up and be assigned to it?

**Comment by thea-exe** [comment]
Yes please! I'll try my shot at it since it's my first issue :D

**Comment by spydermonkee** [comment]
Hi @thea-exe - Are you still working on this issue? 
Thanks!

**Comment by thea-exe** [comment]
Yes!! Sorry, the local environment setup is giving me trouble but I’m
getting it resolved!

**Comment by spydermonkee** [comment]
Awesome! Let us know if you need some support by chatting in the #devs Discord channel. Maybe you have been already and you have a different name on there??? 
Several others in the last week like Topocount and Cryptograph have been also working through some of the local setup. 
Thanks for being here!

**Comment by spydermonkee** [comment]
Hi @thea-exe - Any news on this ticket? You making progress? Have you been communicating in our Discord as well? Apologies if you are already collaborating with our team!

**Comment by thea-exe** [comment]
Hi! Thanks so much for checking in— I had a thread opened on this issue
since last week so I’m slowly resolving it since me and someone on the dev
team is dealing with a new issue concerning my environment! Still working
on it :)

**Comment by spydermonkee** [comment]
Awesome - thanks for that update! Do you mind sharing your Coordinape Discord server handle? Perhaps even by DM'ing me on there? I'm @spydermonkee2418 there.

**Comment by thea-exe** [comment]
I’m @arduweeno#2025!

**Comment by spydermonkee** [comment]
Hi @thea-exe - How are you doing with this issue?

**Comment by spydermonkee** [comment]
Hi @thea-exe - this is the last issue in this milestone and we're keen to get it wrapped soon. Can you share an update on what's happening with this? Thanks :)

**Comment by thea-exe** [comment]
Hey! I’m so sorry I didn’t get a notification, I think you can pass this
onto someone else since my local environment has been a struggle for me.
I’ll hop back soon once I become successful with the local env setup!

**Comment by spydermonkee** [comment]
Sorry to hear that you're having so much difficulty with the local env, @thea-exe! 
Ping us in the DEV channel (and ping me to help wrangle more expert help) if you want support. We would love to have contributions from you!

**Comment by cashd** [comment]
chatted with @spydermonkee, going to pick this task up!

**Comment by spydermonkee** [comment]
heyo, @cashd! 
I've assigned this to you. Let us know if you're not working on it. :)
