### ISSUE TITLE
Migrate Create Nominee Endpoint Hasura

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#455]
Logic
- Use the circle's nomination day limit and add today's date to it to calculate the expiry date of the nomination and also capture the `min_vouches` value from the circle. 
- Check if `min_vouches` is = 1 if yes create a new user in the circle with the address
- Create a new profile record for the address if it doesn't exist already.

Validation
- Check if the nominee address exists as a user in the circle or exists in the nomination table of the circle

**Comment by CryptoGraffe** [comment]
Fixed by https://github.com/coordinape/coordinape/pull/552
