### ISSUE TITLE
Scheduled Epoch Dates displaying incorrectly

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#473]
**Problem**
![image](https://user-images.githubusercontent.com/82838264/151215382-4815ac70-beb5-4e0c-bcd5-ac93e8d507aa.png)

Monthly Epochs are displaying incorrectly

**Steps to Reproduce**
Set monthly recurring Epoch  (In Example Feb 1) next scheduled Epoch is showing up for March 2nd (Should be for March 1st) 

**Solution**
Adjust the display logic to be correct

**Specification**
@zashton need your help here

**Stakeholders**
@zashton

**Comment by f1lander** [comment]
@reeserj can you add steps to reproduce this please maybe this can be done by FE
