### ISSUE TITLE
Gnosis Safe Dapp Integration Spike

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#475]
### Specification 

This is a research investigation to look into implementing Gnosis Safe as a way to enable funding vaults with Gnosis safes.

https://blog.gnosis.pm/turn-your-dapp-into-a-gnosis-safe-app-in-5-minutes-5cdb33a1cd46

**Comment by teeolendo** [comment]
Because we use WalletConnect, we support Gnosis Safe. by default because we don't have signing of transactions. So we're good for now. We might want to consider adding Safe App support. https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-provider

**Comment by teeolendo** [comment]
``
