### ISSUE TITLE
Write Shared Code: Circle ID Generator 

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#486]
### Specification

Since only the vaults will be on-chain at first, the `circle` arguments in the contracts will not be addresses, but arbitrary `bytes32` values. So we need to define a convention that allows us to map the IDs of circles in our database to `bytes32` values & vice versa. These are used when setting allowances, uploading epoch roots, & claiming.

Suggestion: use circle ID from database, prefixed with some version tag for future-proofing, separated by some special character. e.g. “v1-17”. Then convert this string to a `bytes32` using e.g. the ethers.js [Bytes32String](https://docs.ethers.io/v5/api/utils/strings/#Bytes32String) utility functions.

**Comment by levity** [comment]
won't be on main until #577 is merged
