### ISSUE TITLE
Add distributed amount to History Page

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#492]
### Specification

Show the amount of tokens distributed, not just GIVE 

https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/App-1.0?node-id=3987%3A15460

Depends on #556

**Comment by f1lander** [comment]
Hi guys, I want to know about this issue ![image](https://user-images.githubusercontent.com/5679878/153058453-66fd38bf-9747-4670-a58b-259e4a6b0916.png)

The feature to build is the popup, right? is the answer is yes I will split this in subtask to focus on top components using storybook to then put together.

hanks!

**Comment by levity** [comment]
> Hi guys, I want to know about this issue
>
> The feature to build is the popup, right? is the answer is yes I will split this in subtask to focus on top components using storybook to then put together.
> 
> hanks!

Hey @f1lander, actually the popup is covered in issues #470 and #481. This issue is just for changing the history page itself to show the total tokens, e.g. the "60,000 USDC" in your screenshot.

**Comment by f1lander** [comment]
Oh got it, I'll will assign to me because I just started those, thanks!
