### ISSUE TITLE
Display Bug on UI cards

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#494]
**Problem**
Tags and PFP on cards only showing up after an allocation has been made in the allocation page of the app. (See video)

https://user-images.githubusercontent.com/82838264/151451207-b1d7da74-4c37-48c5-ad80-998552b173d6.mov

There may be a similar issue that is causing the description on the Coordinape Card to not display the description 
![image](https://user-images.githubusercontent.com/82838264/151452442-a4647dfb-463d-4555-b06a-bcfd9006cbb1.png)

**What should happen**
the tags should always display on the cards as long as they fit (If they have more tags than will fit I think we've said in earlier versions to just take the first 3.

**Steps to recreate**
1. Go to the allocation page of a circle that has a live epoch, and has Team Selection enabled
2. Click the + icon to give more give
3. tags and pfp will show up if the user has selected any.

**Comment by levity** [comment]
this should be fixed in 0cc4338; please try it out and see

**Comment by reeserj** [comment]
Working.
