### ISSUE TITLE
Build (Vaults) Submit Distribution: Part 2.2 Create Merkle Distribution

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#506]
### Specification

- you may want to call this without a previous distribution arg just to make sure that it matches the values that were shown in the table
- use `createDistribution` in `lib/merkle-distributor` 
    - for values to be submitted to the chain, call this with `previousDistribution` set to the stored distribution data for the previous epoch, if one exists ([why?](https://www.notion.so/Vault-Contracts-Walkthrough-705a0b4abfa04adb9db7dbc025d95da6))
- actually submit to blockchain (`ApeDistributor.uploadEpochRoot`) 
- make sure the number of decimal places matches token's decimal places

**Comment by levity** [comment]
i removed the comment about tapBase; false alarm

**Comment by levity** [comment]
@teeolendo i think we need to leave this one open until this part's completed:

> for values to be submitted to the chain, call this with previousDistribution set to the stored distribution data for the previous epoch, if one exists

**Comment by levity** [comment]
though on second though, i could also see a case for deferring that part to #480 or #507 since it depends upon stored data. what do you think?
