### ISSUE TITLE
Build (Vaults) Submit Distribution: Part 2.3 Store Distribution Data in Backend

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#507]
### Specification

- when submitting an epoch root, we need to store all the info generated--the "balance map" that contains amounts & proofs, the total amount, etc--in the backend, so we can use it again later. claimers will need the proofs to claim their distributions, and the circle admin will need the full list of amounts for generating the root for the next epoch

- adding this to hasura
  - new table, e.g. `distributions`. suggested columns below:
    - foreign key to epoch
    - JSON column for the entire merkle distributor info object ([e.g.](https://github.com/coordinape/coordinape/blob/main/src/lib/merkle-distributor/fixtures.json#L9))
      - feel free to break this out into more columns if appropriate
    - standard timestamp column (created_at)
    - foreign key to user who submitted it
  - create migration to create this new table inside local hasura console, which should generate migration files that will get run for the PR against a temporary hasura preview app
  - write mutation that stores the data into this new table

**Comment by teeolendo** [comment]
This is a basic ERD for the table that should be created. Created this to ensure that we all on the same page. @levity @spydermonkee 
![Distribution_ERD](https://user-images.githubusercontent.com/2772900/155584304-19544881-a354-4662-a98a-7d109217cee6.png)

**Comment by levity** [comment]
seems basically correct to me, just some minor tweaks:
- `distribution_id` & `claim_id` can just be `id`
- snake_case all fields
- `claims` should also have a foreign key to the user. yeah, we could just do address comparison, but that is slower and just feels wrong

ok, this one's a less-minor change:
- add a vaults table and have a foreign key from distribution to that table, so we know token type among other things... we actually haven't created an issue for creating a vaults table yet, just [this block](https://www.notion.so/coordinape/On-Chain-Vaults-27a8a1da30f04967a240df9dd4ddae76#fd6c4782822446eca3dae79f65ad1988) in Notion

**Comment by teeolendo** [comment]
Here's the updated ERD with Vaults @levity makes sense to add this to the migration anyway given where we are at with that.
![Distribution_ERD](https://user-images.githubusercontent.com/2772900/155616185-931ac24d-a2b7-498a-a64a-013d34940b9e.png)

**Comment by levity** [comment]
new tasks:

- [ ] add `new_amount` column to `claims` to track only the amount added in the newest epoch, not the aggregate amount
- [ ] add `distributor_id` (name change?) column to `distributions` to track the `epochTracking` value associated with this distribution in `ApeDistributor`
