### ISSUE TITLE
Migrate End Epoch Cron Trigger

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#524]
## Summary:
Migrate Check EPOCH (Start/Ending) Laravel Cron Trigger functionality to Hasura.

### Details
This task is to migrate the functionality of Check EPOCH (Start/Ending) to Hasura.

**Middleware:** Hasura event secret middleware

**Additional Validations besides basic inputs:**
Nil

**Logic:**
*/5 * * * *
Iterate through `epochs` that has  `end` = false but has past its `end_date`.  Duplicate over all records of `pending_gift_tokens` to `token_gifts` and purge away the existing `pending_gift_tokens` of this circle. Check if circle's `auto_opt_out` = true , if true set `users` inside the circle that didn't allocate this epoch (`starting_tokens` == `give_tokens_remaining`) to opt out(`non_receiver`= 1). 

Create a snapshot of the user's `bio` record and save in the `histories` table. Update all users in the circle and reset their `give_tokens_received` to zero , and `give_token_remaining` = `starting_tokens`, `epoch_first_visit` to 1 and `bio` to `null`. Set `number` to epoch if not yet by counting through past ended `epochs` and set it to `end` = true. 

Check if the circle of the epoch has telegram_id or discord_webhook set and ended = true & check protocols as well for telegram_id for notifications

an e.g of discord/telegram notification 
```
protocol_name / circle_name epoch has just ended!
Users that did not allocate any GIVE Tokens:
xxx, yyy, xxxuser_name

```
(`repeat` = 0 = 1-time, `repeat` = 1 = weekly, `repeat` = 2 = monthly )
Check if epoch is a `repeat` epoch, if its a weekly epoch (for the new repeated epoch) add 7 days to the `start_date`, if monthly add 1 month to it ( use the last day of the month or the specific end day of the existing epoch whichever is earlier.). Do validation checks if the new repeated epoch `start_date` doesn't intercept the `end date` of the current epoch, check if the repeated epoch intercepts with any other existing epochs in the circle. (Take Note that the `end_date` of the ending epoch is allowed to be exactly the same value as the newly created epoch's `start_date` time also need to be factored in. )

If no issues create the repeated epoch and send notification via  to alert the start of a new epoch.
e.g of an discord/telegram notification
`A new repeating epoch has just been created 2022-02-24 22:11:00 to 2022-03-03 22:11:00
`

**DB Tables:**
`circles`,`epochs`

#### Notes:
@jsur

**Comment by spydermonkee** [comment]
Hi @jsur!
Also, this one. Can you share where you're at with this? 
Thanks!

**Comment by topocount** [comment]
@zashton how do you want to merge this and coordinate the laravel-side shutoff? I'm inclined to let you merge this when is convenient for you.
