### ISSUE TITLE
all tables need a trigger to update the `updated_at` column automatically. This behavior was handled in Laravel ORM previously.

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#536]
e.g. 
```
CREATE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp
BEFORE
UPDATE ON profiles
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();
```

**Comment by crabsinger** [comment]
Probably should auto-create an `created_at` too, as that's usually down by the ORM as well.

**Comment by topocount** [comment]
> Probably should auto-create an `created_at` too, as that's usually down by the ORM as well.

postgres actually does this for us: 
![image](https://user-images.githubusercontent.com/17910833/156800086-22785a96-e1f1-4d40-b8d8-3f80fa791167.png)

**Comment by crabsinger** [comment]
> > Probably should auto-create an `created_at` too, as that's usually down by the ORM as well.
> 
> postgres actually does this for us: ![image](https://user-images.githubusercontent.com/17910833/156800086-22785a96-e1f1-4d40-b8d8-3f80fa791167.png)

Oh, awesome. And that's setup on all our tables? @topocount

**Comment by crabsinger** [comment]
@CryptoGraffe do you want to implement this?

**Comment by reeserj** [comment]
@CryptoGraffe is this ready to close?

**Comment by CryptoGraffe** [comment]
@reeserj No it's not, I haven't started on it. I thought someone else in discord said they wanted to work on it but I can't find that message now
