### ISSUE TITLE
Migrate Delete User v2/{circle_id}/admin/{address}

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#543]
## Summary:
Migrate Delete User Laravel API Endpoint functionality to Hasura.

### Details
This task is to migrate the functionality of `<DELETE v2/{circle_id}/admin/{address}>` to Hasura.

In Laravel, this endpoint has the following functionality.

**Middleware:** Hasura circle admin + event secret middleware

**Additional Validations besides basic inputs:**
- admin and deleted user in the same circle
- check if address exists in the circle

**Logic:**

Set user's `deleted_at` col to current timestamp. Purge all `pending_gifts` rows with token value received/sent by the user. Refund the `token` value of each into the sender's `give_token_remaining`. Next, deduct the `token` value of each from the recipient's `give_token_received`. Delete all records of `teammates` that has `user_id` or `team_mate_id` associated with it. Finally, soft delete the user by setting the current timestamp at `deleted_at`. Also set its `give_token_received` to 0 , `give_token_remaining` to its `starting_tokens` value . 

**DB Tables:**
`users`, `pending_token_gifts`, `teammates`

#### Notes:
theres a possibility we could change the `address` input to `user_id`, shall leave it to the person implementing.

**Comment by topocount** [comment]
Check out the `resetuser` logic in laravel and see if that's applicable to any other patterns

**Comment by zashton** [comment]
@topocount checked this one, the other place its used is inside `bulkDelete` user
