### ISSUE TITLE
Refactor ApeAvatar to only take user image props

### ISSUE THREAD

**Issue by teeolendo** [coordinape/coordinape#545]
## Updated task

Remove ApeAvatar and NewApeAvatar; refactor to use src/ui/Avatar instead.

previously:

----

**Problem**
The ApeAvatar component uses the IUser object to as a prop. It's overkill to use the entire object.

**Solution**
ApeAvatar only requires either the user profile image or the user image path.

**Specification**
Ensure that the ApeAvatar only uses the single string prop that points to the location of the users avatar and refactor all instances of ApeAvatar to use the new prop.

**Stakeholders**
@levity

**Comment by levity** [comment]
As can be seen in #533 above, there's currently a NewApeAvatar component that goes in this direction but is duplicative of ApeAvatar. 

As part of this task, once ApeAvatar is changed as described, remove NewApeAvatar and replace its uses with the new ApeAvatar.

**Comment by sshmm** [comment]
@levity does that mean this is implemented?  I see mixed usage between ApeAvatar and NewApeAvatar.

**Comment by levity** [comment]
Right, it's still only partly done.

**Comment by amrro** [comment]
I just implemented a new `ui/Avatar` using stitches and updated it to only accept user's avatar path and user's name in #739.

@levity, I can utilize the new avatar component, but waiting for merging.

**Comment by CryptoGraffe** [comment]
@amrro do you want to make this change now that you are merged, or should someone else pick it up?

**Comment by levity** [comment]
Assigned to you @amrro. Please note that I've updated the task description.

**Comment by yahiamarzouk** [comment]
I can change every component  using Avatar.tsx instead of ApeAvatar.tsx and NewApeAvatar.tsx, is this is the task required for this issue?
or there is more to it?

**Comment by levity** [comment]
Yes, and then remove those other two from the codebase
