### ISSUE TITLE
Org View: Top Level Page

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#554]
**Specification**
Create the bare bones version of this page
- Orgs with circles stacked 
- Also don't do the claim button (may not be visible in current design)
  - that's covered by #470, #481

https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/App-1.0?node-id=3987%3A14953

**Note that the the whole milestone of [ORG VIEW  ](https://github.com/coordinape/coordinape/milestone/5) should be released together on the app. These changes need to be released as one new feature :)

**Comment by spydermonkee** [comment]
@AlexDistill, @ivyquinzel, @smombartz - We need to finalize the circle overview choice. I prefer alt1

**Comment by spydermonkee** [comment]
@smombartz - decision made. When the design is ready, would you be willing to update the figma link in the issue description? Also, if you are good with the two button change (that we've been discussing in the Design Discord channel), then feel free to go that route. I'm just pushing for "done" here :)

**Comment by MarcogodoyV** [comment]
@spydermonkee I would like to be assign to this issue as we talk in Discord
