### ISSUE TITLE
Org View: Update Circle History page

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#556]
**Specification**

- Implement the new design for the circle history page seen [here in Figma](https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/App-1.0?node-id=3987%3A15460)
- See if it's possible to reuse the data-fetching that's already in place for the legacy history page
  - If not, pls comment; we'll probably create another task for redoing the data-fetching with GraphQL
- No need to add the claim button in the upper right; that will be covered by #470 & #481

**Comment by spydermonkee** [comment]
@MarcogodoyV - trying to assign you...

**Comment by MarcogodoyV** [comment]
> @MarcogodoyV - trying to assign you...

Since we couldn't find a way to assign me to this issue, I'll left this comment to let know I'm working on this (and the PR of this issue will be in Org-view Branch, in order to follow the previously talked in issue #555)
