### ISSUE TITLE
"Coordinape In Your Circle": Tooltip in members list in admin view

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#557]
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
- Add tooltip to the Coordinape user in the circle member list in the Admin view. Link on tooltip goes here: https://coordinape.notion.site/Why-is-Coordinape-in-my-Circle-fd17133a82ef4cbf84d4738311fb557a

Design: 
https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2590%3A10721

**Comment by j-yw** [comment]
@spydermonkee Can you assign this as well, thanks.
