### ISSUE TITLE
"Coordinape In Your Circle": ENABLE/DISABLE in members list in admin view

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#558]
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
- Add the ability to "Enable" or "Disable" the Coordinape member if you are an admin. 
- Add tooltip next to ENABLE/DISABLE explaining the option. 

This issue is a little more complex since it may involve some deeper changes to implement the state of "Coordinape as a Circle Member". 

For the enable, this would require a new hasura mutation that restores the user, mutation would set`deleted_at` back to a `null` value. This mutation can be for generic use in restoring normal users.
(validate that the address is still unique within the circle if restored).

For the disable you can use the hasura mutation that deletes a normal user.

Design: 
https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2692%3A9277

**Comment by topocount** [comment]
@spydermonkee how about enabling/disabling the coordinape user with the `non_receiver` field in the backend?

**Comment by spydermonkee** [comment]
Would we then create F/E logic that says IF "coordinape user" AND `non_receiver` THEN don't display in map and show disabled in member list... Or something to that effect? 
 I think it doesn't matter much how the backend implements if the experience result is what we are trying to get.

**Comment by topocount** [comment]
I just think `non_receiver` is a more discrete way to track this

**Comment by topocount** [comment]
@amrro if you comment on this PR requesting it be assigned to you we can now do so.

**Comment by amrro** [comment]
Thanks @topocount, 
Sure, I would like to hack this one.

**Comment by spydermonkee** [comment]
@amrro - Heyo! I see you've been doing some good stuff lately! Thanks a lot! Are you still working on this issue?

**Comment by amrro** [comment]
You are welcome. 

I haven't started working on it. I was Waiting to #739 to merge first.

**Comment by reeserj** [comment]
Looks like it's merged now! @amrro!

**Comment by amrro** [comment]
Hey @reeserj, Not sure what you are talking about. 
I guess #739 requires some changes and updating and I think it's ready.

**Comment by reeserj** [comment]
@amrro are you unblocked on this now?

**Comment by amrro** [comment]
> @amrro are you unblocked on this now?
> 
> 

Yes. On it.

**Comment by spydermonkee** [comment]
Hey @amrro - How is it going on this issue? Need any support?

**Comment by amrro** [comment]
hey @spydermonkee, I think it's done take a look here https://github.com/coordinape/coordinape/pull/1042

**Comment by spydermonkee** [comment]
@amrro - DOPE! Thanks a lot for continuing to crank on this! I see that Lawris is helping point the way and we're nearly there with this 💯 

I look forward to this getting across the finish line.

**Comment by crabsinger** [comment]
resolved by https://github.com/coordinape/coordinape/pull/1042
