### ISSUE TITLE
"Coordinape In Your Circle": Reinstate Coordinape member in admin view 

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#559]
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
- If the coordinape user ( user.role == 2) has a non-null `deleted_at` value show the user in a DISABLED state since the admin previously deleted it already and we don't want them to become annoyed that i's back against their will.

Design: 
https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2692%3A9277

**NOTE - this is dependent on #558**

**Comment by reeserj** [comment]
@amrro would you want to pick this one up when you finish #558 ?

**Comment by amrro** [comment]
Yes. I please assign it to me.

**Comment by crabsinger** [comment]
https://github.com/coordinape/coordinape/pull/1042 resolved this
