### ISSUE TITLE
"Coordinape In Your Circle": Update Tooltip in Allocate View

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#561]
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
1. Update existing tooltip on allocation page for regular circle members.  https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2731%3A10178

2. Update existing tooltip on allocation page for ADMIN circle members. https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2590%3A10681
Add Button to go to Admin Circle Settings

**Link on both tooltips ("Let us know what you think")) goes here: https://coordinape.notion.site/Why-is-Coordinape-in-my-Circle-fd17133a82ef4cbf84d4738311fb557a**

**Comment by j-yw** [comment]
taking this

**Comment by tiff0000** [comment]
Hi team! I'll get started on this task, thanks :)
