### ISSUE TITLE
Migrate Update Own User v2/{circle_id}/users

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#564]
## Summary:
Migrate Update Own User Laravel API Endpoint functionality to Hasura.

### Details
This task is to migrate the functionality of `PUT v2/{circle_id}/users` to Hasura.

In Laravel, this endpoint has the following functionality.

**Middleware:** Hasura event secret

**Additional Validations besides basic inputs:**
-

**Logic:**
Only Inputs to accept `name`, `non_receiver`, `bio`, `epoch_first_visit`

- Check If user is set to `non_receiver` from 0 to 1, Purge all pending_gifts rows with token value received by the user. (can keep those with purely notes). Set user's tokens_received to 0. Iterate through all users that sent tokens to this user and add back the tokens to their tokens_remaining.

**DB Tables:**
`users`, `pending_token_gifts`

#### Notes:
Notifications

Opt out notification via Telegram/Discord (if set) to notify respective channel/groups with refunded total to specific users.
Once you are opted out all the tokens you received will be refunded. The notification will indicate how much of your tokens was refunded + (breakdown of all those senders amount). if you didn't receive any then it will just indicate 0 is refunded.
e.g
$name opted out of the current epoch!
A total of 30 GIVE was refunded
senderName: 10
senderName2: 20
Use event triggers for the sending of notifications, so it doesn't block the mutation if the service fails and has an retry mechanism.

**Comment by topocount** [comment]
@zashton this requires a circle_id gql param to fully identify the user entry to update.

This might be implied based on the rest endpoint, but I figured it was worth pointing out explicitly.
