### ISSUE TITLE
App not refreshing when changing circles

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#581]
**Summary:**

1. **What is actually happening:**
https://discord.com/channels/845400066532704256/854757515899699200/948319857244536872

When switching between circles as an admin user stated they exported CSV for circle 1, swapped to circle 2, and then exported CSV again, the second CSV file resulted in a prior epoch from Circle 1. 

2. **What should be happening:**
It's like the app didn't refresh when the user changed circles and so it brought in the wrong data despite displaying the correct data.

3. **Steps to recreate:**

1. Find two circles with epochs 
2. Go to Admin tab
3. export CSV from Circle 1, 
4. quickly navigate to circle 2
5. Export CSV from Circle 2
6. Ensure exports from both csv's match the circles they should have come from

4. **Screenshots/GIF/Video recording**
I couldn't replicate, but it feels similar to some of our other bugs where switching circles doesn't push through to the whole app.

@spydermonkee Can you help scope this (Since I can't re-create not sure if we should even keep it or not)

**Comment by crabsinger** [comment]
Is this reproducible, if not, maybe we should close? @reeserj @spydermonkee
