### ISSUE TITLE
Allow export of complete asymmetric token allocation graph as .csv

### ISSUE THREAD

**Issue by NiklasTR** [coordinape/coordinape#593]
**Problem**
What problem is this feature addressing?
Within LabDAO we are using coordinape since December. We really like the tool but have been seeing pathologies in the mechanism design where members with a relatively low contribution to project value but strong confidence allocate large numbers of tokens in ways that are not reflecting the perceived reality of most contributors within the project.
In order to start experimenting with ways to map $GIVE tokens into actual governance tokens, we would like to export the complete directed graph matrix (so know who gave whom how many tokens, the rows are users and the columns are users, and the cell value is the number of tokens - the matrix will be asymmetric) instead of a tallied-up balance of tokens per users. 

**Solution**
What's your proposed solution to the problem?
An option in the settings page that says - "export detailed report to csv? Yes/No". Hitting export .csv after toggling this option will give us the matrix described above.

**Specification**
What precisely needs to get built? (include any requirements or design files)
see above

**Stakeholders**
Who needs to provide input? Who might be impacted? Who needs to approve?
I think this could be a lightweight feature of the product. We can then go ahead and build our own open-source tooling around it to penalize bad $GIVE token behavior.

**Comment by NiklasTR** [comment]
@blahah in our team did this programmatically - https://dweb.link/ipfs/bafkreibcian4fm5z75ewvhntjwot7j7woyjor7k6wvq63coad3drwoi5fa

**Comment by reeserj** [comment]
@NiklasTR this data will be available via our API.

Available here- app.coordinape.com/developers

If that's sufficient for you please close this incident.

**Comment by NiklasTR** [comment]
Hi @reeserj - thank you! This looks great - should satisfy our needs. CC'ing @blahah
