### ISSUE TITLE
Bug: Username not wrapping on allocation card

### ISSUE THREAD

**Issue by teeolendo** [coordinape/coordinape#595]
**Summary:**
In the Allocation Card, a user with a long name doesn't wrap inside the card. It extends across the screen.
1. **What is actually happening:**
On the Allocate Card where you give a user GIVE, if a user has a long name, it extends across the screen.
2. **What should be happening:**
The name should wrap inside of the card component.
3. **Steps to recreate:**
Add a user with super long name to a circle. Create an epoch. Go the allocation page. The user's name will not be bounded inside the allocate card. It should wrap inside of the allocate card and should be limited with an ellipsis and a tooltip that potentially shows the user's full name.
4. **Screenshots/GIF/Video recording**
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/2772900/157085673-fb76d4c9-8e3c-4fdb-8907-88db23e1db06.png">

**Comment by tsejerome** [comment]
Working on this.
Just tested out two scenarios, as attached
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/20391660/160275529-cb06d772-8d97-47f6-8589-c4ea2b693750.png">

**Comment by tsejerome** [comment]
The same happens with profile page, and vouching pages, will fix tgt.

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/20391660/160275934-248dc142-0f36-44f7-8b88-7f5cc7c9f13a.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/20391660/160276207-5584d4d3-aaa1-4d07-97f9-eeacbf06c9e5.png">

**Comment by tsejerome** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/20391660/160278599-d543e5f2-ca92-4bfe-9dde-3a611ff953de.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/20391660/160278620-9c333cdf-f495-4749-bbc4-6ac230f5c2cc.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/20391660/160278654-bd210ba4-4242-4d64-82fa-533e866f242b.png">

**Comment by tsejerome** [comment]
Got my code ready, please invite me @tsejerome for access to push a PR/branch if possible! Thanks!

**Comment by reeserj** [comment]
This change looks to be live in prd. 

Closing and moving to shipped
<img width="761" alt="image" src="https://user-images.githubusercontent.com/82838264/163585879-27d96cab-1887-45c3-959d-f1740344fe76.png">
<img width="174" alt="image" src="https://user-images.githubusercontent.com/82838264/163585934-e334a465-940d-4ffb-8dcd-b599749d529f.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/82838264/163586014-ce6364c9-de66-4e02-9c74-b71359ae18cf.png">
<img width="665" alt="image" src="https://user-images.githubusercontent.com/82838264/163586066-78effe3b-3298-419b-88ee-42a1f4950a46.png">
