### ISSUE TITLE
User Support Circle Creation Form Updates 

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#601]
### **Summary**
We want to update the circle creation page to aid with user support. 
This request includes adding a Header, changing the Circle Point of Contact field, and adding the Discord support field.

[Proposal / Rationale](https://www.notion.so/coordinape/New-User-Support-Quick-Hacks-6f8f647147ee472c8d1c47ef931a2f91?d=a5b8d20b9cfc42c8b886c92fda9bd019)

### **Specification**

Design: https://www.figma.com/file/KciBaNjP5Q9idchsxMp9ek?embed_host=notion&kind=&node-id=190%3A790&viewer=1

Add Header "Coordinape Support"

**Circle Point of Contact Field** 
- Add a subheader under Circle Point of Contact with the following copy "We use this for follow-up & support."
- Change Helper Text with the text field to "Discord #0000, Telegram, Twitter or Email."
- Make this field required before the user moves forward
- Error Message Text  "Circle Point of Contact is Required"

**New Need More Help? Field**
- Add a new field to the right of Circle Point of Contact 
- Field Header: Need More Help?
- Subheader: Join Our Discord for Information & Support
- Add Discord Button with Call to Action Text "Join Coordinape Discord"  using this link "https://discord.gg/BG3fDAvzuB"

[You Can find CSS & Visual Styling in the Figma Inspect Section.](https://www.figma.com/file/KciBaNjP5Q9idchsxMp9ek/Coordinape-Tool-Tip-Additions?node-id=190%3A790)

### **Acceptance Criteria** 
**Scenario: User forgets to submit Point of Contact**
- Given: The user navigates to Create a Circle
- When: The Circle Point of Contact field is empty
- Then: The system remains on the same page
- Then: The displays error message "Circle Point of Contact is Required."

**Scenario: User needs support** 
- Given: The user navigates to Create a Circle
- When: The user selects Join Coordinape Discord
- Then: The system opens a new tab with a Discord Invite Link 

**Stakeholders**
@spydermonkee @ivyquinzel

**Comment by levity** [comment]
@ivyquinzel can you please take a look at https://coordinape-git-fork-amrro-amrro-user-support-d7b864-coordinape.vercel.app/new-circle and let us know if it looks good?
