### ISSUE TITLE
Remove Prisma from codebase

### ISSUE THREAD

**Issue by META-DREAMER** [coordinape/coordinape#605]
The only place we are using Prisma is the auth handler here: `https://github.com/coordinape/coordinape/blob/main/api/hasura/auth.ts`

We can replace this with using the Zeus admin client instead to talk to the database (like all the other api handlers).

Will allow us to remove all the prisma code generation logic as well in our bootstrapping steps.

**Comment by crabsinger** [comment]
weird this didn't auto-close with the merge of #649 ... manually closing now. @META-DREAMER this is fully completed now, correct?
