### ISSUE TITLE
Implement F1rewall to reduce Discord bot attacks

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#619]
**Problem**
Currently anytime we share a discord join link that link stays active for the set period of time or number of invites.  We have a couple of unlimited invites open to allow people to join the discord straight from our website or twitter account.

This leaves an attack vector open for bots to try and raid our server and send our users spam (Either in our server or via DM's) 

This prevents us from sharing links to our server freely.

**Solution**
We have a user in our server (Mirandaniel) who created a captcha tool that will create a single use invite to our discord each time the user clicks the link. 
If we can implement the proposal here https://www.notion.so/coordinape/Secure-Discord-Join-Links-9079808793a7403f91a34d8601cf9e28#77b43f6a45ae4ae7b9103b97ab00ff34 it would further secure our discord from attacks.

**Specification**
https://github.com/MiranDaniel/f1rewall is the github repo

Follow the setup instructions in the link above.

**Testing**

1. After implementing, ensure users are able to join via the link
2. Ensure the link provided is single use
3. Ensure the link provided times out after 1 hour.
4. @reeserj can help with testing

**Stakeholders**
@spydermonkee

**Comment by spydermonkee** [comment]
@reeserj - Including the whole set up instructions on this ticket could seem overwhelming to a community dev considering picking this up. Want to just link to it instead? 

Also, a good way to make sure a ticket makes sense is to think about what it would be like if you were being asked to do this and the ticket is the only way that you are being communicated with. So, with that frame, are there any more clear instructions or steps that you can spell out here? Under Specification, maybe it's something like: 
"Implement the f1rewall bot. Test that new users entering through our open invites must got through this flow and that it works."  <- That's super generic, and I think you can do better than me. Does this make sense?

**Comment by reeserj** [comment]
@spydermonkee makes sense. I was just trying to give them a one stop shop. 

I've pared it down and added success criteria.

**Comment by spydermonkee** [comment]
Awesome - One thing I didn't realize until later was that the person who made it would also be implementing. That makes it easier and a little different! This looks good. Do you want to assign it to MiranDaniel and ask if they want to do it?

**Comment by spydermonkee** [comment]
@reeserj  ☝️

**Comment by MiranDaniel** [comment]
Sounds great!

**Comment by reeserj** [comment]
Assigned to you @MiranDaniel! Thanks!

**Comment by MiranDaniel** [comment]
@spydermonkee does Coordinape have a server/vps that you want me to set this up on or do you want me to spin one up myself?

**Comment by spydermonkee** [comment]
Hey @MiranDaniel! 
Would mind asking for guidance in the Dev channel on Discord? I don't have the answer, but I would bet that DEV team would want to point you to a server to use.

**Comment by reeserj** [comment]
Update here- @zashton has provided @MiranDaniel the details he needs to get F1rewall implemented

**Comment by MiranDaniel** [comment]
Implemented on https://discord.coordinape.com/ , can close this issue now.

**Comment by reeserj** [comment]
@spydermonkee should I open a new issue to update all the invite links in the site, or should I add them to this?

**Comment by reeserj** [comment]
After talking with @spydermonkee closing this. I'll create more incidents to update the discord link across the app and homepage.

Thanks @MiranDaniel
