### ISSUE TITLE
FE Hasura Login

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#628]
## Summary:
Integrate Hasura login into FE.

### Details
This task is to integrate the frontend of `<login>` to Hasura.

**Screenshot of Page**
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/17747090/158579910-25a3b78b-93b1-441d-b7b8-6ac5f6ef2360.png">

**Logic:**

**Related Backend Issue:**
 #562

**Comment by reeserj** [comment]
Looking for help with contract based wallet testing
