### ISSUE TITLE
Integrate Hasura Update GIVES into FE

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#637]
## Summary:
Integrate Hasura Update GIVES into FE.

### Details
This task is to integrate the frontend of `<Update GIVES >` to Hasura.
https://app.coordinape.com/give

**Screenshot of Page**
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/17747090/158585544-9a33f4fd-dca5-4371-9915-d9279d8aad12.png">

**Logic:**
-

**Related Backend Issue:**
#568

**Comment by CryptoGraffe** [comment]
Blocked on #568
