### ISSUE TITLE
Integrate Hasura Update Epoch into FE

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#641]
## Summary:
Integrate Hasura Update Epoch into FE.

### Details
This task is to integrate the frontend of `Update Epoch` to Hasura.
https://app.coordinape.com/admin > Edit button beside epoch table

**Screenshot of Page**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/17747090/158587177-3d8c20cf-f34e-41c8-9e10-41071b69bc72.png">

**Logic:**
-

**Related Backend Issue:**
#566

**Comment by CryptoGraffe** [comment]
This was closed by PR #734
