### ISSUE TITLE
Remove Epoch dialog is not automatically dismissed on success and is not manually dismissable

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#659]
**Summary:**

1. **What is actually happening:**

Remove Epoch dialog is not dismissable and is not automatically dismissed after removing an epoch. 

2. **What should be happening:**

The dialog should automatically dismiss after removing an epoch, and should be dismissable by clicking the X or the gray mat outside the modal. 

3. **Steps to recreate:**
Visit admin circle page for circle with a deletable epoch

5. **Screenshots/GIF/Video recording**
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/95149165/159210422-f164be76-a164-46b8-9695-0929a058a1f7.png">

**Comment by sshmm** [comment]
@reeserj  fixed in [fix: allow delete epoch modal to be closed](https://github.com/coordinape/coordinape/commit/30aeef5a66db0b56dafc9685bbcda0b24244f402)
