### ISSUE TITLE
BUG: Show error in nominate form when ETH address invalid

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#671]
**Summary:**
When nominating a user there is no appropriate error text when the eth address is invalid 

1. **What is actually happening:**
No error is presented, but Nominate Member button is disabled

3. **What should be happening:**
There should be an error inline in the form

4. **Steps to recreate:**
Go to nominate a user, input an invalid ETH address

5. **Screenshots/GIF/Video recording**
<img width="729" alt="image" src="https://user-images.githubusercontent.com/95149165/159428039-6c899280-afb5-4d99-bfce-1d6a9b132681.png">

**Comment by sshmm** [comment]
is anyone working on this?

**Comment by sshmm** [comment]
@spydermonkee  when nominating a new user. the description should be at least three characters. that is the only condition
is this ok?
shouldn't it be a sentence at least
or may be it can be left empty?

**Comment by spydermonkee** [comment]
@sshmm - It's fine to just have validation that "something is in there" for now. Validating at least 3 characters is a decent enough proxy for "something". We are planning more changes with more specifics in the coming months, so it's fine for now. Thanks for working on this!

**Comment by sshmm** [comment]
@spydermonkee  I changed it in the PR commit to 40 characters as suggested by Lawris
