### ISSUE TITLE
BUG: Admin member list view should ignore casing when sorting

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#673]
**Summary:**

The user view on a circle admin page does not ignore case when sorting

1. **What is actually happening:**

uppercase names show up before lowercase names

3. **What should be happening:**

case should be ignored when sorting

4. **Steps to recreate:**

1. visit the admin page for the Conn - Friesen circle 
2. create a user with a lowercase name (e.g. 'aaa').
3. and see that all the capitalized users are first. If you scroll to page 8, the aaa name will be after the Z names

5. **Screenshots/GIF/Video recording**
<img width="630" alt="image" src="https://user-images.githubusercontent.com/95149165/159432484-800b33d4-6499-4d09-8920-b785f765d4eb.png">

**Comment by sshmm** [comment]
@spydermonkee  can I work on this issue?

**Comment by spydermonkee** [comment]
Hi @sshmm! I assigned you to this bug. I'll put it into the "in progress" column as well :)
