### ISSUE TITLE
GQL Query Error

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#675]
**Summary:**

1. **What is actually happening:**
When Creating a new circle users are experiencing a GQL Query error and they're not able to proceed with the new circle creation
![image](https://user-images.githubusercontent.com/82838264/159482188-71de82d1-d004-475c-8f28-3555f2d823a8.png)

2. **What should be happening:**
There shouldn't be an error message, and the circle should be created.

3. **Steps to recreate:**
Go to https://app.coordinape.com/new-circle and try to create a new Circle

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.
![image](https://user-images.githubusercontent.com/82838264/159482860-04edf905-d0cc-42dd-8cb5-afa7b9d3f321.png)

**Comment by topocount** [comment]
A picture of the error fully expanded in the console: 
![image](https://user-images.githubusercontent.com/17910833/159518163-f7c6cbe9-5ade-4ab8-9394-5427e3aedbfc.png)
