### ISSUE TITLE
Vouching does not update UI

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#687]
**Summary:**
Vouching for a nominee does not update the UI at all

1. **What is actually happening:**
I go to vouch for a user in the "Conn - Friesen " Health Circle after doing db-seed-fresh. vouching is happening, but the UI doesn't reflect it and still says "2 vouches required" and the button to vouch is not greyed out.  I can tap vouch again and I get an error about already having vouched. 

2. **What should be happening:**
Some visual indicators should happen - it shoudl say "1 more vouch required" or something to that effect. It should say "you have vouched for this user" instead of having a vouch button. 

3. **Screenshots/GIF/Video recording**
video of it happening:
https://www.loom.com/share/943a261af447492b8866feaa85cdf71a

**Comment by sshmm** [comment]
this one is resolved in #788
