### ISSUE TITLE
Sub-project: Migrate postgres to AWS RDS

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#715]
# Migrate our PostgreSQL DB to AWS RDS

- setup multi AZ RDS
- same region as other infra

**Comment by crabsinger** [comment]
@zashton thinking you might want to tackle this issue at some point?

**Comment by zashton** [comment]
> @zashton thinking you might want to tackle this issue at some point?

yeap i could work on this after i'm done with the hasura backend code work
