### ISSUE TITLE
Map line weights need a max thickness

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#733]
**Summary:**

1. **What is actually happening:**
2. When a user allocated significantly more than other users the line weights look bad in the map tab

3. **What should be happening:**
4. There should be a max thickness for the lines

5. **Steps to recreate:**
6. Set yourself 1000 give and allocate to a user, 

7. **Screenshots/GIF/Video recording**
8. 
![Screenshot_20220402-001722](https://user-images.githubusercontent.com/82838264/161367606-fd2c40da-27e0-4dd3-95e9-b243642ebd47.png)

**Comment by levity** [comment]
If possible, this max thickness should be dynamic based on the current zoom scale, i.e. "80% of the current average width of a sender or recipient's circle"

**Comment by reeserj** [comment]
Much better!

**Comment by reeserj** [comment]
Still looks good @levity
