### ISSUE TITLE
Create Epoch form doesn't immediately go into loading state upon clicking save

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#741]
1. **What is actually happening:**
When I click save (which should probably be "Create") on the Create Epoch modal, the loading state does not immediately initiate. There is some lag, and then it initiates. This allows for double clicks of the save button. I thought it wasn't working and clicked again, which eventually ended up in an error state. 

2. **What should be happening:**
The loading indicator should be immediately present and the save button should be disabled upon clicking "Save"

3. **Steps to recreate:**
Visit the admin page for a circle, click create epoch, click save. 

4. **Screenshots/GIF/Video recording**
https://www.loom.com/share/0970c5d194004a689788b5aefd14e483

**Comment by zashton** [comment]
> @reeserj can I work on this?

yes please @sshmm .
Update Epoch has this issue as well
