### ISSUE TITLE
What have you been working on prompt doesn't auto-populate to match the circle name

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#747]
**Summary:**

1. **What is actually happening:**
-The what have you been working on prompt doesn't match the case of the Circle Name
2. **What should be happening:**
- The case of the Circle name and the epoch statement should match
3. **Steps to recreate:**
- Create a circle with a two word name and upper case the 2nd name EG "Delete TesT" 
- Go to allocate tab, and see the contribution prompt.
4. **Screenshots/GIF/Video recording**
![image](https://user-images.githubusercontent.com/82838264/162208354-0c784707-0db5-44ef-9f61-c7399b772575.png)

**Comment by cashd** [comment]
Hey @reeserj I can take this issue on! Just skimmed the component and can already see the line causing the issue :)

**Comment by reeserj** [comment]
Assigned to @cashd! Thanks!

**Comment by cashd** [comment]
@reeserj Hey just wanted to clarify on the intention here. Right now we are capitalizing the circle name in sentence case. Do we want the original circle name to be the source of truth or another format?

**Comment by reeserj** [comment]
I think we'd want the Circle name to match the case that it's entered in the Admin settings @cashd
