### ISSUE TITLE
Clicking on "Vouch for [user]" button, UI does not update, appears not to vouch

### ISSUE THREAD

**Issue by AlexDistill** [coordinape/coordinape#749]
**Summary:**

1. **What is actually happening:**

On the vouching tab, I click on the "Vouch for [user] button" and nothing appears to happen in the UI. No change to "2 vouches needed to confirm" –I click it again and error appears: "voucher has already vouched for this nominee" so it appears it is taking my vouch but not updating the UI?

3. **What should be happening:**
The UI should update when I vouch (number of vouches needed should go down and i should be added to list of _vouchers)_

5. **Steps to recreate:**
Go to vouching page, click on "vouch for [user] button

7. **Screenshots/GIF/Video recording**
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/2601663/162485780-fc4e8453-aade-482e-9a5a-7be2c064199d.png">

**Comment by levity** [comment]
@sshmm maybe you'd be interested in looking at this, since you were just
working on nomination?

**Comment by sshmm** [comment]
@levity  yes, I will look into it :)

**Comment by sshmm** [comment]
@levity I see that the nominations is stored in DB but nominations are returned as empty array. 
Should I wait untill fullcircle fetch is fully migrated to hasura?

**Comment by levity** [comment]
Can you try fetching the nominees from Hasura instead of using the recoil hooks? Let me know if that seems doable
