### ISSUE TITLE
Tags displayed on my profile do not match tags I selected in edit profile UI

### ISSUE THREAD

**Issue by AlexDistill** [coordinape/coordinape#750]
**Summary:**

1. **What is actually happening:**
My profile displays these tags: 
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/2601663/162486642-2bc94fce-1957-41fa-bdd2-8d9f67460c07.png">
but those are not the tags I selected in the edit profile UI
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/2601663/162486715-7386371c-738e-48be-a2c0-9ac957420cbb.png">

I can deselect some tags and they go away from profile, can re-add tags and that all seems to work, but a subset of tags still remain on my profile despite not being selected in edit ui
<img width="945" alt="image" src="https://user-images.githubusercontent.com/2601663/162487299-de2459a2-e00c-4512-960f-a971c24c65c7.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/2601663/162487349-9c6afcdc-3f46-4615-b5a7-098bab6b7ac5.png">

3. **What should be happening:**
skill tags shown on my profile should be same as skills tags I select in edit profile UI

7. **Screenshots/GIF/Video recording**
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/2601663/162487221-5d741664-182f-44b5-9e8c-4daea59422de.png">

**Comment by sshmm** [comment]
@reeserj  anyone working on this?

**Comment by reeserj** [comment]
Not to my knowledge! You want it?
________________________________

**Comment by sshmm** [comment]
> 

yes  :)

**Comment by reeserj** [comment]
You got it,

**Comment by sshmm** [comment]
@AlexDistill  I couldn't reproduce the issue, it seems resolved. Were you trying in production or a local branch?
could you try reproduce the issue in your profile?

**Comment by reeserj** [comment]
I can't reproduce either. 

Let's close for now
