### ISSUE TITLE
Integrate Hasura getDiscordWebhook into FE

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#757]
## Summary:
Integrate Hasura getDiscordWebhook into FE.

**Comment by CryptoGraffe** [comment]
@zashton @topocount  this needs permissions that we don't currently allow. Do we need to create a view in the backend?

**Comment by zashton** [comment]
@CryptoGraffe i've already setup the permissions in `circle_private` view, you can try it out

**Comment by CryptoGraffe** [comment]
@zashton thx
