### ISSUE TITLE
Feature: Bulk Creation of users + Restore

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#775]
This task should be done using hasura's action handler

The GQL mutation should accept an input of `circle_id` + an array of user inputs consisting of
`name`, `address`,  (`non_giver`, `fixed_non_receiver`, `non_receiver`, `starting_tokens`, `role` ) optional will revert to DB defaults. Only a circle admin (`role` == 1) of the specific circle can perform this action

Validate that there are no duplicates of address among the array of inputs and including the (non deleted) users within the circle.
If there is a duplicate with a soft deleted user (`deleted_at` with value) overwrite the inputs into the existing record and set the `deleted_at` value to null to restore the user (there maybe more than 1 so only overwrite 1)

if there are any duplicates throw an 422 error and indicate the specific address that has issue.

for the response return the array of user objects.

@amrro

**Comment by amrro** [comment]
Thanks @zashton. You can assign me now.
