### ISSUE TITLE
Unable to delete first letter in notes box after you start typing

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#778]
**Summary:**

1. **What is actually happening:**

2. **What should be happening:**

3. **Steps to recreate:**

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.

**Comment by levity** [comment]
Duplicate of #753 -- i'm going to look into this now
