### ISSUE TITLE
Nominee discrepancy on Org Overview

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#781]
**Summary:**

1. **What is actually happening:**
When in the Circles View the number of nominees are displayed, but if we click on that circle and view the vouching tab not all of the nominees will show up. (For example if the nominee has expired) 

2. **What should be happening:**
The nominee count should match the **active** nominees 

3. **Steps to recreate:**
See the APE Test Circle 2

Or nominate 1 user in a circle, then the next day nominate 2 more users, (recommend shortening the days for vouching) and wait until the first user would expire and then view the circle from the org overview- It will still be showing 3 nominees
 
4. **Screenshots/GIF/Video recording**
![image](https://user-images.githubusercontent.com/82838264/163458870-c336f604-8117-477f-bc35-5efa6cac74ee.png)

![image](https://user-images.githubusercontent.com/82838264/163458895-31204013-1cac-4216-b614-81e87de70f49.png)

**Comment by levity** [comment]
Fix should be pretty straightforward -- have to add a check against the expiry date in the getOrgData graphql query
