### ISSUE TITLE
Update Discord Link on home page and the app

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#782]
**Problem**
With the completion of https://github.com/coordinape/coordinape/issues/619 we need to update the discord links within Coordinape. 

**Solution**
I have updated the links in the docs, Ivy updated the link in the feedback form to the following link: https://discord.coordinape.com/

We need to update the links on the landing page in the splash image 
![image](https://user-images.githubusercontent.com/82838264/163463321-e742ebd9-16f4-4529-af1a-e48288b91707.png)
 
and the footer
![image](https://user-images.githubusercontent.com/82838264/163463356-7fc4a3ba-9396-44a2-a813-6f11ccf121e5.png)

and the create a circle portion of the app
![image](https://user-images.githubusercontent.com/82838264/163463907-2774eb4f-bd8c-4678-aa29-da63a5e186f9.png)

**Specification**
Update the urls in the home page and the app

**Stakeholders**
@reeserj @spydermonkee

**Comment by crabsinger** [comment]
@ivyquinzel it seems you added this back to "Preparation" column. I think this is already done. Is there anything not done here?
