### ISSUE TITLE
Add a nominee after expiry data

### ISSUE THREAD

**Issue by sshmm** [coordinape/coordinape#789]
**Problem**
If nomination period ended, it is not possible to re-add a nominee.
![image](https://user-images.githubusercontent.com/34943689/163694223-e571d72c-a551-482e-981a-8ff046be1a70.png)

**Solution**
Update the expiry-date with a new value if the an expired nomination is re-nominated

**Comment by levity** [comment]
> Update the expiry-date with a new value if an expired nomination is re-nominated

This solution makes sense to me. @reeserj do you think existing circle admins will be cool with this?

**Comment by reeserj** [comment]
@levity yes. I don't think there'd be any pushback on this.

Should I move it to the ready for coding column?

**Comment by levity** [comment]
Yes please!

**Comment by levity** [comment]
good point! we never caught this in the original design.
