### ISSUE TITLE
Clickable Circles Profile Page

### ISSUE THREAD

**Issue by ivyquinzel** [coordinape/coordinape#799]
### Summary
Users are having trouble navigating to different circles. The profile page is an opportunity to create a workaround. 

### Specification
Make the circles displayed on the profile clickthrough the referenced circles. 

### Acceptance Criteria
Scenario: A user is trying to find the other circles they are in
When: They click on their profile image
Then: Navigate to My Profile
Given: They are in multiple circles
Then: The user clicks a "Core Coordinape" under "My Circle."
Given: The user is a member of "Core Coordinape"
Then: The user will land on the history page of the circle "Core Coordinape."

URL: https://app.coordinape.com/profile/me

<img width="726" alt="Screen Shot 2022-04-22 at 3 49 12 PM" src="https://user-images.githubusercontent.com/83605543/164814530-2564b741-4ec6-4ab3-ba4a-84824e4367cd.png">

### Stakeholders
@smombartz @AlexDistill

**Comment by levity** [comment]
Implementation note: these show up for all profiles, not just your own, and include circles that the viewer is not a member of. So only circles that the viewer is a member of should be clickable.

@ivyquinzel btw, I added a "My Circles" link to the avatar menu that just does the same thing as clicking "Circles" in the navbar.

**Comment by reeserj** [comment]
@spydermonkee could we assign this any dev or do we need something additional?

**Comment by spydermonkee** [comment]
@reeserj - This is definitely a good Community Dev issue!

**Comment by akkikumar72** [comment]
Please assign this to me. I can work on it

**Comment by reeserj** [comment]
> Please assign this to me. I can work on it

You got it! @akkikumar72

**Comment by akkikumar72** [comment]
@ivyquinzel - I  saw that we have a `My circles` page, which does the same thing. Either we can make this page a bit better or we can use the existing profile page to navigate b/w circles

![Mycircles](https://user-images.githubusercontent.com/4746256/164979295-47b2cc68-d381-4167-bcf7-bd2b80fa3e9b.png)

**Comment by reeserj** [comment]
This is needed because if you're in an organization with circles you're not
in this will display them.

**Comment by akkikumar72** [comment]
We can navigate b/w circles here as well. 

Trying to understand the difference b/w the `My Circles` menu page and the "My Circles" section on the profile page.

**Comment by reeserj** [comment]
Menu page will have all circles in the org, the profile page with just have circles you're in
________________________________
