### ISSUE TITLE
Bulk Deletion of Users

### ISSUE THREAD

**Issue by zashton** [coordinape/coordinape#807]
# Enable API Support for bulk deletion of users via Graphql API

This task should be done using hasura's action handler

The GQL mutation should accept an input of `circle_id` + an array of `addresses`

Validate that there are no duplicates of `address` among the array of `addresses` in the input. 
if there are any duplicates throw an 422 error and indicate the specific `addresses` that has issue.

To delete a user set the `deleted_at` column of the user to current timestamp
also delete records from `teammates` table where user is == `user_id` or == `team_mate_id`.
The event trigger will handle the cleanup of the accounting if the circle is in an active epoch. (Do test if this is working correctly)

for the response return a `success` boolean.

**Comment by spydermonkee** [comment]
@zashton - why do we need to build this functionality?

**Comment by zashton** [comment]
> @zashton - why do we need to build this functionality?

User requested so i put it up, some circles wanted to bulk delete users from their circle and import in a whole list of contributors for different epochs.

**Comment by zashton** [comment]
> Is this functionality still required?

Not a priority at the moment, but if you're interested to you can have a go at it.

**Comment by FilipeAleixo** [comment]
Sounds good, I'm on it
