### ISSUE TITLE
allow setting fixed payment amount in member settings

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#809]
- field is disabled if fixed payments are off in circle settings, but any existing value is still shown
  - the message about needing to enable fixed payments is shown outside the field
- if fixed payments are on, the token type is shown next to the field, i.e. [1000 | USDC]
- show the fixed payment amounts in a column in the member table

Depends on #888

**Comment by sshmm** [comment]
@levity  does this issue includes adding fixed amount option to the circle and fixed amount column?

**Comment by levity** [comment]
@sshmm it does include adding the column to the member table, but adding the option to the circle is covered by #808
