### ISSUE TITLE
allow changes to fixed payment amounts in bulk user update

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#810]
Depends on #888

**Comment by topocount** [comment]
@levity ah, yeah a bulk update endpoint hasnt yet been implemented in Hasura.

**Comment by zashton** [comment]
> There was Laravel support for this but I don't know if it got migrated to Hasura. @zashton ?

yeah we only had bulk create backend currently. didn't migrate those bulk features because theres no FE/design for them

**Comment by topocount** [comment]
I'll close this for now, since there's no immediate need for it.
