### ISSUE TITLE
Autosave allocations

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#830]
**Summary:**

Autosave changes on the allocations page directly to server.

**Details:**

Currently, on the Allocate page (https://app.coordinape.com/allocation) whenever you make a change to `notes` or `GIVE` the changes are queued up and a "Save Allocations" button appears when there are unsaved changes.
<img width="276" alt="Screen Shot 2022-04-25 at 5 00 56 PM" src="https://user-images.githubusercontent.com/83605543/165193395-8914f082-2165-4bbb-9cf8-fbde9cb4d8ce.png">

See https://github.com/coordinape/coordinape/blob/c12f9c67324b2b6f00abd6347a916e1803652a1a/src/pages/AllocationPage/AllocationPage.tsx#L214

This issue is to change the functionality from queueing up all changes under the 'Save Allocations' button, to immediately making the changes against the server.

This is like switching from an old Microsoft Word model of needing to click "Save", to a Google Docs ux of autosaving.

**Notes:**
- we don't want to make too many requests to the server, so we should still queue up changes and send them every 1-5 seconds, if someone is typing into their notes.

**Design:**
Continue to show the "Save Allocation" button when changes are queued up but not yet sent to the server. Once the changes have been sent to the server, change the button to green and have it say "Allocations Saved".

**Comment by levity** [comment]
I like this idea generally. Makes a lot of sense now that we no longer need people to wallet-sign each change.

Yes to debouncing so we don't update unnecessarily.

We still need to have the button to advance to the next step, so I wouldn't change the label to something that's no longer a verb.

Introducing a new color is probably not a good idea at this juncture either.

Given that we have more dramatic changes to this flow coming soon in 1.5, I wouldn't prioritize this change now. Better to direct effort toward more lasting changes.

**Comment by smombartz** [comment]
@levity @crabsinger 

The design currently shows this save changes button
<img width="817" alt="image" src="https://user-images.githubusercontent.com/1377389/165341588-64b549cb-fee7-446f-8166-70ee83865254.png">

which could change state based on whats going on (button styles still to be finalized)
![image](https://user-images.githubusercontent.com/1377389/165341680-0722607d-c0b7-43c6-bd8b-414db203ab37.png)

**Comment by levity** [comment]
> We still need to have the button to advance to the next step, so I wouldn't change the label to something that's no longer a verb.

Whoops, strike that, this is already the last step.

**Comment by crabsinger** [comment]
this would actually be a good usecase for Hasura / Graphql and optimistic mutations (https://react-query.tanstack.com/guides/optimistic-updates). Can treat the backend as if its local state on the frontend and just have a "syncing" indicator if there's a mutation in flight using this hook: https://react-query.tanstack.com/reference/useIsMutating

**Comment by akkikumar72** [comment]
Will like to have a look at it. Is it ready to code?

**Comment by levity** [comment]
Not yet. We've got a change to this UX in the works.
