### ISSUE TITLE
What have you been working on this epoch text box doesn't expand

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#844]
**Summary:**

1. **What is actually happening:**
![image](https://user-images.githubusercontent.com/82838264/165799220-246241eb-5c3c-40e5-83db-c8c4da1860c8.png)
The box when entering text in your epoch statement doesn't expand or scroll if you have a lot of statements

2. **What should be happening:**
There should be a scroll bar so users can view their statements easily

3. **Steps to recreate:**
Enter a lot of text in your epoch statement

If you'd like to claim this issue comment below and we'll assign it!

**Comment by akkikumar72** [comment]
@reeserj created a PR for it
