### ISSUE TITLE
Visual Style Updates

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#854]
* Edit 1.5 design tokens
- main areas
    - heading and body text sizes and bold levels
    - typefaces
    - colors - check in with @smombartz  to ensure they're finalized before making changes.
    - Button variants
        - primary, secondary, form, destructive, ... (organize variants by functionality)
        - filled or outlined
        - small, medium, large
    - add these to stitches first, then make Material-UI theme file depend on stitches
- Update components to refer to variants/tokens in theme instead of specific values (un-adHoc-ing)
- Create new components from [Design Library](https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=105%3A2519)  (if they dont already exist)
- change all the button colors — should be covered by the changes above
    - all buttons on vaults page → blue
    - all submit buttons on all form modals → blue
    - next step button on allocation flow → blue
    - all 4 buttons on circle admin page → blue
    - vouching page → blue
    - grey buttons on circle admin settings modal → grey outline, no icons

**Comment by levity** [comment]
Part 1 (#856) is laying the groundwork in the code, and can be merged into production as soon as it's approved; Part 2 will be switching over the colors and buttons to the 1.5 style, and should be batch-released with the other tasks in the [milestone](https://github.com/coordinape/coordinape/milestone/8).

**Comment by wingfeatherwave** [comment]
now part of https://github.com/coordinape/coordinape/pull/934
