### ISSUE TITLE
When nomination fails due to a server error, that error should be shown

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#855]
On the vouching page (in NewNominationModal), when the data is submitted, the submission could fail due to [server-side errors](https://github.com/coordinape/coordinape/blob/main/api/hasura/actions/createNominee.ts#L49). But [the code does not display them](https://github.com/coordinape/coordinape/blob/main/src/pages/VouchingPage/NewNominationModal.tsx#L101).

Fix: Change NewNominationModal so that server-side errors are displayed the same as form validation errors.

**Comment by akkikumar72** [comment]
I would like to look into it. Please assign it to me.

**Comment by akkikumar72** [comment]
Lets close this issue
