### ISSUE TITLE
Allow uploading a logo for an organization

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#861]
Show the logo next to the organization name on [the overview/dashboard page](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=4702%3A11975)

- Click the logo to show a file upload prompt
- Show an error message if the file chosen is not an image
- Take a centered square crop of the image file chosen and upload it to S3
- Update the backend with the new image path

**Comment by sshmm** [comment]
@levity  can I start working on this?

**Comment by levity** [comment]
Sure. Please follow the example of profile image uploading for the backend integration, and let us know in Discord if you have any questions.
