### ISSUE TITLE
1.5.2- Create Contributions page & route & Nav item

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#863]
**Specification** [Figma Link ](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5149%3A18991)
add page header, copy, and route

This removes the "my epoch" page

Depends on #854 & #852 being done

**Comment by karelianpie** [comment]
I'll start working on this @reeserj

**Comment by levity** [comment]
We should first start building the other aspects of 1.5 that have been prioritized ahead of this. @spydermonkee or @crabsinger can you point @karelianpie to one of those?

**Comment by topocount** [comment]
Update on this. All have been created except for the nav item. I think we might want to leave this hidden for a bit longer.
