### ISSUE TITLE
1.5.2- Implement Dework/Wonder Integration in new contributions page

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#868]
**Specification**

Follow the [1.5 specs] and my notes about signalling that contribution entries are non-interactive. No buttons or save text in the drawer.

[1.5 specs]: https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=2603%3A3922

#1460 provides the hook to be used to pull in integrated contributions using a `start_date` and `end_date`.

Utilize the above hook in `ContributionsList` here: https://github.com/coordinape/coordinape/blob/477029133880bdd450c3a42c0d6c57b3c1cc40e9/src/pages/ContributionsPage/ContributionsPage.tsx#L545

Group all the integrations at the bottom of the epoch since these integrations don't provide dates for us to sort on at this time. Make sure the drawer opens without a date for integration contributions since we don't have one to display. You'll also want to shape the integration contributions to conform to the shape of the Contributions in this page.

Be sure to handle the case where no epoch is passed down by just querying for all contributions from the newest epoch end date onwards.

Be sure to add the favicons found here: https://github.com/coordinape/coordinape/blob/910bacecdbf3ac68bbb1e5c2baa9ae6993db4eba/src/components/ProfileCard/ContributionSummary.tsx#L6

_original notes from Reese:_
Test to make sure data still shows correctly in the new UI, and make any changes needed
*Note- Each Dework item should also be represented as a single contribution item.

#584 - Dework integration

**Comment by sshmm** [comment]
> Be sure to handle the case where no epoch is passed down by just querying for all contributions from the newest epoch end date onwards.

is not that handled inside useContributions hook?
