### ISSUE TITLE
Create backend schema for fixed payments

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#888]
Migrations
- new varchar column in circle: `fixed_payment_token_type` (token symbol)
- new boolean column in circle: `fixed_payment_enabled`
- new numeric column in user: `fixed_payment_amount`

Hasura
- allow circle admins to view & edit the new columns above
- allow circle users to view their own `fixed_payment_amount` & the circle's fixed payment settings

**Comment by zashton** [comment]
@levity i could take this one as well
