### ISSUE TITLE
Copy the cypress images and videos during CI into github artifacts so that we can watch failure videos

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#899]

**Comment by akkikumar72** [comment]
Is it https://github.com/coordinape/coordinape/blob/main/.github/workflows/CI.yml#L107-L113?

**Comment by levity** [comment]
this is already happening--it's downloadable from the actions page (e.g. https://github.com/coordinape/coordinape/actions/runs/3202257148), but only when there's a cypress failure
