### ISSUE TITLE
1.5.3- Allow keyboard navigation though the member list

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#929]
[1.5.3 Allocation Updates Notion](https://www.notion.so/coordinape/1-5-Allocations-Updates-21274b560fd74d1d9c9f99fda6dbe636) ||| No Figma

On the new Give page `circles/ID/givebeta`

Enable keyboard navigation through members

When a members drawer is open (but focus is NOT in the feedback text input), set these keyboard navigations:

j: go down one member
k: go up one member

These should match the  Up and Down buttons shown here:

<img width="239" alt="Screen Shot 2022-09-28 at 11 41 00 AM" src="https://user-images.githubusercontent.com/83605543/192862903-c82c21c1-1849-4a71-8400-3f19e47ae18d.png">

**Comment by reeserj** [comment]
Depends on #928 being completed

**Comment by akkikumar72** [comment]
I'll work on this, plz assign it to me.

**Comment by reeserj** [comment]
Being Resolved by #1432
