### ISSUE TITLE
New Circle page just spins if there's no wallet connected

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#951]
**Summary:**

1. **What is actually happening:**
New Circle page will load forever if there's no wallet connected
2. **What should be happening:**
We should have a prompt to connect your wallet while that page is loading.
3. **Steps to recreate:**
Go to https://app.coordinape.com/new-circle with your wallet disconnected.
4. **Screenshots/GIF/Video recording**
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/82838264/169853766-51651d97-36a7-4906-91c4-1acf99bf0170.png">

@AlexDistill or @smombartz do you have opinions on how this text should be displayed?

**Comment by smombartz** [comment]
@reeserj depending on what makes most sense, forwarding users to a login page or showing an overlay both options here (there should probably be a standard way of doing this so its the same for all instances)

- [Connect Wallet Page](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=9329%3A28325)
- [Connect Wallet Overlay](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=9329%3A28576)

**Comment by akkikumar72** [comment]
I would like to work on it. Please assign it to me.

**Comment by reeserj** [comment]
Hey @akkikumar72 just following up on this one! 

Anything blocking you here?

**Comment by levity** [comment]
It's going to be fixed by my PR #989

**Comment by levity** [comment]
Should be fixed now (pending deploy to prod)
