### ISSUE TITLE
Add multi-org support to vaults page

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#953]
To match the 1.5 design & behavior, the vaults page needs to let the user switch between all of their orgs (see [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=3020%3A3780))

So the page needs to be updated with an org switcher at the top, and the ability to load & show the list of vaults for the org that is currently selected.

Adding this to the 1.5.1 milestone because it's related to those changes, but technically it doesn't need to be done until vaults launch.

**Comment by spydermonkee** [comment]
@levity - IYO, is this a decent issue for a community dev who has proven capable?

**Comment by levity** [comment]
Sure. It's small enough that anyone with some experience with Stitches and react-query should be able to handle it.

Actually, now that you've got me thinking about it, I'm going to add more detail to the spec.

**Comment by levity** [comment]
FYI I'm working on a fix related to this
