### ISSUE TITLE
1.5.6 - Admin Updates - General Section

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#963]
UI: @wingfeatherwave is working on some general UI for the settings page

_Dependent on #962_

**Any data fetching to be rebuilt using Zeus**

[See Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=3560%3A11926)

Pull fields from the Settings modal into the General Section
Update toggles to radio buttons

**Sub Sections:**
Epoch Settings
Epoch Timing

**Comment by spydermonkee** [comment]
@karelianpie - After some careful prioritization work, we have identified https://github.com/coordinape/coordinape/milestone/14 as the best next priority to work on. @sshmm has started https://github.com/coordinape/coordinape/issues/962 , which all issues in this admin updates milestone depend on. Would you like to take this issue and coordinate with sshmm?

**Comment by karelianpie** [comment]
> @karelianpie - After some careful prioritization work, we have identified https://github.com/coordinape/coordinape/milestone/14 as the best next priority to work on. @sshmm has started #962 , which all issues in this admin updates milestone depend on. Would you like to take this issue and coordinate with sshmm?

Sounds good, @sshmm keep me posted on your progress and then I can start working on this one 🙇

**Comment by karelianpie** [comment]
@spydermonkee is this issue still valid? I was having a look and I'm a bit confused about the work that happened in https://github.com/coordinape/coordinape/issues/962

**Comment by reeserj** [comment]
@karelianpie the bulk of this issue is to build the data fetching using Zeus.

However, we do now have a situation where we have two scroll bars in one window 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/82838264/174502240-8171dc11-b851-4160-af87-dcee8825a3fb.png">


It looks like @sshmm could be addressing it in #1056 though.
