### ISSUE TITLE
1.5.6 - Admin Updates - Danger Zone

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#966]
Dependent on https://github.com/coordinape/coordinape/issues/962

Any data fetching to be rebuilt using Zeus

[See Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=3560%3A11926)

**Subsections**
- Permanently Remove Circle

Build Modal [Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5859%3A28498)
- **Make clicking remove inactivate the circle.**

**Comment by sshmm** [comment]
@spydermonkee  should clicking delete the circle send a delete action to Hasura? I can't find active column in circles table

**Comment by levity** [comment]
We need to add a deleted_at column

And then to change all the users of circles to include ‘deleted_at is null’
in their queries

It would be better to create a Postgres view of circles that always
includes that filter, and then have all other tables use that view…
migrating the schema to this might be tricky though.

**Comment by sshmm** [comment]
closed by #1262
