### ISSUE TITLE
When allocating, some users have reported GIVE mysteriously moving around from one person to another 

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#979]
This was reported by Zakku, hopefully we can reproduce or get more detail.

**Comment by reeserj** [comment]
I think this has something to do with where your mouse cursor is when you scroll will try to capture video

**Comment by sshmm** [comment]
> I think this has something to do with where your mouse cursor is when you scroll will try to capture video
> 
> To recreate:
> 
>     * Click the number like your going to type the amount of GIVE when allocating funds
> 
>     * Scroll your mouse
>       The allocation should tick up or down.
> 
> 
> Suggest disabling this feature
I tried these steps
This is a nice feature and it only affects the input that you click and not the other users
