### ISSUE TITLE
When allocating, it is suprising that navigating away from the page and back loses all your allocation and notes

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#980]
This was reported by Zakku

**Comment by reeserj** [comment]
This will be resolved with the auto save features @META-DREAMER is working on #830 I'm going to close this

**Comment by CryptoGraffe** [comment]
FWIW @reeserj I think I'm tackling this with the 1.5 allocation work, not sure about @META-DREAMER  - don't want to duplicate if he has something cookin'
