### ISSUE TITLE
1.5.6- Fixed Payments Sections

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#982]
Dependent on https://github.com/coordinape/coordinape/issues/962 and https://github.com/coordinape/coordinape/milestone/7 

Any data fetching to be rebuilt using Zeus

[Figma](https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=5303%3A21149)

Token Address should return the token name after entered
Members count of members on fixed payments
Fixed payments total = Sum of fixed payments per epoch
Available in vault should read 0 when no vault available.

**Comment by EsteFilipe** [comment]
@reeserj interested in working on this. does #962 have to be finished first for this is workable on?

**Comment by reeserj** [comment]
I think you could work on it, but would need to check in with @sshmm to ensure you're aligned. I'll assign it to you

**Comment by crabsinger** [comment]
@FilipeAleixo #962 is merged. Do you still want to take this ticket and can begin working on it now? Or shall we assign to another person?

**Comment by sshmm** [comment]
@FilipeAleixo  please sync with #1056 until it's reviewed and merged if you are going to work on it

**Comment by FilipeAleixo** [comment]
@crabsinger I'm currently short on bandwith, so it's better assigning to someone else

**Comment by crabsinger** [comment]
@spydermonkee is this a blocker for Vaults launching?

**Comment by sshmm** [comment]
can I work on this?

**Comment by reeserj** [comment]
You got it @sshmm

**Comment by sshmm** [comment]
closed by #1287
