### ISSUE TITLE
Add "Pay with Parcel" Button setting under Integrations

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#985]
## Summary: Add "Pay with Parcel" Button setting under Integrations #985

Add a "Pay with Parcel" button to the site under the integrations section so users can know we support an integration with Parcel. This first version of this will be simple, a button that links to our Docs page for the Parcel Integration.

**Specification**

In Circle Admin Settings, add a new "Integration" button for Parcel. See https://github.com/coordinape/coordinape/blob/main/src/pages/AdminPage/AdminIntegrations.tsx

Follow the style set by the Dework integration. We will need to add a new SVG asset for the Parcel icon. The button text should read "Pay with Parcel". The button should link to our parcel docs. There should be no updates to our database or anything else for this change.
![parcel-logo](https://user-images.githubusercontent.com/83605543/171966696-8a530a63-a96c-4ed6-bd2c-0dd596475f08.svg)

Parcel logo svg asset attached

**Comment by crabsinger** [comment]
@reeserj do we have a docs page yet for the Parcel Integration? When ready, this button will link to it.

**Comment by karelianpie** [comment]
@reeserj following the discussion [here](https://github.com/coordinape/coordinape/issues/863#issuecomment-1145583098), @crabsinger suggested [here](https://discord.com/channels/845400066532704256/898299792575299654/982020139501383720) this one as a better issue to be worked on.
