### ISSUE TITLE
Handle bad image upload errors on OrgLogoUploader

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape#990]
**Summary:**

https://github.com/coordinape/coordinape/pull/909 introduced a bug edge case, where if you upload a file with a valid filepath, but invalid data, the error that results isn't handled. This issue should address and fix it.

1. **What is actually happening:**

If you take a text file, and rename it to a valid image filename like `badimage.jpg` and then try to upload this image as an Org Logo, the error is not captured, and the page spins indefintely.

2. **What should be happening:**
The error should be rescued, and the user shown an error of "invalid image file".

3. **Steps to recreate:**
Create a bad image via 
```
❯ echo "thanksforcontributing" > badimage.jpg
```

Try to upload this image to the OrgLogo uploader.

The graphql returns an internal error, and this error is not handled.

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.

<img width="543" alt="Screen Shot 2022-06-03 at 9 32 08 AM" src="https://user-images.githubusercontent.com/83605543/171907394-b063e5e1-da61-485a-b793-8bdf7fe5401a.png">

**Comment by sshmm** [comment]
@crabsinger  Ok I will look into this
